/** Emits the generated Go models, validators, decoders and encoders. */

import {
  resolveRef,
  type MessageSpec,
  type Node,
  type ObjectNode,
  type ProtocolModel,
  type PropertySpec,
} from "./schema-model.ts";

const BANNER = [
  "// Code generated by packages/protocol/tools/generate.ts from",
  "// schemas/connector/v1.schema.json. DO NOT EDIT.",
  "",
  "package connectorv1",
  "",
].join("\n");

const INITIALISMS = new Map<string, string>([
  ["id", "ID"],
  ["ids", "IDs"],
  ["url", "URL"],
  ["urls", "URLs"],
  ["json", "JSON"],
  ["http", "HTTP"],
  ["https", "HTTPS"],
  ["api", "API"],
  ["tls", "TLS"],
  ["ip", "IP"],
  ["mcp", "MCP"],
]);

function goPart(part: string): string {
  const lower = part.toLowerCase();
  const initialism = INITIALISMS.get(lower);
  if (initialism !== undefined) return initialism;
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

/** Converts a schema name or enum value into an exported Go identifier. */
export function goName(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/u)
    .filter((part) => part.length > 0)
    .map((part) => goPart(part))
    .join("");
}

function literal(value: string): string {
  return JSON.stringify(value);
}

function comment(text: string, indent = ""): string {
  if (text === "") return "";
  const width = 84 - indent.length;
  const words = text.split(/\s+/u);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line === "") line = word;
    else if (`${line} ${word}`.length <= width) line = `${line} ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line !== "") lines.push(line);
  return lines.map((entry) => `${indent}// ${entry}`).join("\n");
}

function declComment(name: string, text: string): string {
  const header = `${name} is defined by the connector protocol schema.`;
  if (text === "") return comment(header);
  return `${comment(header)}\n//\n${comment(text)}`;
}

function lowerFirst(text: string): string {
  return text.charAt(0).toLowerCase() + text.slice(1);
}

function objectDefs(model: ProtocolModel): { defName: string; node: ObjectNode }[] {
  const result: { defName: string; node: ObjectNode }[] = [];
  for (const defName of model.defOrder) {
    const node = model.defs.get(defName);
    if (node !== undefined && node.kind === "object") result.push({ defName, node });
  }
  return result;
}

function scalarDefs(model: ProtocolModel): { defName: string; node: Node }[] {
  const result: { defName: string; node: Node }[] = [];
  for (const defName of model.defOrder) {
    const node = model.defs.get(defName);
    if (node !== undefined && node.kind !== "object") result.push({ defName, node });
  }
  return result;
}

function goTypeOfNode(model: ProtocolModel, node: Node, refName: string | null): string {
  switch (node.kind) {
    case "string":
      if (node.sensitive) return "SensitiveString";
      if (node.enumTypeName !== null) return node.enumTypeName;
      return "string";
    case "integer":
      return "int64";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "array": {
      const itemNode = node.itemRef === null ? node.item : resolveRef(model, node.itemRef);
      return `[]${goTypeOfNode(model, itemNode, node.itemRef)}`;
    }
    case "object":
      return node.typeName;
    case "dynamic":
      return "any";
  }
  throw new Error(`unsupported node for ${refName ?? "anonymous"}`);
}

function goTypeOf(model: ProtocolModel, property: PropertySpec): string {
  const node = property.ref === null ? property.node : resolveRef(model, property.ref);
  const base = goTypeOfNode(model, node, property.ref);
  if (!property.optional) return base;
  if (node.kind === "array") return base;
  return `*${base}`;
}

function validatorName(defName: string): string {
  return `validate${goName(defName)}`;
}

function inlineValidatorName(owner: ObjectNode, property: PropertySpec): string {
  return `validate${owner.typeName}${goName(property.name)}`;
}

export function emitGoTypes(model: ProtocolModel): string {
  const out: string[] = [BANNER];

  out.push(comment(`ProtocolName is the protocol described by ${model.title}.`));
  out.push(`const ProtocolName = ${literal(model.name)}\n`);
  out.push(
    comment(
      "ProtocolVersion is the only version this build accepts. An envelope carrying any other value is rejected with ErrorClassProtocolUnsupported and is never best-effort parsed.",
    ),
  );
  out.push(`const ProtocolVersion int64 = ${model.version}\n`);

  out.push(comment("Byte bounds enforced on raw frames before deserialisation."));
  out.push("const (");
  out.push(`\tMaxControlFrameBytes = ${model.limits.max_control_frame_bytes}`);
  out.push(`\tMaxDataStreamHeaderBytes = ${model.limits.max_data_stream_header_bytes}`);
  out.push(")\n");

  out.push(comment("Channel is a logical channel of the connector protocol."));
  out.push("type Channel string\n");
  out.push("const (");
  for (const [channel, description] of model.channels) {
    out.push(comment(`Channel${goName(channel)} carries ${lowerFirst(description)}`, "\t"));
    out.push(`\tChannel${goName(channel)} Channel = ${literal(channel)}`);
  }
  out.push(")\n");
  out.push(comment("ChannelValues lists every channel in declaration order."));
  out.push(
    `var ChannelValues = []Channel{${[...model.channels.keys()].map((channel) => `Channel${goName(channel)}`).join(", ")}}\n`,
  );

  for (const enumType of model.enums) {
    out.push(declComment(enumType.typeName, enumType.description));
    out.push(`type ${enumType.typeName} string\n`);
    out.push("const (");
    for (const value of enumType.values) {
      out.push(`\t${enumType.typeName}${goName(value)} ${enumType.typeName} = ${literal(value)}`);
    }
    out.push(")\n");
    out.push(comment(`${enumType.typeName}Values lists every value in declaration order.`));
    out.push(
      `var ${enumType.typeName}Values = []${enumType.typeName}{${enumType.values.map((value) => `${enumType.typeName}${goName(value)}`).join(", ")}}\n`,
    );
  }

  out.push(comment("MessageDirection states which side of the trust boundary sends a message."));
  out.push("type MessageDirection string\n");
  out.push("const (");
  out.push('\tDirectionConnectorToControlPlane MessageDirection = "connector_to_control_plane"');
  out.push('\tDirectionControlPlaneToConnector MessageDirection = "control_plane_to_connector"');
  out.push(")\n");

  out.push(comment("MessageDirections records the sender of each message type."));
  out.push("var MessageDirections = map[MessageType]MessageDirection{");
  for (const message of model.messages) {
    const direction =
      message.direction === "connector_to_control_plane"
        ? "DirectionConnectorToControlPlane"
        : "DirectionControlPlaneToConnector";
    out.push(`\tMessageType${goName(message.type)}: ${direction},`);
  }
  out.push("}\n");

  out.push(comment("MessageChannels records the channel each message type travels on."));
  out.push("var MessageChannels = map[MessageType]Channel{");
  for (const message of model.messages) {
    out.push(`\tMessageType${goName(message.type)}: Channel${goName(message.channel)},`);
  }
  out.push("}\n");

  out.push(
    comment(
      "PayloadMaxBytes records the maximum canonical payload size for each message type. A payload larger than its bound is rejected.",
    ),
  );
  out.push("var PayloadMaxBytes = map[MessageType]int{");
  for (const message of model.messages) {
    const payload = model.defs.get(message.payloadDef);
    if (payload === undefined || payload.kind !== "object" || payload.maxBytes === null) {
      throw new Error(`payload ${message.payloadDef} has no bound`);
    }
    out.push(`\tMessageType${goName(message.type)}: ${payload.maxBytes},`);
  }
  out.push("}\n");

  out.push(
    comment(
      "ViolationReason classifies a refused frame. Only some reasons map to a wire error class.",
    ),
  );
  out.push("type ViolationReason string\n");
  out.push("const (");
  for (const reason of model.violationReasons) {
    out.push(comment(`Reason${goName(reason.name)} reports that ${lowerFirst(reason.description)}`, "\t"));
    out.push(`\tReason${goName(reason.name)} ViolationReason = ${literal(reason.name)}`);
  }
  out.push(")\n");

  out.push(
    comment("ViolationErrorClass maps a rejection reason to the connector error class reported for it."),
  );
  out.push("var ViolationErrorClass = map[ViolationReason]ErrorClass{");
  for (const reason of model.violationReasons) {
    out.push(
      `\tReason${goName(reason.name)}: ${reason.errorClass === null ? '""' : `ErrorClass${goName(reason.errorClass)}`},`,
    );
  }
  out.push("}\n");

  out.push(comment("SchemaViolationCode identifies the kind of schema failure."));
  out.push("type SchemaViolationCode string\n");
  out.push("const (");
  for (const code of model.schemaViolationCodes) {
    out.push(`\tSchemaViolation${goName(code)} SchemaViolationCode = ${literal(code)}`);
  }
  out.push(")\n");

  out.push(comment("SchemaViolation is one schema failure, located by JSON path."));
  out.push("type SchemaViolation struct {");
  out.push('\tPath string `json:"path"`');
  out.push('\tCode SchemaViolationCode `json:"code"`');
  out.push('\tMessage string `json:"message"`');
  out.push("}\n");

  out.push(
    comment(
      "KnownCapabilities lists the capabilities known at this protocol version. Unknown capabilities are accepted so that a newer connector is classified rather than rejected.",
    ),
  );
  out.push(`var KnownCapabilities = []string{${model.knownCapabilities.map(literal).join(", ")}}\n`);
  out.push(comment("KnownPlatforms lists the platforms known at this protocol version."));
  out.push(`var KnownPlatforms = []string{${model.knownPlatforms.map(literal).join(", ")}}\n`);
  out.push(comment("KnownArchitectures lists the architectures known at this protocol version."));
  out.push(`var KnownArchitectures = []string{${model.knownArchitectures.map(literal).join(", ")}}\n`);

  out.push(
    comment(
      "IdentifierPrefixes records the conventional prefixes of the opaque identifiers this protocol carries. They are documentation only: consumers must treat identifiers as opaque and validators must not require a prefix.",
    ),
  );
  out.push("var IdentifierPrefixes = map[string]string{");
  for (const [field, prefix] of model.identifierPrefixes) {
    out.push(`\t${literal(field)}: ${literal(prefix)},`);
  }
  out.push("}\n");

  for (const { defName, node } of scalarDefs(model)) {
    if (node.kind === "string" && node.enumTypeName !== null) continue;
    out.push(declComment(goName(defName), node.description));
    out.push(`type ${goName(defName)} = ${goTypeOfNode(model, node, defName)}\n`);
  }

  for (const { node } of objectDefs(model)) {
    out.push(declComment(node.typeName, node.description));
    out.push(`type ${node.typeName} struct {`);
    for (const property of node.properties) {
      if (property.node.kind === "dynamic" && property.ref === null) continue;
      const fieldComment = comment(property.description, "\t");
      if (fieldComment !== "") out.push(fieldComment);
      const omit = property.optional ? ",omitempty" : "";
      out.push(
        `\t${goName(property.name)} ${goTypeOf(model, property)} \`json:${literal(`${property.name}${omit}`)}\``,
      );
    }
    out.push("}\n");
  }

  out.push(
    comment(
      "Payload is implemented by every version 1 message payload. The interface is closed: only payloads generated from the schema can satisfy it.",
    ),
  );
  out.push("type Payload interface {");
  out.push("\t// MessageType reports the envelope type this payload belongs to.");
  out.push("\tMessageType() MessageType");
  out.push("\tisConnectorPayload()");
  out.push("}\n");

  for (const message of model.messages) {
    const typeName = payloadTypeName(model, message);
    out.push(comment(`MessageType reports the envelope type carrying a ${typeName}.`));
    out.push(
      `func (${typeName}) MessageType() MessageType { return MessageType${goName(message.type)} }\n`,
    );
    out.push(`func (${typeName}) isConnectorPayload() {}\n`);
  }

  out.push(comment("Frame is a decoded control frame: envelope header plus its typed payload."));
  out.push("type Frame struct {");
  out.push("\tEnvelope Envelope");
  out.push("\tPayload Payload");
  out.push("}\n");

  return out.join("\n");
}

export function emitGoValidate(model: ProtocolModel): string {
  const out: string[] = [BANNER];
  const patterns: string[] = [];
  const patternNames = new Map<string, string>();
  const patternConst = (pattern: string | null): string | null => {
    if (pattern === null) return null;
    const existing = patternNames.get(pattern);
    if (existing !== undefined) return existing;
    const name = `pattern${patternNames.size}`;
    patternNames.set(pattern, name);
    patterns.push(`var ${name} = regexp.MustCompile(${literal(pattern)})`);
    return name;
  };

  const body: string[] = [];

  const emitScalarValidator = (name: string, node: Node, description: string): void => {
    const doc = comment(`${name} checks ${lowerFirst(description === "" ? "a generated schema node." : description)}`);
    if (doc !== "") body.push(doc);
    body.push(`func ${name}(value any, path string, out *[]SchemaViolation) {`);
    switch (node.kind) {
      case "string": {
        const parts: string[] = [];
        if (node.enumValues !== null) {
          parts.push(`values: []string{${node.enumValues.map(literal).join(", ")}}`);
        } else {
          if (node.minLength !== null) parts.push(`minLength: ${node.minLength}`);
          parts.push(`maxLength: ${node.maxLength}`);
          const pattern = patternConst(node.pattern);
          if (pattern !== null) parts.push(`pattern: ${pattern}`);
        }
        body.push(`\tcheckString(value, path, out, stringOpts{${parts.join(", ")}})`);
        break;
      }
      case "integer":
        body.push(`\tcheckInteger(value, path, out, ${node.minimum}, ${node.maximum})`);
        break;
      case "number":
        body.push(`\tcheckNumber(value, path, out, ${node.minimum}, ${node.maximum})`);
        break;
      case "boolean":
        body.push("\tcheckBoolean(value, path, out)");
        break;
      case "array": {
        body.push(
          `\titems, ok := checkArray(value, path, out, ${node.minItems}, ${node.maxItems}, ${node.uniqueItems})`,
        );
        body.push("\tif !ok {");
        body.push("\t\treturn");
        body.push("\t}");
        const itemValidator = node.itemRef !== null ? validatorName(node.itemRef) : `${name}Item`;
        body.push("\tfor index, item := range items {");
        body.push(`\t\t${itemValidator}(item, indexPath(path, index), out)`);
        body.push("\t}");
        break;
      }
      case "dynamic":
        body.push("\tcheckPlainObject(value, path, out)");
        break;
      case "object":
        throw new Error("objects use the object validator");
    }
    body.push("}\n");
  };

  for (const { defName, node } of scalarDefs(model)) {
    emitScalarValidator(validatorName(defName), node, node.description);
  }

  for (const { defName, node } of objectDefs(model)) {
    for (const property of node.properties) {
      if (property.ref !== null) continue;
      if (property.node.kind === "array" && property.node.itemRef === null) {
        emitScalarValidator(`${inlineValidatorName(node, property)}Item`, property.node.item, "");
      }
      emitScalarValidator(inlineValidatorName(node, property), property.node, property.description);
    }

    body.push(comment(`${validatorName(defName)} checks a ${node.typeName} value.`));
    body.push(`func ${validatorName(defName)}(value any, path string, out *[]SchemaViolation) {`);
    body.push(
      `\tsource, ok := checkObject(value, path, out, []string{${node.properties.map((property) => literal(property.name)).join(", ")}}, []string{${node.required.map(literal).join(", ")}})`,
    );
    body.push("\tif !ok {");
    body.push("\t\treturn");
    body.push("\t}");
    for (const property of node.properties) {
      const validator =
        property.ref !== null ? validatorName(property.ref) : inlineValidatorName(node, property);
      body.push(`\tif field, present := source[${literal(property.name)}]; present {`);
      body.push(`\t\t${validator}(field, path+${literal(`.${property.name}`)}, out)`);
      body.push("\t}");
    }
    for (const rule of node.requires) {
      body.push(
        `\tif matchesCondition(source[${literal(rule.whenProperty)}], []string{${rule.whenValues.map(literal).join(", ")}}) {`,
      );
      for (const required of rule.required) {
        body.push(
          `\t\trequireProperty(source, path, ${literal(required)}, ${literal(rule.detail)}, out)`,
        );
      }
      for (const forbidden of rule.forbidden) {
        body.push(
          `\t\tforbidProperty(source, path, ${literal(forbidden)}, ${literal(rule.detail)}, out)`,
        );
      }
      body.push("\t}");
    }
    body.push("}\n");
  }

  out.push('import "regexp"\n');
  out.push(patterns.join("\n"));
  out.push("");
  out.push(body.join("\n"));
  return out.join("\n");
}

export function emitGoDecode(model: ProtocolModel): string {
  const out: string[] = [BANNER];
  out.push(
    comment(
      "Decoders build typed values from an already validated JSON tree. Calling a decoder on a value that has not passed its validator is a programming error; the frame entry points in frame.go always validate first.",
    ),
  );
  out.push("");

  for (const { defName, node } of objectDefs(model)) {
    out.push(comment(`Decode${node.typeName} builds a ${node.typeName} from a validated tree.`));
    out.push(`func Decode${node.typeName}(value any) ${node.typeName} {`);
    out.push("\tsource, _ := value.(map[string]any)");
    out.push(`\tvar out ${node.typeName}`);
    for (const property of node.properties) {
      if (property.node.kind === "dynamic" && property.ref === null) continue;
      const targetNode = property.ref === null ? property.node : resolveRef(model, property.ref);
      const field = `out.${goName(property.name)}`;
      const key = literal(property.name);
      if (!property.optional) {
        out.push(`\t${field} = ${goDecodeExpression(model, targetNode, `source[${key}]`)}`);
        continue;
      }
      out.push(`\tif field, present := source[${key}]; present {`);
      if (targetNode.kind === "array") {
        out.push(`\t\t${field} = ${goDecodeExpression(model, targetNode, "field")}`);
      } else {
        out.push(`\t\tdecoded := ${goDecodeExpression(model, targetNode, "field")}`);
        out.push(`\t\t${field} = &decoded`);
      }
      out.push("\t}");
    }
    out.push("\treturn out");
    out.push("}\n");
    void defName;
  }

  return out.join("\n");
}

function goDecodeExpression(model: ProtocolModel, node: Node, access: string): string {
  switch (node.kind) {
    case "string":
      if (node.sensitive) return `SensitiveString(decodeString(${access}))`;
      if (node.enumTypeName !== null) return `${node.enumTypeName}(decodeString(${access}))`;
      return `decodeString(${access})`;
    case "integer":
      return `decodeInt(${access})`;
    case "number":
      return `decodeFloat(${access})`;
    case "boolean":
      return `decodeBool(${access})`;
    case "array": {
      const itemNode = node.itemRef === null ? node.item : resolveRef(model, node.itemRef);
      const itemType = goTypeOfNode(model, itemNode, node.itemRef);
      return `decodeSlice(${access}, func(item any) ${itemType} { return ${goDecodeExpression(model, itemNode, "item")} })`;
    }
    case "object":
      return `Decode${node.typeName}(${access})`;
    case "dynamic":
      return access;
  }
}

export function emitGoEncode(model: ProtocolModel): string {
  const out: string[] = [BANNER];
  out.push(
    comment(
      "Canonical encoders. Output is deterministic: properties appear in schema order, absent optional properties are omitted, and numbers and strings are formatted identically to the TypeScript encoder so that both languages produce byte-identical frames.",
    ),
  );
  out.push("");

  for (const { node } of objectDefs(model)) {
    const dynamic = node.properties.find(
      (property) => property.node.kind === "dynamic" && property.ref === null,
    );
    const extraParameter = dynamic === undefined ? "" : `, ${goName(dynamic.name)}JSON []byte`;
    out.push(
      comment(
        `encode${node.typeName}Into writes the canonical encoding of a ${node.typeName}.`,
      ),
    );
    out.push(
      `func encode${node.typeName}Into(w *canonicalWriter, value ${node.typeName}${extraParameter}) {`,
    );
    out.push("\tw.beginObject()");
    for (const property of node.properties) {
      const key = literal(property.name);
      if (property.node.kind === "dynamic" && property.ref === null) {
        out.push(`\tw.key(${key})`);
        out.push(`\tw.raw(${goName(property.name)}JSON)`);
        continue;
      }
      const targetNode = property.ref === null ? property.node : resolveRef(model, property.ref);
      const field = `value.${goName(property.name)}`;
      if (property.optional) {
        out.push(`\tif ${field} != nil {`);
        out.push(`\t\tw.key(${key})`);
        const access = targetNode.kind === "array" ? field : `(*${field})`;
        for (const line of goEncodeStatements(model, targetNode, access, "\t\t")) out.push(line);
        out.push("\t}");
        continue;
      }
      out.push(`\tw.key(${key})`);
      for (const line of goEncodeStatements(model, targetNode, field, "\t")) out.push(line);
    }
    out.push("\tw.endObject()");
    out.push("}\n");

    out.push(
      comment(
        `Encode${node.typeName} returns the canonical encoding of a ${node.typeName}.`,
      ),
    );
    out.push(
      `func Encode${node.typeName}(value ${node.typeName}${extraParameter}) ([]byte, error) {`,
    );
    out.push("\tvar w canonicalWriter");
    out.push(
      `\tencode${node.typeName}Into(&w, value${dynamic === undefined ? "" : `, ${goName(dynamic.name)}JSON`})`,
    );
    out.push("\treturn w.result()");
    out.push("}\n");
  }

  return out.join("\n");
}

function goEncodeStatements(
  model: ProtocolModel,
  node: Node,
  access: string,
  indent: string,
): string[] {
  switch (node.kind) {
    case "string":
      if (node.sensitive) return [`${indent}w.string(${access}.Reveal())`];
      if (node.enumTypeName !== null) return [`${indent}w.string(string(${access}))`];
      return [`${indent}w.string(${access})`];
    case "integer":
      return [`${indent}w.integer(${access})`];
    case "number":
      return [`${indent}w.number(${access})`];
    case "boolean":
      return [`${indent}w.boolean(${access})`];
    case "array": {
      const itemNode = node.itemRef === null ? node.item : resolveRef(model, node.itemRef);
      const lines = [`${indent}w.beginArray()`, `${indent}for _, item := range ${access} {`];
      lines.push(`${indent}\tw.item()`);
      for (const line of goEncodeStatements(model, itemNode, "item", `${indent}\t`)) lines.push(line);
      lines.push(`${indent}}`);
      lines.push(`${indent}w.endArray()`);
      return lines;
    }
    case "object":
      return [`${indent}encode${node.typeName}Into(w, ${access})`];
    case "dynamic":
      return [`${indent}w.raw([]byte(${access}))`];
  }
}

export function emitGoDispatch(model: ProtocolModel): string {
  const out: string[] = [BANNER];
  out.push(
    comment(
      "Type-directed dispatch generated from x-protocol.messages. Adding a message type to the schema is the only way to add one here.",
    ),
  );
  out.push("");

  out.push(comment("validatePayload checks a payload against the schema selected by message type."));
  out.push(
    "func validatePayload(messageType MessageType, value any, path string, out *[]SchemaViolation) {",
  );
  out.push("\tswitch messageType {");
  for (const message of model.messages) {
    out.push(`\tcase MessageType${goName(message.type)}:`);
    out.push(`\t\t${validatorName(message.payloadDef)}(value, path, out)`);
  }
  out.push("\t}");
  out.push("}\n");

  out.push(comment("decodePayload builds the typed payload for a validated frame."));
  out.push("func decodePayload(messageType MessageType, value any) Payload {");
  out.push("\tswitch messageType {");
  for (const message of model.messages) {
    out.push(`\tcase MessageType${goName(message.type)}:`);
    out.push(`\t\treturn Decode${payloadTypeName(model, message)}(value)`);
  }
  out.push("\t}");
  out.push("\treturn nil");
  out.push("}\n");

  out.push(comment("EncodePayload returns the canonical encoding of any version 1 payload."));
  out.push("func EncodePayload(payload Payload) ([]byte, error) {");
  out.push("\tswitch value := payload.(type) {");
  for (const message of model.messages) {
    out.push(`\tcase ${payloadTypeName(model, message)}:`);
    out.push(`\t\treturn Encode${payloadTypeName(model, message)}(value)`);
  }
  out.push("\t}");
  out.push('\treturn nil, errUnknownPayload');
  out.push("}\n");

  out.push(comment("IsKnownMessageType reports whether a value names a version 1 message type."));
  out.push("func IsKnownMessageType(value string) bool {");
  out.push("\tswitch MessageType(value) {");
  out.push(
    `\tcase ${model.messages.map((message) => `MessageType${goName(message.type)}`).join(", ")}:`,
  );
  out.push("\t\treturn true");
  out.push("\t}");
  out.push("\treturn false");
  out.push("}\n");

  return out.join("\n");
}

function payloadTypeName(model: ProtocolModel, message: MessageSpec): string {
  const node = model.defs.get(message.payloadDef);
  if (node === undefined || node.kind !== "object") {
    throw new Error(`payload ${message.payloadDef} is not an object`);
  }
  return node.typeName;
}
