// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

// Decoders build typed values from an already validated JSON tree. Calling a decoder
// on a value that has not passed its validator is a programming error; the frame entry
// points in frame.go always validate first.

// DecodeRepositoryIdentity builds a RepositoryIdentity from a validated tree.
func DecodeRepositoryIdentity(value any) RepositoryIdentity {
	source, _ := value.(map[string]any)
	var out RepositoryIdentity
	out.Canonical = decodeString(source["canonical"])
	if field, present := source["clone_urls"]; present {
		out.CloneURLs = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	return out
}

// DecodeValidationViewport builds a ValidationViewport from a validated tree.
func DecodeValidationViewport(value any) ValidationViewport {
	source, _ := value.(map[string]any)
	var out ValidationViewport
	out.Width = decodeInt(source["width"])
	out.Height = decodeInt(source["height"])
	if field, present := source["device_scale_factor"]; present {
		decoded := decodeFloat(field)
		out.DeviceScaleFactor = &decoded
	}
	return out
}

// DecodeProjectSettings builds a ProjectSettings from a validated tree.
func DecodeProjectSettings(value any) ProjectSettings {
	source, _ := value.(map[string]any)
	var out ProjectSettings
	out.DefaultValidationViewports = decodeSlice(source["default_validation_viewports"], func(item any) ValidationViewport { return DecodeValidationViewport(item) })
	return out
}

// DecodeOrganisation builds a Organisation from a validated tree.
func DecodeOrganisation(value any) Organisation {
	source, _ := value.(map[string]any)
	var out Organisation
	out.ID = decodeString(source["id"])
	out.Name = decodeString(source["name"])
	out.Slug = decodeString(source["slug"])
	out.Status = OrganisationStatus(decodeString(source["status"]))
	out.CreatedAt = decodeString(source["created_at"])
	out.UpdatedAt = decodeString(source["updated_at"])
	return out
}

// DecodeUser builds a User from a validated tree.
func DecodeUser(value any) User {
	source, _ := value.(map[string]any)
	var out User
	out.ID = decodeString(source["id"])
	out.OrganisationID = decodeString(source["organisation_id"])
	out.Email = decodeString(source["email"])
	out.DisplayName = decodeString(source["display_name"])
	out.Status = UserStatus(decodeString(source["status"]))
	if field, present := source["local_credential_set"]; present {
		decoded := decodeBool(field)
		out.LocalCredentialSet = &decoded
	}
	out.CreatedAt = decodeString(source["created_at"])
	out.UpdatedAt = decodeString(source["updated_at"])
	return out
}

// DecodeProject builds a Project from a validated tree.
func DecodeProject(value any) Project {
	source, _ := value.(map[string]any)
	var out Project
	out.ID = decodeString(source["id"])
	out.OrganisationID = decodeString(source["organisation_id"])
	out.Name = decodeString(source["name"])
	out.Slug = decodeString(source["slug"])
	if field, present := source["repository_identity"]; present {
		decoded := DecodeRepositoryIdentity(field)
		out.RepositoryIdentity = &decoded
	}
	out.DefaultBranch = decodeString(source["default_branch"])
	out.Status = ProjectStatus(decodeString(source["status"]))
	out.Settings = DecodeProjectSettings(source["settings"])
	out.Version = decodeInt(source["version"])
	out.CreatedAt = decodeString(source["created_at"])
	out.UpdatedAt = decodeString(source["updated_at"])
	return out
}

// DecodeHumanSession builds a HumanSession from a validated tree.
func DecodeHumanSession(value any) HumanSession {
	source, _ := value.(map[string]any)
	var out HumanSession
	out.SessionID = decodeString(source["session_id"])
	if field, present := source["user_id"]; present {
		decoded := decodeString(field)
		out.UserID = &decoded
	}
	if field, present := source["organisation_id"]; present {
		decoded := decodeString(field)
		out.OrganisationID = &decoded
	}
	if field, present := source["email"]; present {
		decoded := decodeString(field)
		out.Email = &decoded
	}
	out.Display = decodeString(source["display"])
	if field, present := source["project_ids"]; present {
		out.ProjectIDs = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	out.ExpiresAt = decodeString(source["expires_at"])
	return out
}

// DecodeAgentSession builds a AgentSession from a validated tree.
func DecodeAgentSession(value any) AgentSession {
	source, _ := value.(map[string]any)
	var out AgentSession
	out.ID = decodeString(source["id"])
	if field, present := source["organisation_id"]; present {
		decoded := decodeString(field)
		out.OrganisationID = &decoded
	}
	out.ProjectID = decodeString(source["project_id"])
	if field, present := source["connector_id"]; present {
		decoded := decodeString(field)
		out.ConnectorID = &decoded
	}
	if field, present := source["workspace_id"]; present {
		decoded := decodeString(field)
		out.WorkspaceID = &decoded
	}
	out.AgentType = decodeString(source["agent_type"])
	if field, present := source["agent_version"]; present {
		decoded := decodeString(field)
		out.AgentVersion = &decoded
	}
	out.Capabilities = decodeSlice(source["capabilities"], func(item any) AgentCapability { return AgentCapability(decodeString(item)) })
	if field, present := source["branch"]; present {
		decoded := decodeString(field)
		out.Branch = &decoded
	}
	if field, present := source["head_commit"]; present {
		decoded := decodeString(field)
		out.HeadCommit = &decoded
	}
	out.Status = AgentSessionStatus(decodeString(source["status"]))
	out.StartedAt = decodeString(source["started_at"])
	if field, present := source["last_seen_at"]; present {
		decoded := decodeString(field)
		out.LastSeenAt = &decoded
	}
	if field, present := source["ended_at"]; present {
		decoded := decodeString(field)
		out.EndedAt = &decoded
	}
	return out
}

// DecodeEnvironment builds a Environment from a validated tree.
func DecodeEnvironment(value any) Environment {
	source, _ := value.(map[string]any)
	var out Environment
	out.ID = decodeString(source["id"])
	out.OrganisationID = decodeString(source["organisation_id"])
	if field, present := source["project_id"]; present {
		decoded := decodeString(field)
		out.ProjectID = &decoded
	}
	out.Name = decodeString(source["name"])
	out.Platform = decodeString(source["platform"])
	out.Architecture = decodeString(source["architecture"])
	out.Labels = decodeSlice(source["labels"], func(item any) string { return decodeString(item) })
	out.TrustLevel = EnvironmentTrustLevel(decodeString(source["trust_level"]))
	out.Status = EnvironmentStatus(decodeString(source["status"]))
	if field, present := source["last_seen_at"]; present {
		decoded := decodeString(field)
		out.LastSeenAt = &decoded
	}
	out.CreatedAt = decodeString(source["created_at"])
	return out
}

// DecodeConnector builds a Connector from a validated tree.
func DecodeConnector(value any) Connector {
	source, _ := value.(map[string]any)
	var out Connector
	out.ID = decodeString(source["id"])
	out.OrganisationID = decodeString(source["organisation_id"])
	out.EnvironmentID = decodeString(source["environment_id"])
	if field, present := source["project_id"]; present {
		decoded := decodeString(field)
		out.ProjectID = &decoded
	}
	out.CertificateFingerprint = decodeString(source["certificate_fingerprint"])
	out.CertificateNotAfter = decodeString(source["certificate_not_after"])
	out.Version = decodeString(source["version"])
	out.Capabilities = decodeSlice(source["capabilities"], func(item any) string { return decodeString(item) })
	out.Status = ConnectorStatus(decodeString(source["status"]))
	if field, present := source["connected_at"]; present {
		decoded := decodeString(field)
		out.ConnectedAt = &decoded
	}
	if field, present := source["last_heartbeat_at"]; present {
		decoded := decodeString(field)
		out.LastHeartbeatAt = &decoded
	}
	if field, present := source["revoked_at"]; present {
		decoded := decodeString(field)
		out.RevokedAt = &decoded
	}
	out.CreatedAt = decodeString(source["created_at"])
	return out
}

// DecodeWorkspace builds a Workspace from a validated tree.
func DecodeWorkspace(value any) Workspace {
	source, _ := value.(map[string]any)
	var out Workspace
	out.ID = decodeString(source["id"])
	out.OrganisationID = decodeString(source["organisation_id"])
	out.ProjectID = decodeString(source["project_id"])
	if field, present := source["environment_id"]; present {
		decoded := decodeString(field)
		out.EnvironmentID = &decoded
	}
	if field, present := source["connector_id"]; present {
		decoded := decodeString(field)
		out.ConnectorID = &decoded
	}
	out.PathHash = decodeString(source["path_hash"])
	out.DisplayPath = decodeString(source["display_path"])
	if field, present := source["repository_identity"]; present {
		decoded := decodeString(field)
		out.RepositoryIdentity = &decoded
	}
	out.Branch = decodeString(source["branch"])
	out.HeadCommit = decodeString(source["head_commit"])
	out.Dirty = decodeBool(source["dirty"])
	out.Source = WorkspaceObservationSource(decodeString(source["source"]))
	if field, present := source["last_observed_at"]; present {
		decoded := decodeString(field)
		out.LastObservedAt = &decoded
	}
	out.CreatedAt = decodeString(source["created_at"])
	return out
}

// DecodeActor builds a Actor from a validated tree.
func DecodeActor(value any) Actor {
	source, _ := value.(map[string]any)
	var out Actor
	out.Type = ActorType(decodeString(source["type"]))
	if field, present := source["id"]; present {
		decoded := decodeString(field)
		out.ID = &decoded
	}
	if field, present := source["display"]; present {
		decoded := decodeString(field)
		out.Display = &decoded
	}
	return out
}

// DecodeCorrelation builds a Correlation from a validated tree.
func DecodeCorrelation(value any) Correlation {
	source, _ := value.(map[string]any)
	var out Correlation
	if field, present := source["request_id"]; present {
		decoded := decodeString(field)
		out.RequestID = &decoded
	}
	if field, present := source["causation_event_id"]; present {
		decoded := decodeString(field)
		out.CausationEventID = &decoded
	}
	if field, present := source["connector_id"]; present {
		decoded := decodeString(field)
		out.ConnectorID = &decoded
	}
	if field, present := source["environment_id"]; present {
		decoded := decodeString(field)
		out.EnvironmentID = &decoded
	}
	if field, present := source["workspace_id"]; present {
		decoded := decodeString(field)
		out.WorkspaceID = &decoded
	}
	if field, present := source["published_service_id"]; present {
		decoded := decodeString(field)
		out.PublishedServiceID = &decoded
	}
	if field, present := source["agent_session_id"]; present {
		decoded := decodeString(field)
		out.AgentSessionID = &decoded
	}
	if field, present := source["browser_session_id"]; present {
		decoded := decodeString(field)
		out.BrowserSessionID = &decoded
	}
	if field, present := source["worker_id"]; present {
		decoded := decodeString(field)
		out.WorkerID = &decoded
	}
	if field, present := source["artefact_id"]; present {
		decoded := decodeString(field)
		out.ArtefactID = &decoded
	}
	if field, present := source["review_id"]; present {
		decoded := decodeString(field)
		out.ReviewID = &decoded
	}
	if field, present := source["finding_id"]; present {
		decoded := decodeString(field)
		out.FindingID = &decoded
	}
	if field, present := source["annotation_id"]; present {
		decoded := decodeString(field)
		out.AnnotationID = &decoded
	}
	if field, present := source["job_id"]; present {
		decoded := decodeString(field)
		out.JobID = &decoded
	}
	return out
}

// DecodeEnvelope builds a Envelope from a validated tree.
func DecodeEnvelope(value any) Envelope {
	source, _ := value.(map[string]any)
	var out Envelope
	out.ID = decodeString(source["id"])
	out.SchemaVersion = decodeInt(source["schema_version"])
	out.Sequence = decodeInt(source["sequence"])
	out.Type = MessageType(decodeString(source["type"]))
	out.OccurredAt = decodeString(source["occurred_at"])
	out.RecordedAt = decodeString(source["recorded_at"])
	out.OrganisationID = decodeString(source["organisation_id"])
	if field, present := source["project_id"]; present {
		decoded := decodeString(field)
		out.ProjectID = &decoded
	}
	out.Actor = DecodeActor(source["actor"])
	if field, present := source["correlation"]; present {
		decoded := DecodeCorrelation(field)
		out.Correlation = &decoded
	}
	return out
}

// DecodeOrganisationCreatedPayload builds a OrganisationCreatedPayload from a
// validated tree.
func DecodeOrganisationCreatedPayload(value any) OrganisationCreatedPayload {
	source, _ := value.(map[string]any)
	var out OrganisationCreatedPayload
	out.Slug = decodeString(source["slug"])
	out.Name = decodeString(source["name"])
	return out
}

// DecodeProjectCreatedPayload builds a ProjectCreatedPayload from a validated tree.
func DecodeProjectCreatedPayload(value any) ProjectCreatedPayload {
	source, _ := value.(map[string]any)
	var out ProjectCreatedPayload
	out.Slug = decodeString(source["slug"])
	out.Name = decodeString(source["name"])
	if field, present := source["default_branch"]; present {
		decoded := decodeString(field)
		out.DefaultBranch = &decoded
	}
	if field, present := source["repository_canonical"]; present {
		decoded := decodeString(field)
		out.RepositoryCanonical = &decoded
	}
	return out
}

// DecodeProjectRepositoryChangedPayload builds a ProjectRepositoryChangedPayload from
// a validated tree.
func DecodeProjectRepositoryChangedPayload(value any) ProjectRepositoryChangedPayload {
	source, _ := value.(map[string]any)
	var out ProjectRepositoryChangedPayload
	if field, present := source["previous_canonical"]; present {
		decoded := decodeString(field)
		out.PreviousCanonical = &decoded
	}
	out.NewCanonical = decodeString(source["new_canonical"])
	return out
}

// DecodeUserInvitedPayload builds a UserInvitedPayload from a validated tree.
func DecodeUserInvitedPayload(value any) UserInvitedPayload {
	source, _ := value.(map[string]any)
	var out UserInvitedPayload
	out.UserID = decodeString(source["user_id"])
	out.Method = LoginMethod(decodeString(source["method"]))
	out.ExpiresAt = decodeString(source["expires_at"])
	return out
}

// DecodeUserCredentialsSetPayload builds a UserCredentialsSetPayload from a validated
// tree.
func DecodeUserCredentialsSetPayload(value any) UserCredentialsSetPayload {
	source, _ := value.(map[string]any)
	var out UserCredentialsSetPayload
	out.UserID = decodeString(source["user_id"])
	out.Method = LoginMethod(decodeString(source["method"]))
	return out
}

// DecodeAuthenticationLoginSucceededPayload builds a
// AuthenticationLoginSucceededPayload from a validated tree.
func DecodeAuthenticationLoginSucceededPayload(value any) AuthenticationLoginSucceededPayload {
	source, _ := value.(map[string]any)
	var out AuthenticationLoginSucceededPayload
	out.SessionID = decodeString(source["session_id"])
	if field, present := source["user_id"]; present {
		decoded := decodeString(field)
		out.UserID = &decoded
	}
	out.Method = LoginMethod(decodeString(source["method"]))
	return out
}

// DecodeAuthenticationLoginFailedPayload builds a AuthenticationLoginFailedPayload
// from a validated tree.
func DecodeAuthenticationLoginFailedPayload(value any) AuthenticationLoginFailedPayload {
	source, _ := value.(map[string]any)
	var out AuthenticationLoginFailedPayload
	out.Reason = LoginFailureReason(decodeString(source["reason"]))
	out.Method = LoginMethod(decodeString(source["method"]))
	if field, present := source["user_id"]; present {
		decoded := decodeString(field)
		out.UserID = &decoded
	}
	return out
}

// DecodeSessionRevokedPayload builds a SessionRevokedPayload from a validated tree.
func DecodeSessionRevokedPayload(value any) SessionRevokedPayload {
	source, _ := value.(map[string]any)
	var out SessionRevokedPayload
	out.SessionID = decodeString(source["session_id"])
	if field, present := source["user_id"]; present {
		decoded := decodeString(field)
		out.UserID = &decoded
	}
	out.Reason = SessionRevocationReason(decodeString(source["reason"]))
	return out
}

// DecodeProjectUpdatedPayload builds a ProjectUpdatedPayload from a validated tree.
func DecodeProjectUpdatedPayload(value any) ProjectUpdatedPayload {
	source, _ := value.(map[string]any)
	var out ProjectUpdatedPayload
	out.ChangedFields = decodeSlice(source["changed_fields"], func(item any) string { return decodeString(item) })
	return out
}

// DecodeProjectArchivedPayload builds a ProjectArchivedPayload from a validated tree.
func DecodeProjectArchivedPayload(value any) ProjectArchivedPayload {
	source, _ := value.(map[string]any)
	var out ProjectArchivedPayload
	out.PreviousStatus = ProjectStatus(decodeString(source["previous_status"]))
	out.NewStatus = ProjectStatus(decodeString(source["new_status"]))
	return out
}

// DecodeConnectorEnrolledPayload builds a ConnectorEnrolledPayload from a validated
// tree.
func DecodeConnectorEnrolledPayload(value any) ConnectorEnrolledPayload {
	source, _ := value.(map[string]any)
	var out ConnectorEnrolledPayload
	out.EnvironmentID = decodeString(source["environment_id"])
	out.EnvironmentName = decodeString(source["environment_name"])
	out.Platform = decodeString(source["platform"])
	out.Architecture = decodeString(source["architecture"])
	out.ConnectorVersion = decodeString(source["connector_version"])
	out.Capabilities = decodeSlice(source["capabilities"], func(item any) string { return decodeString(item) })
	out.CertificateFingerprint = decodeString(source["certificate_fingerprint"])
	out.IdentityExpiresAt = decodeString(source["identity_expires_at"])
	if field, present := source["enrolment_token_id"]; present {
		decoded := decodeString(field)
		out.EnrolmentTokenID = &decoded
	}
	out.NewStatus = ConnectorStatus(decodeString(source["new_status"]))
	return out
}

// DecodeConnectorConnectedPayload builds a ConnectorConnectedPayload from a validated
// tree.
func DecodeConnectorConnectedPayload(value any) ConnectorConnectedPayload {
	source, _ := value.(map[string]any)
	var out ConnectorConnectedPayload
	out.PreviousStatus = ConnectorStatus(decodeString(source["previous_status"]))
	out.NewStatus = ConnectorStatus(decodeString(source["new_status"]))
	out.Trigger = ConnectorConnectedTrigger(decodeString(source["trigger"]))
	return out
}

// DecodeConnectorDegradedPayload builds a ConnectorDegradedPayload from a validated
// tree.
func DecodeConnectorDegradedPayload(value any) ConnectorDegradedPayload {
	source, _ := value.(map[string]any)
	var out ConnectorDegradedPayload
	out.PreviousStatus = ConnectorStatus(decodeString(source["previous_status"]))
	out.NewStatus = ConnectorStatus(decodeString(source["new_status"]))
	out.Trigger = ConnectorDegradedTrigger(decodeString(source["trigger"]))
	out.SilentForSecondsAtLeast = decodeInt(source["silent_for_seconds_at_least"])
	return out
}

// DecodeConnectorDisconnectedPayload builds a ConnectorDisconnectedPayload from a
// validated tree.
func DecodeConnectorDisconnectedPayload(value any) ConnectorDisconnectedPayload {
	source, _ := value.(map[string]any)
	var out ConnectorDisconnectedPayload
	out.PreviousStatus = ConnectorStatus(decodeString(source["previous_status"]))
	out.NewStatus = ConnectorStatus(decodeString(source["new_status"]))
	out.Trigger = ConnectorDisconnectedTrigger(decodeString(source["trigger"]))
	if field, present := source["silent_for_seconds_at_least"]; present {
		decoded := decodeInt(field)
		out.SilentForSecondsAtLeast = &decoded
	}
	return out
}

// DecodeConnectorRevokedPayload builds a ConnectorRevokedPayload from a validated
// tree.
func DecodeConnectorRevokedPayload(value any) ConnectorRevokedPayload {
	source, _ := value.(map[string]any)
	var out ConnectorRevokedPayload
	out.PreviousStatus = ConnectorStatus(decodeString(source["previous_status"]))
	out.NewStatus = ConnectorStatus(decodeString(source["new_status"]))
	out.RoutesRevoked = decodeInt(source["routes_revoked"])
	out.SessionsDisconnected = decodeInt(source["sessions_disconnected"])
	if field, present := source["channels_closed"]; present {
		decoded := decodeInt(field)
		out.ChannelsClosed = &decoded
	}
	return out
}

// DecodeWorkspaceObservedPayload builds a WorkspaceObservedPayload from a validated
// tree.
func DecodeWorkspaceObservedPayload(value any) WorkspaceObservedPayload {
	source, _ := value.(map[string]any)
	var out WorkspaceObservedPayload
	out.WorkspaceID = decodeString(source["workspace_id"])
	if field, present := source["environment_id"]; present {
		decoded := decodeString(field)
		out.EnvironmentID = &decoded
	}
	out.PathHash = decodeString(source["path_hash"])
	out.DisplayPath = decodeString(source["display_path"])
	if field, present := source["repository_identity"]; present {
		decoded := decodeString(field)
		out.RepositoryIdentity = &decoded
	}
	out.Branch = decodeString(source["branch"])
	out.HeadCommit = decodeString(source["head_commit"])
	out.Dirty = decodeBool(source["dirty"])
	out.Source = WorkspaceObservationSource(decodeString(source["source"]))
	return out
}

// DecodeWorkspaceHeadChangedPayload builds a WorkspaceHeadChangedPayload from a
// validated tree.
func DecodeWorkspaceHeadChangedPayload(value any) WorkspaceHeadChangedPayload {
	source, _ := value.(map[string]any)
	var out WorkspaceHeadChangedPayload
	out.WorkspaceID = decodeString(source["workspace_id"])
	if field, present := source["environment_id"]; present {
		decoded := decodeString(field)
		out.EnvironmentID = &decoded
	}
	out.PreviousBranch = decodeString(source["previous_branch"])
	out.PreviousHeadCommit = decodeString(source["previous_head_commit"])
	out.PreviousDirty = decodeBool(source["previous_dirty"])
	out.Branch = decodeString(source["branch"])
	out.HeadCommit = decodeString(source["head_commit"])
	out.Dirty = decodeBool(source["dirty"])
	return out
}

// DecodeJobEnqueuedPayload builds a JobEnqueuedPayload from a validated tree.
func DecodeJobEnqueuedPayload(value any) JobEnqueuedPayload {
	source, _ := value.(map[string]any)
	var out JobEnqueuedPayload
	out.JobID = decodeString(source["job_id"])
	out.Kind = JobKind(decodeString(source["kind"]))
	out.RunAfter = decodeString(source["run_after"])
	return out
}

// DecodeJobSucceededPayload builds a JobSucceededPayload from a validated tree.
func DecodeJobSucceededPayload(value any) JobSucceededPayload {
	source, _ := value.(map[string]any)
	var out JobSucceededPayload
	out.JobID = decodeString(source["job_id"])
	out.Kind = JobKind(decodeString(source["kind"]))
	out.Attempts = decodeInt(source["attempts"])
	out.DurationMs = decodeInt(source["duration_ms"])
	return out
}

// DecodeJobFailedPayload builds a JobFailedPayload from a validated tree.
func DecodeJobFailedPayload(value any) JobFailedPayload {
	source, _ := value.(map[string]any)
	var out JobFailedPayload
	out.JobID = decodeString(source["job_id"])
	out.Kind = JobKind(decodeString(source["kind"]))
	out.Attempts = decodeInt(source["attempts"])
	out.Reason = JobFailureReason(decodeString(source["reason"]))
	out.Retrying = decodeBool(source["retrying"])
	if field, present := source["next_attempt_at"]; present {
		decoded := decodeString(field)
		out.NextAttemptAt = &decoded
	}
	return out
}

// DecodeStreamSubscribe builds a StreamSubscribe from a validated tree.
func DecodeStreamSubscribe(value any) StreamSubscribe {
	source, _ := value.(map[string]any)
	var out StreamSubscribe
	out.Type = StreamSubscribeType(decodeString(source["type"]))
	out.LastSequence = decodeInt(source["last_sequence"])
	if field, present := source["max_replay"]; present {
		decoded := decodeInt(field)
		out.MaxReplay = &decoded
	}
	return out
}

// DecodeStreamSubscribed builds a StreamSubscribed from a validated tree.
func DecodeStreamSubscribed(value any) StreamSubscribed {
	source, _ := value.(map[string]any)
	var out StreamSubscribed
	out.Type = StreamSubscribedType(decodeString(source["type"]))
	out.ProjectID = decodeString(source["project_id"])
	out.CurrentSequence = decodeInt(source["current_sequence"])
	out.EarliestAvailableSequence = decodeInt(source["earliest_available_sequence"])
	out.Replaying = decodeBool(source["replaying"])
	return out
}

// DecodeStreamRefreshRequired builds a StreamRefreshRequired from a validated tree.
func DecodeStreamRefreshRequired(value any) StreamRefreshRequired {
	source, _ := value.(map[string]any)
	var out StreamRefreshRequired
	out.Type = StreamRefreshRequiredType(decodeString(source["type"]))
	out.Reason = StreamRefreshRequiredReason(decodeString(source["reason"]))
	out.CurrentSequence = decodeInt(source["current_sequence"])
	out.EarliestAvailableSequence = decodeInt(source["earliest_available_sequence"])
	return out
}

// DecodeStreamHeartbeat builds a StreamHeartbeat from a validated tree.
func DecodeStreamHeartbeat(value any) StreamHeartbeat {
	source, _ := value.(map[string]any)
	var out StreamHeartbeat
	out.Type = StreamHeartbeatType(decodeString(source["type"]))
	out.CurrentSequence = decodeInt(source["current_sequence"])
	out.SentAt = decodeString(source["sent_at"])
	return out
}

// DecodeStreamError builds a StreamError from a validated tree.
func DecodeStreamError(value any) StreamError {
	source, _ := value.(map[string]any)
	var out StreamError
	out.Type = StreamErrorType(decodeString(source["type"]))
	out.Code = ErrorClass(decodeString(source["code"]))
	out.Message = decodeString(source["message"])
	out.Retryable = decodeBool(source["retryable"])
	return out
}

// DecodeApiErrorDetails builds a ApiErrorDetails from a validated tree.
func DecodeApiErrorDetails(value any) ApiErrorDetails {
	source, _ := value.(map[string]any)
	var out ApiErrorDetails
	if field, present := source["current_version"]; present {
		decoded := decodeInt(field)
		out.CurrentVersion = &decoded
	}
	if field, present := source["expected_version"]; present {
		decoded := decodeInt(field)
		out.ExpectedVersion = &decoded
	}
	if field, present := source["current_epoch"]; present {
		decoded := decodeInt(field)
		out.CurrentEpoch = &decoded
	}
	if field, present := source["candidates"]; present {
		out.Candidates = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	if field, present := source["allowed_transitions"]; present {
		out.AllowedTransitions = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	if field, present := source["required_evidence"]; present {
		out.RequiredEvidence = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	if field, present := source["missing_context"]; present {
		out.MissingContext = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	if field, present := source["retry_after_ms"]; present {
		decoded := decodeInt(field)
		out.RetryAfterMs = &decoded
	}
	if field, present := source["field"]; present {
		decoded := decodeString(field)
		out.Field = &decoded
	}
	if field, present := source["reason"]; present {
		decoded := decodeString(field)
		out.Reason = &decoded
	}
	return out
}

// DecodeApiError builds a ApiError from a validated tree.
func DecodeApiError(value any) ApiError {
	source, _ := value.(map[string]any)
	var out ApiError
	out.Code = ErrorClass(decodeString(source["code"]))
	out.Message = decodeString(source["message"])
	if field, present := source["details"]; present {
		decoded := DecodeApiErrorDetails(field)
		out.Details = &decoded
	}
	return out
}

// DecodeApiMeta builds a ApiMeta from a validated tree.
func DecodeApiMeta(value any) ApiMeta {
	source, _ := value.(map[string]any)
	var out ApiMeta
	out.RequestID = decodeString(source["request_id"])
	if field, present := source["next_cursor"]; present {
		decoded := decodeString(field)
		out.NextCursor = &decoded
	}
	return out
}

// DecodeApiErrorResponse builds a ApiErrorResponse from a validated tree.
func DecodeApiErrorResponse(value any) ApiErrorResponse {
	source, _ := value.(map[string]any)
	var out ApiErrorResponse
	out.Error = DecodeApiError(source["error"])
	out.Meta = DecodeApiMeta(source["meta"])
	return out
}

// DecodeCursorClaims builds a CursorClaims from a validated tree.
func DecodeCursorClaims(value any) CursorClaims {
	source, _ := value.(map[string]any)
	var out CursorClaims
	out.Version = decodeInt(source["version"])
	out.SortKey = decodeString(source["sort_key"])
	out.ID = decodeString(source["id"])
	return out
}
