// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

// Type-directed dispatch generated from x-protocol.messages. Adding a message type to
// the schema is the only way to add one here.

// validatePayload checks a payload against the schema selected by message type.
func validatePayload(messageType MessageType, value any, path string, out *[]SchemaViolation) {
	switch messageType {
	case MessageTypeOrganisationCreated:
		validateOrganisationCreatedPayload(value, path, out)
	case MessageTypeProjectCreated:
		validateProjectCreatedPayload(value, path, out)
	case MessageTypeProjectUpdated:
		validateProjectUpdatedPayload(value, path, out)
	case MessageTypeProjectRepositoryChanged:
		validateProjectRepositoryChangedPayload(value, path, out)
	case MessageTypeProjectArchived:
		validateProjectArchivedPayload(value, path, out)
	case MessageTypeUserInvited:
		validateUserInvitedPayload(value, path, out)
	case MessageTypeUserCredentialsSet:
		validateUserCredentialsSetPayload(value, path, out)
	case MessageTypeAuthenticationLoginSucceeded:
		validateAuthenticationLoginSucceededPayload(value, path, out)
	case MessageTypeAuthenticationLoginFailed:
		validateAuthenticationLoginFailedPayload(value, path, out)
	case MessageTypeSessionRevoked:
		validateSessionRevokedPayload(value, path, out)
	case MessageTypeConnectorEnrolled:
		validateConnectorEnrolledPayload(value, path, out)
	case MessageTypeConnectorConnected:
		validateConnectorConnectedPayload(value, path, out)
	case MessageTypeConnectorDegraded:
		validateConnectorDegradedPayload(value, path, out)
	case MessageTypeConnectorDisconnected:
		validateConnectorDisconnectedPayload(value, path, out)
	case MessageTypeConnectorRevoked:
		validateConnectorRevokedPayload(value, path, out)
	case MessageTypeWorkspaceObserved:
		validateWorkspaceObservedPayload(value, path, out)
	case MessageTypeWorkspaceHeadChanged:
		validateWorkspaceHeadChangedPayload(value, path, out)
	case MessageTypeJobEnqueued:
		validateJobEnqueuedPayload(value, path, out)
	case MessageTypeJobSucceeded:
		validateJobSucceededPayload(value, path, out)
	case MessageTypeJobFailed:
		validateJobFailedPayload(value, path, out)
	}
}

// decodePayload builds the typed payload for a validated frame.
func decodePayload(messageType MessageType, value any) Payload {
	switch messageType {
	case MessageTypeOrganisationCreated:
		return DecodeOrganisationCreatedPayload(value)
	case MessageTypeProjectCreated:
		return DecodeProjectCreatedPayload(value)
	case MessageTypeProjectUpdated:
		return DecodeProjectUpdatedPayload(value)
	case MessageTypeProjectRepositoryChanged:
		return DecodeProjectRepositoryChangedPayload(value)
	case MessageTypeProjectArchived:
		return DecodeProjectArchivedPayload(value)
	case MessageTypeUserInvited:
		return DecodeUserInvitedPayload(value)
	case MessageTypeUserCredentialsSet:
		return DecodeUserCredentialsSetPayload(value)
	case MessageTypeAuthenticationLoginSucceeded:
		return DecodeAuthenticationLoginSucceededPayload(value)
	case MessageTypeAuthenticationLoginFailed:
		return DecodeAuthenticationLoginFailedPayload(value)
	case MessageTypeSessionRevoked:
		return DecodeSessionRevokedPayload(value)
	case MessageTypeConnectorEnrolled:
		return DecodeConnectorEnrolledPayload(value)
	case MessageTypeConnectorConnected:
		return DecodeConnectorConnectedPayload(value)
	case MessageTypeConnectorDegraded:
		return DecodeConnectorDegradedPayload(value)
	case MessageTypeConnectorDisconnected:
		return DecodeConnectorDisconnectedPayload(value)
	case MessageTypeConnectorRevoked:
		return DecodeConnectorRevokedPayload(value)
	case MessageTypeWorkspaceObserved:
		return DecodeWorkspaceObservedPayload(value)
	case MessageTypeWorkspaceHeadChanged:
		return DecodeWorkspaceHeadChangedPayload(value)
	case MessageTypeJobEnqueued:
		return DecodeJobEnqueuedPayload(value)
	case MessageTypeJobSucceeded:
		return DecodeJobSucceededPayload(value)
	case MessageTypeJobFailed:
		return DecodeJobFailedPayload(value)
	}
	return nil
}

// EncodePayload returns the canonical encoding of any version 1 payload.
func EncodePayload(payload Payload) ([]byte, error) {
	switch value := payload.(type) {
	case OrganisationCreatedPayload:
		return EncodeOrganisationCreatedPayload(value)
	case ProjectCreatedPayload:
		return EncodeProjectCreatedPayload(value)
	case ProjectUpdatedPayload:
		return EncodeProjectUpdatedPayload(value)
	case ProjectRepositoryChangedPayload:
		return EncodeProjectRepositoryChangedPayload(value)
	case ProjectArchivedPayload:
		return EncodeProjectArchivedPayload(value)
	case UserInvitedPayload:
		return EncodeUserInvitedPayload(value)
	case UserCredentialsSetPayload:
		return EncodeUserCredentialsSetPayload(value)
	case AuthenticationLoginSucceededPayload:
		return EncodeAuthenticationLoginSucceededPayload(value)
	case AuthenticationLoginFailedPayload:
		return EncodeAuthenticationLoginFailedPayload(value)
	case SessionRevokedPayload:
		return EncodeSessionRevokedPayload(value)
	case ConnectorEnrolledPayload:
		return EncodeConnectorEnrolledPayload(value)
	case ConnectorConnectedPayload:
		return EncodeConnectorConnectedPayload(value)
	case ConnectorDegradedPayload:
		return EncodeConnectorDegradedPayload(value)
	case ConnectorDisconnectedPayload:
		return EncodeConnectorDisconnectedPayload(value)
	case ConnectorRevokedPayload:
		return EncodeConnectorRevokedPayload(value)
	case WorkspaceObservedPayload:
		return EncodeWorkspaceObservedPayload(value)
	case WorkspaceHeadChangedPayload:
		return EncodeWorkspaceHeadChangedPayload(value)
	case JobEnqueuedPayload:
		return EncodeJobEnqueuedPayload(value)
	case JobSucceededPayload:
		return EncodeJobSucceededPayload(value)
	case JobFailedPayload:
		return EncodeJobFailedPayload(value)
	}
	return nil, errUnknownPayload
}

// IsKnownMessageType reports whether a value names a version 1 message type.
func IsKnownMessageType(value string) bool {
	switch MessageType(value) {
	case MessageTypeOrganisationCreated, MessageTypeProjectCreated, MessageTypeProjectUpdated, MessageTypeProjectRepositoryChanged, MessageTypeProjectArchived, MessageTypeUserInvited, MessageTypeUserCredentialsSet, MessageTypeAuthenticationLoginSucceeded, MessageTypeAuthenticationLoginFailed, MessageTypeSessionRevoked, MessageTypeConnectorEnrolled, MessageTypeConnectorConnected, MessageTypeConnectorDegraded, MessageTypeConnectorDisconnected, MessageTypeConnectorRevoked, MessageTypeWorkspaceObserved, MessageTypeWorkspaceHeadChanged, MessageTypeJobEnqueued, MessageTypeJobSucceeded, MessageTypeJobFailed:
		return true
	}
	return false
}
