// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

// Canonical encoders. Output is deterministic: properties appear in schema order,
// absent optional properties are omitted, and numbers and strings are formatted
// identically to the TypeScript encoder so that both languages produce byte-identical
// frames.

// encodeRepositoryIdentityInto writes the canonical encoding of a RepositoryIdentity.
func encodeRepositoryIdentityInto(w *canonicalWriter, value RepositoryIdentity) {
	w.beginObject()
	w.key("canonical")
	w.string(value.Canonical)
	if value.CloneURLs != nil {
		w.key("clone_urls")
		w.beginArray()
		for _, item := range value.CloneURLs {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	w.endObject()
}

// EncodeRepositoryIdentity returns the canonical encoding of a RepositoryIdentity.
func EncodeRepositoryIdentity(value RepositoryIdentity) ([]byte, error) {
	var w canonicalWriter
	encodeRepositoryIdentityInto(&w, value)
	return w.result()
}

// encodeValidationViewportInto writes the canonical encoding of a ValidationViewport.
func encodeValidationViewportInto(w *canonicalWriter, value ValidationViewport) {
	w.beginObject()
	w.key("width")
	w.integer(value.Width)
	w.key("height")
	w.integer(value.Height)
	if value.DeviceScaleFactor != nil {
		w.key("device_scale_factor")
		w.number((*value.DeviceScaleFactor))
	}
	w.endObject()
}

// EncodeValidationViewport returns the canonical encoding of a ValidationViewport.
func EncodeValidationViewport(value ValidationViewport) ([]byte, error) {
	var w canonicalWriter
	encodeValidationViewportInto(&w, value)
	return w.result()
}

// encodeProjectSettingsInto writes the canonical encoding of a ProjectSettings.
func encodeProjectSettingsInto(w *canonicalWriter, value ProjectSettings) {
	w.beginObject()
	w.key("default_validation_viewports")
	w.beginArray()
	for _, item := range value.DefaultValidationViewports {
		w.item()
		encodeValidationViewportInto(w, item)
	}
	w.endArray()
	w.endObject()
}

// EncodeProjectSettings returns the canonical encoding of a ProjectSettings.
func EncodeProjectSettings(value ProjectSettings) ([]byte, error) {
	var w canonicalWriter
	encodeProjectSettingsInto(&w, value)
	return w.result()
}

// encodeOrganisationInto writes the canonical encoding of a Organisation.
func encodeOrganisationInto(w *canonicalWriter, value Organisation) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("name")
	w.string(value.Name)
	w.key("slug")
	w.string(value.Slug)
	w.key("status")
	w.string(string(value.Status))
	w.key("created_at")
	w.string(value.CreatedAt)
	w.key("updated_at")
	w.string(value.UpdatedAt)
	w.endObject()
}

// EncodeOrganisation returns the canonical encoding of a Organisation.
func EncodeOrganisation(value Organisation) ([]byte, error) {
	var w canonicalWriter
	encodeOrganisationInto(&w, value)
	return w.result()
}

// encodeUserInto writes the canonical encoding of a User.
func encodeUserInto(w *canonicalWriter, value User) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	w.key("email")
	w.string(value.Email)
	w.key("display_name")
	w.string(value.DisplayName)
	w.key("status")
	w.string(string(value.Status))
	if value.LocalCredentialSet != nil {
		w.key("local_credential_set")
		w.boolean((*value.LocalCredentialSet))
	}
	w.key("created_at")
	w.string(value.CreatedAt)
	w.key("updated_at")
	w.string(value.UpdatedAt)
	w.endObject()
}

// EncodeUser returns the canonical encoding of a User.
func EncodeUser(value User) ([]byte, error) {
	var w canonicalWriter
	encodeUserInto(&w, value)
	return w.result()
}

// encodeProjectInto writes the canonical encoding of a Project.
func encodeProjectInto(w *canonicalWriter, value Project) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	w.key("name")
	w.string(value.Name)
	w.key("slug")
	w.string(value.Slug)
	if value.RepositoryIdentity != nil {
		w.key("repository_identity")
		encodeRepositoryIdentityInto(w, (*value.RepositoryIdentity))
	}
	w.key("default_branch")
	w.string(value.DefaultBranch)
	w.key("status")
	w.string(string(value.Status))
	w.key("settings")
	encodeProjectSettingsInto(w, value.Settings)
	w.key("version")
	w.integer(value.Version)
	w.key("created_at")
	w.string(value.CreatedAt)
	w.key("updated_at")
	w.string(value.UpdatedAt)
	w.endObject()
}

// EncodeProject returns the canonical encoding of a Project.
func EncodeProject(value Project) ([]byte, error) {
	var w canonicalWriter
	encodeProjectInto(&w, value)
	return w.result()
}

// encodeHumanSessionInto writes the canonical encoding of a HumanSession.
func encodeHumanSessionInto(w *canonicalWriter, value HumanSession) {
	w.beginObject()
	w.key("session_id")
	w.string(value.SessionID)
	if value.UserID != nil {
		w.key("user_id")
		w.string((*value.UserID))
	}
	if value.OrganisationID != nil {
		w.key("organisation_id")
		w.string((*value.OrganisationID))
	}
	if value.Email != nil {
		w.key("email")
		w.string((*value.Email))
	}
	w.key("display")
	w.string(value.Display)
	if value.ProjectIDs != nil {
		w.key("project_ids")
		w.beginArray()
		for _, item := range value.ProjectIDs {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	w.key("expires_at")
	w.string(value.ExpiresAt)
	w.endObject()
}

// EncodeHumanSession returns the canonical encoding of a HumanSession.
func EncodeHumanSession(value HumanSession) ([]byte, error) {
	var w canonicalWriter
	encodeHumanSessionInto(&w, value)
	return w.result()
}

// encodeEnvironmentInto writes the canonical encoding of a Environment.
func encodeEnvironmentInto(w *canonicalWriter, value Environment) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	if value.ProjectID != nil {
		w.key("project_id")
		w.string((*value.ProjectID))
	}
	w.key("name")
	w.string(value.Name)
	w.key("platform")
	w.string(value.Platform)
	w.key("architecture")
	w.string(value.Architecture)
	w.key("labels")
	w.beginArray()
	for _, item := range value.Labels {
		w.item()
		w.string(item)
	}
	w.endArray()
	w.key("trust_level")
	w.string(string(value.TrustLevel))
	w.key("status")
	w.string(string(value.Status))
	if value.LastSeenAt != nil {
		w.key("last_seen_at")
		w.string((*value.LastSeenAt))
	}
	w.key("created_at")
	w.string(value.CreatedAt)
	w.endObject()
}

// EncodeEnvironment returns the canonical encoding of a Environment.
func EncodeEnvironment(value Environment) ([]byte, error) {
	var w canonicalWriter
	encodeEnvironmentInto(&w, value)
	return w.result()
}

// encodeConnectorInto writes the canonical encoding of a Connector.
func encodeConnectorInto(w *canonicalWriter, value Connector) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	w.key("environment_id")
	w.string(value.EnvironmentID)
	if value.ProjectID != nil {
		w.key("project_id")
		w.string((*value.ProjectID))
	}
	w.key("certificate_fingerprint")
	w.string(value.CertificateFingerprint)
	w.key("certificate_not_after")
	w.string(value.CertificateNotAfter)
	w.key("version")
	w.string(value.Version)
	w.key("capabilities")
	w.beginArray()
	for _, item := range value.Capabilities {
		w.item()
		w.string(item)
	}
	w.endArray()
	w.key("status")
	w.string(string(value.Status))
	if value.ConnectedAt != nil {
		w.key("connected_at")
		w.string((*value.ConnectedAt))
	}
	if value.LastHeartbeatAt != nil {
		w.key("last_heartbeat_at")
		w.string((*value.LastHeartbeatAt))
	}
	if value.RevokedAt != nil {
		w.key("revoked_at")
		w.string((*value.RevokedAt))
	}
	w.key("created_at")
	w.string(value.CreatedAt)
	w.endObject()
}

// EncodeConnector returns the canonical encoding of a Connector.
func EncodeConnector(value Connector) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorInto(&w, value)
	return w.result()
}

// encodeWorkspaceInto writes the canonical encoding of a Workspace.
func encodeWorkspaceInto(w *canonicalWriter, value Workspace) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	w.key("project_id")
	w.string(value.ProjectID)
	if value.EnvironmentID != nil {
		w.key("environment_id")
		w.string((*value.EnvironmentID))
	}
	if value.ConnectorID != nil {
		w.key("connector_id")
		w.string((*value.ConnectorID))
	}
	w.key("path_hash")
	w.string(value.PathHash)
	w.key("display_path")
	w.string(value.DisplayPath)
	if value.RepositoryIdentity != nil {
		w.key("repository_identity")
		w.string((*value.RepositoryIdentity))
	}
	w.key("branch")
	w.string(value.Branch)
	w.key("head_commit")
	w.string(value.HeadCommit)
	w.key("dirty")
	w.boolean(value.Dirty)
	w.key("source")
	w.string(string(value.Source))
	if value.LastObservedAt != nil {
		w.key("last_observed_at")
		w.string((*value.LastObservedAt))
	}
	w.key("created_at")
	w.string(value.CreatedAt)
	w.endObject()
}

// EncodeWorkspace returns the canonical encoding of a Workspace.
func EncodeWorkspace(value Workspace) ([]byte, error) {
	var w canonicalWriter
	encodeWorkspaceInto(&w, value)
	return w.result()
}

// encodeActorInto writes the canonical encoding of a Actor.
func encodeActorInto(w *canonicalWriter, value Actor) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	if value.ID != nil {
		w.key("id")
		w.string((*value.ID))
	}
	if value.Display != nil {
		w.key("display")
		w.string((*value.Display))
	}
	w.endObject()
}

// EncodeActor returns the canonical encoding of a Actor.
func EncodeActor(value Actor) ([]byte, error) {
	var w canonicalWriter
	encodeActorInto(&w, value)
	return w.result()
}

// encodeCorrelationInto writes the canonical encoding of a Correlation.
func encodeCorrelationInto(w *canonicalWriter, value Correlation) {
	w.beginObject()
	if value.RequestID != nil {
		w.key("request_id")
		w.string((*value.RequestID))
	}
	if value.CausationEventID != nil {
		w.key("causation_event_id")
		w.string((*value.CausationEventID))
	}
	if value.ConnectorID != nil {
		w.key("connector_id")
		w.string((*value.ConnectorID))
	}
	if value.EnvironmentID != nil {
		w.key("environment_id")
		w.string((*value.EnvironmentID))
	}
	if value.WorkspaceID != nil {
		w.key("workspace_id")
		w.string((*value.WorkspaceID))
	}
	if value.PublishedServiceID != nil {
		w.key("published_service_id")
		w.string((*value.PublishedServiceID))
	}
	if value.AgentSessionID != nil {
		w.key("agent_session_id")
		w.string((*value.AgentSessionID))
	}
	if value.BrowserSessionID != nil {
		w.key("browser_session_id")
		w.string((*value.BrowserSessionID))
	}
	if value.WorkerID != nil {
		w.key("worker_id")
		w.string((*value.WorkerID))
	}
	if value.ArtefactID != nil {
		w.key("artefact_id")
		w.string((*value.ArtefactID))
	}
	if value.ReviewID != nil {
		w.key("review_id")
		w.string((*value.ReviewID))
	}
	if value.FindingID != nil {
		w.key("finding_id")
		w.string((*value.FindingID))
	}
	if value.AnnotationID != nil {
		w.key("annotation_id")
		w.string((*value.AnnotationID))
	}
	if value.JobID != nil {
		w.key("job_id")
		w.string((*value.JobID))
	}
	w.endObject()
}

// EncodeCorrelation returns the canonical encoding of a Correlation.
func EncodeCorrelation(value Correlation) ([]byte, error) {
	var w canonicalWriter
	encodeCorrelationInto(&w, value)
	return w.result()
}

// encodeEnvelopeInto writes the canonical encoding of a Envelope.
func encodeEnvelopeInto(w *canonicalWriter, value Envelope, PayloadJSON []byte) {
	w.beginObject()
	w.key("id")
	w.string(value.ID)
	w.key("schema_version")
	w.integer(value.SchemaVersion)
	w.key("sequence")
	w.integer(value.Sequence)
	w.key("type")
	w.string(string(value.Type))
	w.key("occurred_at")
	w.string(value.OccurredAt)
	w.key("recorded_at")
	w.string(value.RecordedAt)
	w.key("organisation_id")
	w.string(value.OrganisationID)
	if value.ProjectID != nil {
		w.key("project_id")
		w.string((*value.ProjectID))
	}
	w.key("actor")
	encodeActorInto(w, value.Actor)
	if value.Correlation != nil {
		w.key("correlation")
		encodeCorrelationInto(w, (*value.Correlation))
	}
	w.key("payload")
	w.raw(PayloadJSON)
	w.endObject()
}

// EncodeEnvelope returns the canonical encoding of a Envelope.
func EncodeEnvelope(value Envelope, PayloadJSON []byte) ([]byte, error) {
	var w canonicalWriter
	encodeEnvelopeInto(&w, value, PayloadJSON)
	return w.result()
}

// encodeOrganisationCreatedPayloadInto writes the canonical encoding of a
// OrganisationCreatedPayload.
func encodeOrganisationCreatedPayloadInto(w *canonicalWriter, value OrganisationCreatedPayload) {
	w.beginObject()
	w.key("slug")
	w.string(value.Slug)
	w.key("name")
	w.string(value.Name)
	w.endObject()
}

// EncodeOrganisationCreatedPayload returns the canonical encoding of a
// OrganisationCreatedPayload.
func EncodeOrganisationCreatedPayload(value OrganisationCreatedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeOrganisationCreatedPayloadInto(&w, value)
	return w.result()
}

// encodeProjectCreatedPayloadInto writes the canonical encoding of a
// ProjectCreatedPayload.
func encodeProjectCreatedPayloadInto(w *canonicalWriter, value ProjectCreatedPayload) {
	w.beginObject()
	w.key("slug")
	w.string(value.Slug)
	w.key("name")
	w.string(value.Name)
	if value.DefaultBranch != nil {
		w.key("default_branch")
		w.string((*value.DefaultBranch))
	}
	if value.RepositoryCanonical != nil {
		w.key("repository_canonical")
		w.string((*value.RepositoryCanonical))
	}
	w.endObject()
}

// EncodeProjectCreatedPayload returns the canonical encoding of a
// ProjectCreatedPayload.
func EncodeProjectCreatedPayload(value ProjectCreatedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeProjectCreatedPayloadInto(&w, value)
	return w.result()
}

// encodeProjectRepositoryChangedPayloadInto writes the canonical encoding of a
// ProjectRepositoryChangedPayload.
func encodeProjectRepositoryChangedPayloadInto(w *canonicalWriter, value ProjectRepositoryChangedPayload) {
	w.beginObject()
	if value.PreviousCanonical != nil {
		w.key("previous_canonical")
		w.string((*value.PreviousCanonical))
	}
	w.key("new_canonical")
	w.string(value.NewCanonical)
	w.endObject()
}

// EncodeProjectRepositoryChangedPayload returns the canonical encoding of a
// ProjectRepositoryChangedPayload.
func EncodeProjectRepositoryChangedPayload(value ProjectRepositoryChangedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeProjectRepositoryChangedPayloadInto(&w, value)
	return w.result()
}

// encodeUserInvitedPayloadInto writes the canonical encoding of a UserInvitedPayload.
func encodeUserInvitedPayloadInto(w *canonicalWriter, value UserInvitedPayload) {
	w.beginObject()
	w.key("user_id")
	w.string(value.UserID)
	w.key("method")
	w.string(string(value.Method))
	w.key("expires_at")
	w.string(value.ExpiresAt)
	w.endObject()
}

// EncodeUserInvitedPayload returns the canonical encoding of a UserInvitedPayload.
func EncodeUserInvitedPayload(value UserInvitedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeUserInvitedPayloadInto(&w, value)
	return w.result()
}

// encodeUserCredentialsSetPayloadInto writes the canonical encoding of a
// UserCredentialsSetPayload.
func encodeUserCredentialsSetPayloadInto(w *canonicalWriter, value UserCredentialsSetPayload) {
	w.beginObject()
	w.key("user_id")
	w.string(value.UserID)
	w.key("method")
	w.string(string(value.Method))
	w.endObject()
}

// EncodeUserCredentialsSetPayload returns the canonical encoding of a
// UserCredentialsSetPayload.
func EncodeUserCredentialsSetPayload(value UserCredentialsSetPayload) ([]byte, error) {
	var w canonicalWriter
	encodeUserCredentialsSetPayloadInto(&w, value)
	return w.result()
}

// encodeAuthenticationLoginSucceededPayloadInto writes the canonical encoding of a
// AuthenticationLoginSucceededPayload.
func encodeAuthenticationLoginSucceededPayloadInto(w *canonicalWriter, value AuthenticationLoginSucceededPayload) {
	w.beginObject()
	w.key("session_id")
	w.string(value.SessionID)
	if value.UserID != nil {
		w.key("user_id")
		w.string((*value.UserID))
	}
	w.key("method")
	w.string(string(value.Method))
	w.endObject()
}

// EncodeAuthenticationLoginSucceededPayload returns the canonical encoding of a
// AuthenticationLoginSucceededPayload.
func EncodeAuthenticationLoginSucceededPayload(value AuthenticationLoginSucceededPayload) ([]byte, error) {
	var w canonicalWriter
	encodeAuthenticationLoginSucceededPayloadInto(&w, value)
	return w.result()
}

// encodeAuthenticationLoginFailedPayloadInto writes the canonical encoding of a
// AuthenticationLoginFailedPayload.
func encodeAuthenticationLoginFailedPayloadInto(w *canonicalWriter, value AuthenticationLoginFailedPayload) {
	w.beginObject()
	w.key("reason")
	w.string(string(value.Reason))
	w.key("method")
	w.string(string(value.Method))
	if value.UserID != nil {
		w.key("user_id")
		w.string((*value.UserID))
	}
	w.endObject()
}

// EncodeAuthenticationLoginFailedPayload returns the canonical encoding of a
// AuthenticationLoginFailedPayload.
func EncodeAuthenticationLoginFailedPayload(value AuthenticationLoginFailedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeAuthenticationLoginFailedPayloadInto(&w, value)
	return w.result()
}

// encodeSessionRevokedPayloadInto writes the canonical encoding of a
// SessionRevokedPayload.
func encodeSessionRevokedPayloadInto(w *canonicalWriter, value SessionRevokedPayload) {
	w.beginObject()
	w.key("session_id")
	w.string(value.SessionID)
	if value.UserID != nil {
		w.key("user_id")
		w.string((*value.UserID))
	}
	w.key("reason")
	w.string(string(value.Reason))
	w.endObject()
}

// EncodeSessionRevokedPayload returns the canonical encoding of a
// SessionRevokedPayload.
func EncodeSessionRevokedPayload(value SessionRevokedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeSessionRevokedPayloadInto(&w, value)
	return w.result()
}

// encodeProjectUpdatedPayloadInto writes the canonical encoding of a
// ProjectUpdatedPayload.
func encodeProjectUpdatedPayloadInto(w *canonicalWriter, value ProjectUpdatedPayload) {
	w.beginObject()
	w.key("changed_fields")
	w.beginArray()
	for _, item := range value.ChangedFields {
		w.item()
		w.string(item)
	}
	w.endArray()
	w.endObject()
}

// EncodeProjectUpdatedPayload returns the canonical encoding of a
// ProjectUpdatedPayload.
func EncodeProjectUpdatedPayload(value ProjectUpdatedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeProjectUpdatedPayloadInto(&w, value)
	return w.result()
}

// encodeProjectArchivedPayloadInto writes the canonical encoding of a
// ProjectArchivedPayload.
func encodeProjectArchivedPayloadInto(w *canonicalWriter, value ProjectArchivedPayload) {
	w.beginObject()
	w.key("previous_status")
	w.string(string(value.PreviousStatus))
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.endObject()
}

// EncodeProjectArchivedPayload returns the canonical encoding of a
// ProjectArchivedPayload.
func EncodeProjectArchivedPayload(value ProjectArchivedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeProjectArchivedPayloadInto(&w, value)
	return w.result()
}

// encodeConnectorEnrolledPayloadInto writes the canonical encoding of a
// ConnectorEnrolledPayload.
func encodeConnectorEnrolledPayloadInto(w *canonicalWriter, value ConnectorEnrolledPayload) {
	w.beginObject()
	w.key("environment_id")
	w.string(value.EnvironmentID)
	w.key("environment_name")
	w.string(value.EnvironmentName)
	w.key("platform")
	w.string(value.Platform)
	w.key("architecture")
	w.string(value.Architecture)
	w.key("connector_version")
	w.string(value.ConnectorVersion)
	w.key("capabilities")
	w.beginArray()
	for _, item := range value.Capabilities {
		w.item()
		w.string(item)
	}
	w.endArray()
	w.key("certificate_fingerprint")
	w.string(value.CertificateFingerprint)
	w.key("identity_expires_at")
	w.string(value.IdentityExpiresAt)
	if value.EnrolmentTokenID != nil {
		w.key("enrolment_token_id")
		w.string((*value.EnrolmentTokenID))
	}
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.endObject()
}

// EncodeConnectorEnrolledPayload returns the canonical encoding of a
// ConnectorEnrolledPayload.
func EncodeConnectorEnrolledPayload(value ConnectorEnrolledPayload) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorEnrolledPayloadInto(&w, value)
	return w.result()
}

// encodeConnectorConnectedPayloadInto writes the canonical encoding of a
// ConnectorConnectedPayload.
func encodeConnectorConnectedPayloadInto(w *canonicalWriter, value ConnectorConnectedPayload) {
	w.beginObject()
	w.key("previous_status")
	w.string(string(value.PreviousStatus))
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.key("trigger")
	w.string(string(value.Trigger))
	w.endObject()
}

// EncodeConnectorConnectedPayload returns the canonical encoding of a
// ConnectorConnectedPayload.
func EncodeConnectorConnectedPayload(value ConnectorConnectedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorConnectedPayloadInto(&w, value)
	return w.result()
}

// encodeConnectorDegradedPayloadInto writes the canonical encoding of a
// ConnectorDegradedPayload.
func encodeConnectorDegradedPayloadInto(w *canonicalWriter, value ConnectorDegradedPayload) {
	w.beginObject()
	w.key("previous_status")
	w.string(string(value.PreviousStatus))
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.key("trigger")
	w.string(string(value.Trigger))
	w.key("silent_for_seconds_at_least")
	w.integer(value.SilentForSecondsAtLeast)
	w.endObject()
}

// EncodeConnectorDegradedPayload returns the canonical encoding of a
// ConnectorDegradedPayload.
func EncodeConnectorDegradedPayload(value ConnectorDegradedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorDegradedPayloadInto(&w, value)
	return w.result()
}

// encodeConnectorDisconnectedPayloadInto writes the canonical encoding of a
// ConnectorDisconnectedPayload.
func encodeConnectorDisconnectedPayloadInto(w *canonicalWriter, value ConnectorDisconnectedPayload) {
	w.beginObject()
	w.key("previous_status")
	w.string(string(value.PreviousStatus))
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.key("trigger")
	w.string(string(value.Trigger))
	if value.SilentForSecondsAtLeast != nil {
		w.key("silent_for_seconds_at_least")
		w.integer((*value.SilentForSecondsAtLeast))
	}
	w.endObject()
}

// EncodeConnectorDisconnectedPayload returns the canonical encoding of a
// ConnectorDisconnectedPayload.
func EncodeConnectorDisconnectedPayload(value ConnectorDisconnectedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorDisconnectedPayloadInto(&w, value)
	return w.result()
}

// encodeConnectorRevokedPayloadInto writes the canonical encoding of a
// ConnectorRevokedPayload.
func encodeConnectorRevokedPayloadInto(w *canonicalWriter, value ConnectorRevokedPayload) {
	w.beginObject()
	w.key("previous_status")
	w.string(string(value.PreviousStatus))
	w.key("new_status")
	w.string(string(value.NewStatus))
	w.key("routes_revoked")
	w.integer(value.RoutesRevoked)
	w.key("sessions_disconnected")
	w.integer(value.SessionsDisconnected)
	if value.ChannelsClosed != nil {
		w.key("channels_closed")
		w.integer((*value.ChannelsClosed))
	}
	w.endObject()
}

// EncodeConnectorRevokedPayload returns the canonical encoding of a
// ConnectorRevokedPayload.
func EncodeConnectorRevokedPayload(value ConnectorRevokedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeConnectorRevokedPayloadInto(&w, value)
	return w.result()
}

// encodeWorkspaceObservedPayloadInto writes the canonical encoding of a
// WorkspaceObservedPayload.
func encodeWorkspaceObservedPayloadInto(w *canonicalWriter, value WorkspaceObservedPayload) {
	w.beginObject()
	w.key("workspace_id")
	w.string(value.WorkspaceID)
	if value.EnvironmentID != nil {
		w.key("environment_id")
		w.string((*value.EnvironmentID))
	}
	w.key("path_hash")
	w.string(value.PathHash)
	w.key("display_path")
	w.string(value.DisplayPath)
	if value.RepositoryIdentity != nil {
		w.key("repository_identity")
		w.string((*value.RepositoryIdentity))
	}
	w.key("branch")
	w.string(value.Branch)
	w.key("head_commit")
	w.string(value.HeadCommit)
	w.key("dirty")
	w.boolean(value.Dirty)
	w.key("source")
	w.string(string(value.Source))
	w.endObject()
}

// EncodeWorkspaceObservedPayload returns the canonical encoding of a
// WorkspaceObservedPayload.
func EncodeWorkspaceObservedPayload(value WorkspaceObservedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeWorkspaceObservedPayloadInto(&w, value)
	return w.result()
}

// encodeWorkspaceHeadChangedPayloadInto writes the canonical encoding of a
// WorkspaceHeadChangedPayload.
func encodeWorkspaceHeadChangedPayloadInto(w *canonicalWriter, value WorkspaceHeadChangedPayload) {
	w.beginObject()
	w.key("workspace_id")
	w.string(value.WorkspaceID)
	if value.EnvironmentID != nil {
		w.key("environment_id")
		w.string((*value.EnvironmentID))
	}
	w.key("previous_branch")
	w.string(value.PreviousBranch)
	w.key("previous_head_commit")
	w.string(value.PreviousHeadCommit)
	w.key("previous_dirty")
	w.boolean(value.PreviousDirty)
	w.key("branch")
	w.string(value.Branch)
	w.key("head_commit")
	w.string(value.HeadCommit)
	w.key("dirty")
	w.boolean(value.Dirty)
	w.endObject()
}

// EncodeWorkspaceHeadChangedPayload returns the canonical encoding of a
// WorkspaceHeadChangedPayload.
func EncodeWorkspaceHeadChangedPayload(value WorkspaceHeadChangedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeWorkspaceHeadChangedPayloadInto(&w, value)
	return w.result()
}

// encodeJobEnqueuedPayloadInto writes the canonical encoding of a JobEnqueuedPayload.
func encodeJobEnqueuedPayloadInto(w *canonicalWriter, value JobEnqueuedPayload) {
	w.beginObject()
	w.key("job_id")
	w.string(value.JobID)
	w.key("kind")
	w.string(string(value.Kind))
	w.key("run_after")
	w.string(value.RunAfter)
	w.endObject()
}

// EncodeJobEnqueuedPayload returns the canonical encoding of a JobEnqueuedPayload.
func EncodeJobEnqueuedPayload(value JobEnqueuedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeJobEnqueuedPayloadInto(&w, value)
	return w.result()
}

// encodeJobSucceededPayloadInto writes the canonical encoding of a
// JobSucceededPayload.
func encodeJobSucceededPayloadInto(w *canonicalWriter, value JobSucceededPayload) {
	w.beginObject()
	w.key("job_id")
	w.string(value.JobID)
	w.key("kind")
	w.string(string(value.Kind))
	w.key("attempts")
	w.integer(value.Attempts)
	w.key("duration_ms")
	w.integer(value.DurationMs)
	w.endObject()
}

// EncodeJobSucceededPayload returns the canonical encoding of a JobSucceededPayload.
func EncodeJobSucceededPayload(value JobSucceededPayload) ([]byte, error) {
	var w canonicalWriter
	encodeJobSucceededPayloadInto(&w, value)
	return w.result()
}

// encodeJobFailedPayloadInto writes the canonical encoding of a JobFailedPayload.
func encodeJobFailedPayloadInto(w *canonicalWriter, value JobFailedPayload) {
	w.beginObject()
	w.key("job_id")
	w.string(value.JobID)
	w.key("kind")
	w.string(string(value.Kind))
	w.key("attempts")
	w.integer(value.Attempts)
	w.key("reason")
	w.string(string(value.Reason))
	w.key("retrying")
	w.boolean(value.Retrying)
	if value.NextAttemptAt != nil {
		w.key("next_attempt_at")
		w.string((*value.NextAttemptAt))
	}
	w.endObject()
}

// EncodeJobFailedPayload returns the canonical encoding of a JobFailedPayload.
func EncodeJobFailedPayload(value JobFailedPayload) ([]byte, error) {
	var w canonicalWriter
	encodeJobFailedPayloadInto(&w, value)
	return w.result()
}

// encodeStreamSubscribeInto writes the canonical encoding of a StreamSubscribe.
func encodeStreamSubscribeInto(w *canonicalWriter, value StreamSubscribe) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	w.key("last_sequence")
	w.integer(value.LastSequence)
	if value.MaxReplay != nil {
		w.key("max_replay")
		w.integer((*value.MaxReplay))
	}
	w.endObject()
}

// EncodeStreamSubscribe returns the canonical encoding of a StreamSubscribe.
func EncodeStreamSubscribe(value StreamSubscribe) ([]byte, error) {
	var w canonicalWriter
	encodeStreamSubscribeInto(&w, value)
	return w.result()
}

// encodeStreamSubscribedInto writes the canonical encoding of a StreamSubscribed.
func encodeStreamSubscribedInto(w *canonicalWriter, value StreamSubscribed) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	w.key("project_id")
	w.string(value.ProjectID)
	w.key("current_sequence")
	w.integer(value.CurrentSequence)
	w.key("earliest_available_sequence")
	w.integer(value.EarliestAvailableSequence)
	w.key("replaying")
	w.boolean(value.Replaying)
	w.endObject()
}

// EncodeStreamSubscribed returns the canonical encoding of a StreamSubscribed.
func EncodeStreamSubscribed(value StreamSubscribed) ([]byte, error) {
	var w canonicalWriter
	encodeStreamSubscribedInto(&w, value)
	return w.result()
}

// encodeStreamRefreshRequiredInto writes the canonical encoding of a
// StreamRefreshRequired.
func encodeStreamRefreshRequiredInto(w *canonicalWriter, value StreamRefreshRequired) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	w.key("reason")
	w.string(string(value.Reason))
	w.key("current_sequence")
	w.integer(value.CurrentSequence)
	w.key("earliest_available_sequence")
	w.integer(value.EarliestAvailableSequence)
	w.endObject()
}

// EncodeStreamRefreshRequired returns the canonical encoding of a
// StreamRefreshRequired.
func EncodeStreamRefreshRequired(value StreamRefreshRequired) ([]byte, error) {
	var w canonicalWriter
	encodeStreamRefreshRequiredInto(&w, value)
	return w.result()
}

// encodeStreamHeartbeatInto writes the canonical encoding of a StreamHeartbeat.
func encodeStreamHeartbeatInto(w *canonicalWriter, value StreamHeartbeat) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	w.key("current_sequence")
	w.integer(value.CurrentSequence)
	w.key("sent_at")
	w.string(value.SentAt)
	w.endObject()
}

// EncodeStreamHeartbeat returns the canonical encoding of a StreamHeartbeat.
func EncodeStreamHeartbeat(value StreamHeartbeat) ([]byte, error) {
	var w canonicalWriter
	encodeStreamHeartbeatInto(&w, value)
	return w.result()
}

// encodeStreamErrorInto writes the canonical encoding of a StreamError.
func encodeStreamErrorInto(w *canonicalWriter, value StreamError) {
	w.beginObject()
	w.key("type")
	w.string(string(value.Type))
	w.key("code")
	w.string(string(value.Code))
	w.key("message")
	w.string(value.Message)
	w.key("retryable")
	w.boolean(value.Retryable)
	w.endObject()
}

// EncodeStreamError returns the canonical encoding of a StreamError.
func EncodeStreamError(value StreamError) ([]byte, error) {
	var w canonicalWriter
	encodeStreamErrorInto(&w, value)
	return w.result()
}

// encodeApiErrorDetailsInto writes the canonical encoding of a ApiErrorDetails.
func encodeApiErrorDetailsInto(w *canonicalWriter, value ApiErrorDetails) {
	w.beginObject()
	if value.CurrentVersion != nil {
		w.key("current_version")
		w.integer((*value.CurrentVersion))
	}
	if value.ExpectedVersion != nil {
		w.key("expected_version")
		w.integer((*value.ExpectedVersion))
	}
	if value.CurrentEpoch != nil {
		w.key("current_epoch")
		w.integer((*value.CurrentEpoch))
	}
	if value.Candidates != nil {
		w.key("candidates")
		w.beginArray()
		for _, item := range value.Candidates {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	if value.AllowedTransitions != nil {
		w.key("allowed_transitions")
		w.beginArray()
		for _, item := range value.AllowedTransitions {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	if value.RequiredEvidence != nil {
		w.key("required_evidence")
		w.beginArray()
		for _, item := range value.RequiredEvidence {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	if value.MissingContext != nil {
		w.key("missing_context")
		w.beginArray()
		for _, item := range value.MissingContext {
			w.item()
			w.string(item)
		}
		w.endArray()
	}
	if value.RetryAfterMs != nil {
		w.key("retry_after_ms")
		w.integer((*value.RetryAfterMs))
	}
	if value.Field != nil {
		w.key("field")
		w.string((*value.Field))
	}
	if value.Reason != nil {
		w.key("reason")
		w.string((*value.Reason))
	}
	w.endObject()
}

// EncodeApiErrorDetails returns the canonical encoding of a ApiErrorDetails.
func EncodeApiErrorDetails(value ApiErrorDetails) ([]byte, error) {
	var w canonicalWriter
	encodeApiErrorDetailsInto(&w, value)
	return w.result()
}

// encodeApiErrorInto writes the canonical encoding of a ApiError.
func encodeApiErrorInto(w *canonicalWriter, value ApiError) {
	w.beginObject()
	w.key("code")
	w.string(string(value.Code))
	w.key("message")
	w.string(value.Message)
	if value.Details != nil {
		w.key("details")
		encodeApiErrorDetailsInto(w, (*value.Details))
	}
	w.endObject()
}

// EncodeApiError returns the canonical encoding of a ApiError.
func EncodeApiError(value ApiError) ([]byte, error) {
	var w canonicalWriter
	encodeApiErrorInto(&w, value)
	return w.result()
}

// encodeApiMetaInto writes the canonical encoding of a ApiMeta.
func encodeApiMetaInto(w *canonicalWriter, value ApiMeta) {
	w.beginObject()
	w.key("request_id")
	w.string(value.RequestID)
	if value.NextCursor != nil {
		w.key("next_cursor")
		w.string((*value.NextCursor))
	}
	w.endObject()
}

// EncodeApiMeta returns the canonical encoding of a ApiMeta.
func EncodeApiMeta(value ApiMeta) ([]byte, error) {
	var w canonicalWriter
	encodeApiMetaInto(&w, value)
	return w.result()
}

// encodeApiErrorResponseInto writes the canonical encoding of a ApiErrorResponse.
func encodeApiErrorResponseInto(w *canonicalWriter, value ApiErrorResponse) {
	w.beginObject()
	w.key("error")
	encodeApiErrorInto(w, value.Error)
	w.key("meta")
	encodeApiMetaInto(w, value.Meta)
	w.endObject()
}

// EncodeApiErrorResponse returns the canonical encoding of a ApiErrorResponse.
func EncodeApiErrorResponse(value ApiErrorResponse) ([]byte, error) {
	var w canonicalWriter
	encodeApiErrorResponseInto(&w, value)
	return w.result()
}

// encodeCursorClaimsInto writes the canonical encoding of a CursorClaims.
func encodeCursorClaimsInto(w *canonicalWriter, value CursorClaims) {
	w.beginObject()
	w.key("version")
	w.integer(value.Version)
	w.key("sort_key")
	w.string(value.SortKey)
	w.key("id")
	w.string(value.ID)
	w.endObject()
}

// EncodeCursorClaims returns the canonical encoding of a CursorClaims.
func EncodeCursorClaims(value CursorClaims) ([]byte, error) {
	var w canonicalWriter
	encodeCursorClaimsInto(&w, value)
	return w.result()
}
