// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

// ProtocolName is the protocol described by ReviewPlane platform foundation, version
// 1.
const ProtocolName = "platform"

// ProtocolVersion is the only version this build accepts. An envelope carrying any
// other value is rejected with ErrorClassProtocolUnsupported and is never best-effort
// parsed.
const ProtocolVersion int64 = 1

// Byte bounds enforced on raw frames before deserialisation.
const (
	MaxEventBytes         = 32768
	MaxStreamMessageBytes = 8192
	MaxAPIErrorBytes      = 8192
)

// Channel is a logical channel of the platform protocol.
type Channel string

const (
	// ChannelOrganisation carries organisation and project lifecycle (docs/EVENTS.md
	// section 7).
	ChannelOrganisation Channel = "organisation"
	// ChannelJobs carries durable background work (docs/ARCHITECTURE.md section 4.8).
	ChannelJobs Channel = "jobs"
	// ChannelStream carries the project event stream of docs/API.md section 18.1.
	ChannelStream Channel = "stream"
	// ChannelAPI carries the HTTP response metadata and refusal envelope of docs/API.md
	// section 5.
	ChannelAPI Channel = "api"
)

// ChannelValues lists every channel in declaration order.
var ChannelValues = []Channel{ChannelOrganisation, ChannelJobs, ChannelStream, ChannelAPI}

// MessageType is defined by the connector protocol schema.
//
// The event types this source owns. Unknown types are rejected by this codec, never
// ignored. This enumeration MUST equal the keys of x-protocol.messages, and is a
// subset of the event_types vocabulary: an event type defined in another schema source
// is decoded by that source.
type MessageType string

const (
	MessageTypeOrganisationCreated          MessageType = "organisation.created"
	MessageTypeProjectCreated               MessageType = "project.created"
	MessageTypeProjectUpdated               MessageType = "project.updated"
	MessageTypeProjectRepositoryChanged     MessageType = "project.repository_changed"
	MessageTypeProjectArchived              MessageType = "project.archived"
	MessageTypeUserInvited                  MessageType = "user.invited"
	MessageTypeUserCredentialsSet           MessageType = "user.credentials_set"
	MessageTypeAuthenticationLoginSucceeded MessageType = "authentication.login_succeeded"
	MessageTypeAuthenticationLoginFailed    MessageType = "authentication.login_failed"
	MessageTypeSessionRevoked               MessageType = "session.revoked"
	MessageTypeJobEnqueued                  MessageType = "job.enqueued"
	MessageTypeJobSucceeded                 MessageType = "job.succeeded"
	MessageTypeJobFailed                    MessageType = "job.failed"
)

// MessageTypeValues lists every value in declaration order.
var MessageTypeValues = []MessageType{MessageTypeOrganisationCreated, MessageTypeProjectCreated, MessageTypeProjectUpdated, MessageTypeProjectRepositoryChanged, MessageTypeProjectArchived, MessageTypeUserInvited, MessageTypeUserCredentialsSet, MessageTypeAuthenticationLoginSucceeded, MessageTypeAuthenticationLoginFailed, MessageTypeSessionRevoked, MessageTypeJobEnqueued, MessageTypeJobSucceeded, MessageTypeJobFailed}

// ErrorClass is defined by the connector protocol schema.
//
// Stable API error code (docs/API.md section 5, docs/MCP_SPEC.md section 12). This
// enumeration MUST equal x-protocol.error_classes. Adding a code is additive within a
// protocol version, and clients MUST tolerate a code they do not recognise.
type ErrorClass string

const (
	ErrorClassAuthenticationRequired      ErrorClass = "AUTHENTICATION_REQUIRED"
	ErrorClassAuthorisationDenied         ErrorClass = "AUTHORISATION_DENIED"
	ErrorClassProjectContextAmbiguous     ErrorClass = "PROJECT_CONTEXT_AMBIGUOUS"
	ErrorClassProjectContextMismatch      ErrorClass = "PROJECT_CONTEXT_MISMATCH"
	ErrorClassResourceNotFound            ErrorClass = "RESOURCE_NOT_FOUND"
	ErrorClassResourceStale               ErrorClass = "RESOURCE_STALE"
	ErrorClassVersionConflict             ErrorClass = "VERSION_CONFLICT"
	ErrorClassIdempotencyConflict         ErrorClass = "IDEMPOTENCY_CONFLICT"
	ErrorClassValidationFailed            ErrorClass = "VALIDATION_FAILED"
	ErrorClassConnectorOffline            ErrorClass = "CONNECTOR_OFFLINE"
	ErrorClassPublishedServiceUnavailable ErrorClass = "PUBLISHED_SERVICE_UNAVAILABLE"
	ErrorClassBrowserCapacityExhausted    ErrorClass = "BROWSER_CAPACITY_EXHAUSTED"
	ErrorClassBrowserSessionNotActive     ErrorClass = "BROWSER_SESSION_NOT_ACTIVE"
	ErrorClassBrowserCommandTimeout       ErrorClass = "BROWSER_COMMAND_TIMEOUT"
	ErrorClassControlNotOwned             ErrorClass = "CONTROL_NOT_OWNED"
	ErrorClassControlEpochStale           ErrorClass = "CONTROL_EPOCH_STALE"
	ErrorClassPolicyDenied                ErrorClass = "POLICY_DENIED"
	ErrorClassApprovalRequired            ErrorClass = "APPROVAL_REQUIRED"
	ErrorClassEvidenceRequired            ErrorClass = "EVIDENCE_REQUIRED"
	ErrorClassArtefactUploadIncomplete    ErrorClass = "ARTEFACT_UPLOAD_INCOMPLETE"
	ErrorClassUnsupportedCapability       ErrorClass = "UNSUPPORTED_CAPABILITY"
	ErrorClassRateLimited                 ErrorClass = "RATE_LIMITED"
	ErrorClassInternalError               ErrorClass = "INTERNAL_ERROR"
)

// ErrorClassValues lists every value in declaration order.
var ErrorClassValues = []ErrorClass{ErrorClassAuthenticationRequired, ErrorClassAuthorisationDenied, ErrorClassProjectContextAmbiguous, ErrorClassProjectContextMismatch, ErrorClassResourceNotFound, ErrorClassResourceStale, ErrorClassVersionConflict, ErrorClassIdempotencyConflict, ErrorClassValidationFailed, ErrorClassConnectorOffline, ErrorClassPublishedServiceUnavailable, ErrorClassBrowserCapacityExhausted, ErrorClassBrowserSessionNotActive, ErrorClassBrowserCommandTimeout, ErrorClassControlNotOwned, ErrorClassControlEpochStale, ErrorClassPolicyDenied, ErrorClassApprovalRequired, ErrorClassEvidenceRequired, ErrorClassArtefactUploadIncomplete, ErrorClassUnsupportedCapability, ErrorClassRateLimited, ErrorClassInternalError}

// ActorType is defined by the connector protocol schema.
//
// Kind of principal an event is attributed to (docs/EVENTS.md section 5). Actor
// identity MUST never be inferred from display text.
type ActorType string

const (
	ActorTypeHumanUser     ActorType = "human_user"
	ActorTypeAgentSession  ActorType = "agent_session"
	ActorTypeConnector     ActorType = "connector"
	ActorTypeBrowserWorker ActorType = "browser_worker"
	ActorTypeSystem        ActorType = "system"
	ActorTypeIntegration   ActorType = "integration"
)

// ActorTypeValues lists every value in declaration order.
var ActorTypeValues = []ActorType{ActorTypeHumanUser, ActorTypeAgentSession, ActorTypeConnector, ActorTypeBrowserWorker, ActorTypeSystem, ActorTypeIntegration}

// JobKind is defined by the connector protocol schema.
//
// Durable background work the runner understands (docs/ARCHITECTURE.md section 4.8).
// It is an enumeration because an operator reading a failed job needs a name with a
// fixed meaning, not free text a caller chose.
type JobKind string

const (
	JobKindEventOutboxDispatch    JobKind = "event_outbox_dispatch"
	JobKindIdempotencyKeyExpiry   JobKind = "idempotency_key_expiry"
	JobKindPublishedServiceExpiry JobKind = "published_service_expiry"
)

// JobKindValues lists every value in declaration order.
var JobKindValues = []JobKind{JobKindEventOutboxDispatch, JobKindIdempotencyKeyExpiry, JobKindPublishedServiceExpiry}

// JobFailureReason is defined by the connector protocol schema.
//
// Why a job attempt failed. Stable, so a dead-lettered job can be diagnosed from the
// audit trail alone.
type JobFailureReason string

const (
	JobFailureReasonHandlerError      JobFailureReason = "handler_error"
	JobFailureReasonAttemptTimeout    JobFailureReason = "attempt_timeout"
	JobFailureReasonAttemptsExhausted JobFailureReason = "attempts_exhausted"
	JobFailureReasonHandlerUnknown    JobFailureReason = "handler_unknown"
)

// JobFailureReasonValues lists every value in declaration order.
var JobFailureReasonValues = []JobFailureReason{JobFailureReasonHandlerError, JobFailureReasonAttemptTimeout, JobFailureReasonAttemptsExhausted, JobFailureReasonHandlerUnknown}

// ProjectStatus is defined by the connector protocol schema.
//
// Project lifecycle status (docs/DOMAIN_MODEL.md section 5).
type ProjectStatus string

const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusArchived ProjectStatus = "archived"
)

// ProjectStatusValues lists every value in declaration order.
var ProjectStatusValues = []ProjectStatus{ProjectStatusActive, ProjectStatusArchived}

// OrganisationStatus is defined by the connector protocol schema.
//
// Organisation lifecycle status (docs/DOMAIN_MODEL.md section 4).
type OrganisationStatus string

const (
	OrganisationStatusActive    OrganisationStatus = "active"
	OrganisationStatusSuspended OrganisationStatus = "suspended"
)

// OrganisationStatusValues lists every value in declaration order.
var OrganisationStatusValues = []OrganisationStatus{OrganisationStatusActive, OrganisationStatusSuspended}

// UserStatus is defined by the connector protocol schema.
//
// User lifecycle status (docs/DOMAIN_MODEL.md section 5). A suspended user keeps every
// record they authored and can no longer authenticate.
type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

// UserStatusValues lists every value in declaration order.
var UserStatusValues = []UserStatus{UserStatusActive, UserStatusSuspended}

// LoginMethod is defined by the connector protocol schema.
//
// How a human authenticated. bootstrap_token is the ADR-0016 exchange, install_token
// is the one-time administrator bootstrap, and password is a local account.
type LoginMethod string

const (
	LoginMethodPassword       LoginMethod = "password"
	LoginMethodBootstrapToken LoginMethod = "bootstrap_token"
	LoginMethodInstallToken   LoginMethod = "install_token"
)

// LoginMethodValues lists every value in declaration order.
var LoginMethodValues = []LoginMethod{LoginMethodPassword, LoginMethodBootstrapToken, LoginMethodInstallToken}

// LoginFailureReason is defined by the connector protocol schema.
//
// Why an authentication attempt was refused. Stable, so a run of failures can be
// classified from the audit trail alone without any record of what was submitted.
type LoginFailureReason string

const (
	LoginFailureReasonUnknownUser          LoginFailureReason = "unknown_user"
	LoginFailureReasonInvalidPassword      LoginFailureReason = "invalid_password"
	LoginFailureReasonPasswordNotSet       LoginFailureReason = "password_not_set"
	LoginFailureReasonUserSuspended        LoginFailureReason = "user_suspended"
	LoginFailureReasonRateLimited          LoginFailureReason = "rate_limited"
	LoginFailureReasonInstallTokenInvalid  LoginFailureReason = "install_token_invalid"
	LoginFailureReasonInstallTokenExpired  LoginFailureReason = "install_token_expired"
	LoginFailureReasonInstallTokenConsumed LoginFailureReason = "install_token_consumed"
)

// LoginFailureReasonValues lists every value in declaration order.
var LoginFailureReasonValues = []LoginFailureReason{LoginFailureReasonUnknownUser, LoginFailureReasonInvalidPassword, LoginFailureReasonPasswordNotSet, LoginFailureReasonUserSuspended, LoginFailureReasonRateLimited, LoginFailureReasonInstallTokenInvalid, LoginFailureReasonInstallTokenExpired, LoginFailureReasonInstallTokenConsumed}

// SessionRevocationReason is defined by the connector protocol schema.
//
// Why a session stopped being usable.
type SessionRevocationReason string

const (
	SessionRevocationReasonSignOut                SessionRevocationReason = "sign_out"
	SessionRevocationReasonRotated                SessionRevocationReason = "rotated"
	SessionRevocationReasonRevokedByUser          SessionRevocationReason = "revoked_by_user"
	SessionRevocationReasonRevokedByAdministrator SessionRevocationReason = "revoked_by_administrator"
)

// SessionRevocationReasonValues lists every value in declaration order.
var SessionRevocationReasonValues = []SessionRevocationReason{SessionRevocationReasonSignOut, SessionRevocationReasonRotated, SessionRevocationReasonRevokedByUser, SessionRevocationReasonRevokedByAdministrator}

// StreamSubscribeType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamSubscribeType string

const (
	StreamSubscribeTypeStreamSubscribe StreamSubscribeType = "stream.subscribe"
)

// StreamSubscribeTypeValues lists every value in declaration order.
var StreamSubscribeTypeValues = []StreamSubscribeType{StreamSubscribeTypeStreamSubscribe}

// StreamSubscribedType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamSubscribedType string

const (
	StreamSubscribedTypeStreamSubscribed StreamSubscribedType = "stream.subscribed"
)

// StreamSubscribedTypeValues lists every value in declaration order.
var StreamSubscribedTypeValues = []StreamSubscribedType{StreamSubscribedTypeStreamSubscribed}

// StreamRefreshRequiredType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamRefreshRequiredType string

const (
	StreamRefreshRequiredTypeStreamRefreshRequired StreamRefreshRequiredType = "stream.refresh_required"
)

// StreamRefreshRequiredTypeValues lists every value in declaration order.
var StreamRefreshRequiredTypeValues = []StreamRefreshRequiredType{StreamRefreshRequiredTypeStreamRefreshRequired}

// StreamRefreshRequiredReason is defined by the connector protocol schema.
//
// Why a replay was not possible.
type StreamRefreshRequiredReason string

const (
	StreamRefreshRequiredReasonReplayWindowExceeded  StreamRefreshRequiredReason = "replay_window_exceeded"
	StreamRefreshRequiredReasonSequenceAheadOfStream StreamRefreshRequiredReason = "sequence_ahead_of_stream"
	StreamRefreshRequiredReasonReplayLimitExceeded   StreamRefreshRequiredReason = "replay_limit_exceeded"
)

// StreamRefreshRequiredReasonValues lists every value in declaration order.
var StreamRefreshRequiredReasonValues = []StreamRefreshRequiredReason{StreamRefreshRequiredReasonReplayWindowExceeded, StreamRefreshRequiredReasonSequenceAheadOfStream, StreamRefreshRequiredReasonReplayLimitExceeded}

// StreamHeartbeatType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamHeartbeatType string

const (
	StreamHeartbeatTypeStreamHeartbeat StreamHeartbeatType = "stream.heartbeat"
)

// StreamHeartbeatTypeValues lists every value in declaration order.
var StreamHeartbeatTypeValues = []StreamHeartbeatType{StreamHeartbeatTypeStreamHeartbeat}

// StreamErrorType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamErrorType string

const (
	StreamErrorTypeStreamError StreamErrorType = "stream.error"
)

// StreamErrorTypeValues lists every value in declaration order.
var StreamErrorTypeValues = []StreamErrorType{StreamErrorTypeStreamError}

// MessageDirection states which side of the trust boundary sends a message.
type MessageDirection string

const (
	DirectionControlPlaneToSubscriber MessageDirection = "control_plane_to_subscriber"
	DirectionSubscriberToControlPlane MessageDirection = "subscriber_to_control_plane"
)

// MessageDirections records the sender of each message type.
var MessageDirections = map[MessageType]MessageDirection{
	MessageTypeOrganisationCreated:          DirectionControlPlaneToSubscriber,
	MessageTypeProjectCreated:               DirectionControlPlaneToSubscriber,
	MessageTypeProjectUpdated:               DirectionControlPlaneToSubscriber,
	MessageTypeProjectRepositoryChanged:     DirectionControlPlaneToSubscriber,
	MessageTypeProjectArchived:              DirectionControlPlaneToSubscriber,
	MessageTypeUserInvited:                  DirectionControlPlaneToSubscriber,
	MessageTypeUserCredentialsSet:           DirectionControlPlaneToSubscriber,
	MessageTypeAuthenticationLoginSucceeded: DirectionControlPlaneToSubscriber,
	MessageTypeAuthenticationLoginFailed:    DirectionControlPlaneToSubscriber,
	MessageTypeSessionRevoked:               DirectionControlPlaneToSubscriber,
	MessageTypeJobEnqueued:                  DirectionControlPlaneToSubscriber,
	MessageTypeJobSucceeded:                 DirectionControlPlaneToSubscriber,
	MessageTypeJobFailed:                    DirectionControlPlaneToSubscriber,
}

// MessageChannels records the channel each message type travels on.
var MessageChannels = map[MessageType]Channel{
	MessageTypeOrganisationCreated:          ChannelOrganisation,
	MessageTypeProjectCreated:               ChannelOrganisation,
	MessageTypeProjectUpdated:               ChannelOrganisation,
	MessageTypeProjectRepositoryChanged:     ChannelOrganisation,
	MessageTypeProjectArchived:              ChannelOrganisation,
	MessageTypeUserInvited:                  ChannelOrganisation,
	MessageTypeUserCredentialsSet:           ChannelOrganisation,
	MessageTypeAuthenticationLoginSucceeded: ChannelOrganisation,
	MessageTypeAuthenticationLoginFailed:    ChannelOrganisation,
	MessageTypeSessionRevoked:               ChannelOrganisation,
	MessageTypeJobEnqueued:                  ChannelJobs,
	MessageTypeJobSucceeded:                 ChannelJobs,
	MessageTypeJobFailed:                    ChannelJobs,
}

// PayloadMaxBytes records the maximum canonical payload size for each message type. A
// payload larger than its bound is rejected.
var PayloadMaxBytes = map[MessageType]int{
	MessageTypeOrganisationCreated:          1024,
	MessageTypeProjectCreated:               1024,
	MessageTypeProjectUpdated:               1024,
	MessageTypeProjectRepositoryChanged:     1024,
	MessageTypeProjectArchived:              512,
	MessageTypeUserInvited:                  512,
	MessageTypeUserCredentialsSet:           512,
	MessageTypeAuthenticationLoginSucceeded: 512,
	MessageTypeAuthenticationLoginFailed:    512,
	MessageTypeSessionRevoked:               512,
	MessageTypeJobEnqueued:                  1024,
	MessageTypeJobSucceeded:                 1024,
	MessageTypeJobFailed:                    1024,
}

// ViolationReason classifies a refused frame. Only some reasons map to a wire error
// class.
type ViolationReason string

const (
	// ReasonFrameTooLarge reports that the encoded event or message exceeded its byte
	// bound. Detected on the raw bytes before deserialisation.
	ReasonFrameTooLarge ViolationReason = "frame_too_large"
	// ReasonMalformedJSON reports that the message was not well-formed JSON, or was
	// truncated.
	ReasonMalformedJSON ViolationReason = "malformed_json"
	// ReasonUnsupportedSchemaVersion reports that schema_version was absent, not an
	// integer, or not a version this build accepts.
	ReasonUnsupportedSchemaVersion ViolationReason = "unsupported_schema_version"
	// ReasonUnknownMessageType reports that type was absent or not an event type this
	// source owns. A consumer that receives an event type it does not know MUST ignore it
	// rather than fail; a producer that writes one through this codec is refused.
	ReasonUnknownMessageType ViolationReason = "unknown_message_type"
	// ReasonPayloadTooLarge reports that the payload exceeded the byte bound declared for
	// its event type.
	ReasonPayloadTooLarge ViolationReason = "payload_too_large"
	// ReasonSchemaViolation reports that the message parsed but did not satisfy the
	// schema for its type.
	ReasonSchemaViolation ViolationReason = "schema_violation"
)

// ViolationErrorClass maps a rejection reason to the connector error class reported
// for it.
var ViolationErrorClass = map[ViolationReason]ErrorClass{
	ReasonFrameTooLarge:            "",
	ReasonMalformedJSON:            "",
	ReasonUnsupportedSchemaVersion: ErrorClassUnsupportedCapability,
	ReasonUnknownMessageType:       ErrorClassUnsupportedCapability,
	ReasonPayloadTooLarge:          "",
	ReasonSchemaViolation:          ErrorClassValidationFailed,
}

// SchemaViolationCode identifies the kind of schema failure.
type SchemaViolationCode string

const (
	SchemaViolationType            SchemaViolationCode = "type"
	SchemaViolationRequired        SchemaViolationCode = "required"
	SchemaViolationForbidden       SchemaViolationCode = "forbidden"
	SchemaViolationUnknownProperty SchemaViolationCode = "unknown_property"
	SchemaViolationEnum            SchemaViolationCode = "enum"
	SchemaViolationConst           SchemaViolationCode = "const"
	SchemaViolationPattern         SchemaViolationCode = "pattern"
	SchemaViolationTooShort        SchemaViolationCode = "too_short"
	SchemaViolationTooLong         SchemaViolationCode = "too_long"
	SchemaViolationTooSmall        SchemaViolationCode = "too_small"
	SchemaViolationTooLarge        SchemaViolationCode = "too_large"
	SchemaViolationTooFewItems     SchemaViolationCode = "too_few_items"
	SchemaViolationTooManyItems    SchemaViolationCode = "too_many_items"
	SchemaViolationDuplicateItems  SchemaViolationCode = "duplicate_items"
	SchemaViolationNotInteger      SchemaViolationCode = "not_integer"
)

// SchemaViolation is one schema failure, located by JSON path.
type SchemaViolation struct {
	Path    string              `json:"path"`
	Code    SchemaViolationCode `json:"code"`
	Message string              `json:"message"`
}

// EventTypes lists the stage 1 event catalogue of docs/EVENTS.md section 7. Event
// names are stable public integration contracts; adding one is additive within a
// schema version, which is why the envelope's type field bounds a name's shape rather
// than enumerating it. A consumer that does not recognise a name MUST ignore the event
// rather than fail.
var EventTypes = []string{"organisation.created", "user.invited", "user.credentials_set", "authentication.login_succeeded", "authentication.login_failed", "session.revoked", "project.created", "project.updated", "project.repository_changed", "project.archived", "connector.enrolled", "connector.connected", "connector.degraded", "connector.disconnected", "connector.revoked", "workspace.observed", "workspace.head_changed", "published_service.requested", "published_service.ready", "published_service.failed", "published_service.expired", "published_service.revoked", "agent_credential.issued", "agent_session.started", "agent_session.waiting", "agent_session.blocked", "agent_session.completed", "agent_session.failed", "agent_session.disconnected", "browser_session.requested", "browser_session.allocated", "browser_session.ready", "browser_session.navigated", "browser_session.paused", "browser_session.resumed", "browser_session.degraded", "browser_session.terminated", "browser_session.failed", "browser.control_requested", "browser.control_transferred", "browser.control_released", "browser.command_rejected", "browser.command_executed", "browser.live_view_started", "browser.live_view_stopped", "screenshot.captured", "artefact.upload_started", "artefact.upload_completed", "artefact.upload_failed", "artefact.access_granted", "artefact.redacted", "artefact.expired", "review.created", "review.named", "review.assigned", "review.claimed", "review.status_changed", "review.accepted", "review.reopened", "review.archived", "finding.created", "finding.annotated", "finding.claimed", "finding.status_changed", "finding.comment_added", "finding.verification_submitted", "finding.verification_accepted", "finding.verification_rejected", "finding.resolved", "finding.reopened", "job.enqueued", "job.succeeded", "job.failed"}

// StreamMessageTypes lists the discriminator values carried by the stream control
// messages of docs/API.md section 18.1. An event envelope carries its own event type
// in the same field, so one member distinguishes every message on the channel.
var StreamMessageTypes = []string{"stream.subscribe", "stream.subscribed", "stream.refresh_required", "stream.heartbeat", "stream.error"}

// IdempotencyHeaders lists the request headers that carry an idempotency key on a
// state-changing HTTP request (docs/API.md section 2, docs/MCP_SPEC.md section 10).
// The key is scoped to actor, operation and project; the header only carries it.
var IdempotencyHeaders = []string{"Idempotency-Key"}

// CorrelationHeaders lists the request headers that carry a correlation identifier
// (docs/ARCHITECTURE.md section 15). The control plane mints one when the caller
// supplies none and returns it as meta.request_id on every response.
var CorrelationHeaders = []string{"X-Request-Id"}

// PaginationParameters lists the query parameters of a paginated collection
// (docs/API.md section 6). The cursor is opaque and MUST NOT be constructed by a
// client.
var PaginationParameters = []string{"cursor", "limit"}

// IdentifierPrefixes records the conventional prefixes of the opaque identifiers this
// protocol carries. They are documentation only: consumers must treat identifiers as
// opaque and validators must not require a prefix.
var IdentifierPrefixes = map[string]string{
	"organisation":      "org_",
	"user":              "usr_",
	"install_token":     "ins_",
	"human_session":     "vwr_",
	"project":           "prj_",
	"environment":       "env_",
	"connector":         "con_",
	"workspace":         "wsp_",
	"published_service": "svc_",
	"agent_credential":  "agc_",
	"agent_session":     "ags_",
	"browser_worker":    "wkr_",
	"browser_session":   "brs_",
	"control_lease":     "lse_",
	"review":            "rev_",
	"finding":           "fin_",
	"comment":           "cmt_",
	"annotation":        "ann_",
	"artefact":          "art_",
	"artefact_grant":    "agr_",
	"verification":      "ver_",
	"event":             "evt_",
	"job":               "job_",
	"request":           "req_",
}

// Identifier is defined by the connector protocol schema.
//
// Opaque durable identifier (docs/DOMAIN_MODEL.md section 3). Consumers MUST treat the
// value as opaque: the schema bounds only its length and character class and never its
// documented prefix, and the value encodes no tenant, no timestamp and no database
// sequence.
type Identifier = string

// Timestamp is defined by the connector protocol schema.
//
// RFC 3339 timestamp in UTC, with a mandatory trailing Z.
type Timestamp = string

// SequenceNumber is defined by the connector protocol schema.
//
// Position in a project's event stream. Monotonically increasing within a project and
// never reused. Global ordering across projects is not guaranteed, and the value is
// not a database row identifier a consumer may depend on.
type SequenceNumber = int64

// Cursor is defined by the connector protocol schema.
//
// Opaque pagination cursor (docs/API.md section 6). It is base64url text without
// padding; its contents are the server's business and a client MUST NOT parse,
// construct or modify one.
type Cursor = string

// Slug is defined by the connector protocol schema.
//
// Human-friendly alias, unique inside its parent. Mutable, and never a substitute for
// the identifier (docs/DOMAIN_MODEL.md section 3).
type Slug = string

// DisplayName is defined by the connector protocol schema.
//
// Name a human reads. It is description and never an authorisation input.
type DisplayName = string

// EmailAddress is defined by the connector protocol schema.
//
// Address a human is known by. It is an alias for a user, never an identity: the
// identifier is what every other record references. The bound is the RFC 5321 maximum
// path length. The pattern is deliberately permissive — one at-sign, no whitespace and
// no control characters — because a stricter one rejects addresses that work: a
// dotless host such as administrator@localhost is what a fresh self-hosted
// installation is seeded with, and deliverability is not something a schema can
// decide.
type EmailAddress = string

// GitRefName is defined by the connector protocol schema.
//
// Git branch name. Bounded and restricted to the characters a ref may hold, so a value
// stored here cannot become an argument to something else.
type GitRefName = string

// RepositoryIdentity is defined by the connector protocol schema.
//
// Provider-agnostic repository identity (docs/DOMAIN_MODEL.md section 6). canonical is
// the normalised host-and-path form that two clone URLs for the same repository both
// reduce to, which is what lets an SSH remote and an HTTPS remote be recognised as one
// repository. clone_urls records the forms actually seen, for display and for a
// connector to match a checkout against.
type RepositoryIdentity struct {
	// Normalised host and path, lowercase host, no scheme, no credentials, no .git suffix
	// and no trailing slash, for example github.com/example/refresh-surplus.
	Canonical string `json:"canonical"`
	// Clone URLs that reduce to canonical, in the order they were supplied. Duplicates
	// are removed by the control plane before storage.
	CloneURLs []string `json:"clone_urls,omitempty"`
}

// ValidationViewport is defined by the connector protocol schema.
//
// A viewport the project validates at (docs/UX_FLOWS.md section 4). The bounds are the
// browser protocol's, because a viewport stored here is one a browser session is later
// asked to adopt; a value the worker would refuse must not be storable.
type ValidationViewport struct {
	// Viewport width in CSS pixels.
	Width int64 `json:"width"`
	// Viewport height in CSS pixels.
	Height int64 `json:"height"`
	// Device pixel ratio. Absent means 1, which is what a browser session adopts when the
	// project does not say otherwise.
	DeviceScaleFactor *float64 `json:"device_scale_factor,omitempty"`
}

// ProjectSettings is defined by the connector protocol schema.
//
// Project settings (docs/DOMAIN_MODEL.md section 6). Stage 1 holds the default
// validation viewports and nothing else; the object refuses unknown members so a
// setting cannot be introduced in one service without being defined here first.
type ProjectSettings struct {
	// Viewports a finding is expected to be validated at. It defaults to 390x844 and
	// 1440x900, which AGENTS.md requires of browser-facing work and the Stage 1
	// completion gate checks against.
	DefaultValidationViewports []ValidationViewport `json:"default_validation_viewports"`
}

// Organisation is defined by the connector protocol schema.
//
// The top-level administrative and data-isolation boundary (docs/DOMAIN_MODEL.md
// section 4).
type Organisation struct {
	// Organisation identity, conventionally prefixed org_.
	ID string `json:"id"`
	// Display name.
	Name string `json:"name"`
	// Mutable alias.
	Slug string `json:"slug"`
	// Lifecycle status.
	Status OrganisationStatus `json:"status"`
	// When the organisation was created.
	CreatedAt string `json:"created_at"`
	// When it last changed.
	UpdatedAt string `json:"updated_at"`
}

// User is defined by the connector protocol schema.
//
// A human identity (docs/DOMAIN_MODEL.md section 5). It never carries credential
// material: whether a password exists is stated, and the hash is not part of any
// representation that leaves the database.
type User struct {
	// User identity, conventionally prefixed usr_.
	ID string `json:"id"`
	// Owning organisation, carried for defence-in-depth filtering (docs/DOMAIN_MODEL.md
	// section 3).
	OrganisationID string `json:"organisation_id"`
	// Address the human is known by.
	Email string `json:"email"`
	// Name shown in a timeline.
	DisplayName string `json:"display_name"`
	// Lifecycle status.
	Status UserStatus `json:"status"`
	// Whether this user can authenticate locally. It is the fact a first-run screen
	// needs, and it says nothing about the credential itself. The name avoids the word
	// the schema checker forbids in a field, which exists so that no protocol field can
	// ever carry a credential.
	LocalCredentialSet *bool `json:"local_credential_set,omitempty"`
	// When the user record was created.
	CreatedAt string `json:"created_at"`
	// When it last changed.
	UpdatedAt string `json:"updated_at"`
}

// Project is defined by the connector protocol schema.
//
// The principal working boundary (docs/DOMAIN_MODEL.md section 6). A review belongs to
// exactly one project, and a browser session may only route to services authorised for
// the same project.
type Project struct {
	// Project identity, conventionally prefixed prj_.
	ID string `json:"id"`
	// Owning organisation, carried for defence-in-depth filtering.
	OrganisationID string `json:"organisation_id"`
	// Display name.
	Name string `json:"name"`
	// Alias, unique within the organisation.
	Slug string `json:"slug"`
	// Repository the project's work lands in. Absent until an operator supplies one; a
	// change to it is audited as project.repository_changed.
	RepositoryIdentity *RepositoryIdentity `json:"repository_identity,omitempty"`
	// Branch reviews are captured against by default.
	DefaultBranch string `json:"default_branch"`
	// Lifecycle status. Deleting a project archives it.
	Status ProjectStatus `json:"status"`
	// Project settings.
	Settings ProjectSettings `json:"settings"`
	// Optimistic-concurrency version (docs/API.md section 5.2). A write carrying a
	// different expected_version is refused with VERSION_CONFLICT rather than silently
	// overwriting.
	Version int64 `json:"version"`
	// When the project was created.
	CreatedAt string `json:"created_at"`
	// When it last changed.
	UpdatedAt string `json:"updated_at"`
}

// HumanSession is defined by the connector protocol schema.
//
// What a human session tells its own holder (docs/API.md section 4). The session token
// lives in an HTTP-only cookie and is never part of this representation; project_ids
// absent means organisation-wide scope, and a list means exactly those projects.
type HumanSession struct {
	// Session identity, conventionally prefixed vwr_.
	SessionID string `json:"session_id"`
	// The authenticated user. Absent for a session issued from the bootstrap
	// administrator token, which has no user record behind it (ADR-0016).
	UserID *string `json:"user_id,omitempty"`
	// Organisation the session acts in.
	OrganisationID *string `json:"organisation_id,omitempty"`
	// Address of the authenticated user, when there is one.
	Email *string `json:"email,omitempty"`
	// Name shown in the application shell.
	Display string `json:"display"`
	// Projects the session may reach. Absent means every project in the organisation.
	ProjectIDs []string `json:"project_ids,omitempty"`
	// When the session stops being usable without revocation.
	ExpiresAt string `json:"expires_at"`
}

// Actor is defined by the connector protocol schema.
//
// The principal an event is attributed to (docs/EVENTS.md section 2).
type Actor struct {
	// Principal kind. It is the authoritative part of an actor; display is not.
	Type ActorType `json:"type"`
	// Identifier of the principal, absent for a system actor that has none.
	ID *string `json:"id,omitempty"`
	// Human-readable label for a timeline. It is description and never an authorisation
	// input.
	Display *string `json:"display,omitempty"`
}

// Correlation is defined by the connector protocol schema.
//
// Correlation identifiers (docs/EVENTS.md section 2, docs/ARCHITECTURE.md section 15).
// Every member is an opaque identifier: correlation never carries a header, a body or
// a secret.
type Correlation struct {
	// The API request that caused the event, conventionally prefixed req_.
	RequestID *string `json:"request_id,omitempty"`
	// The event that caused this one, conventionally prefixed evt_.
	CausationEventID *string `json:"causation_event_id,omitempty"`
	// Connector, conventionally prefixed con_.
	ConnectorID *string `json:"connector_id,omitempty"`
	// Environment, conventionally prefixed env_.
	EnvironmentID *string `json:"environment_id,omitempty"`
	// Workspace, conventionally prefixed wsp_.
	WorkspaceID *string `json:"workspace_id,omitempty"`
	// Published service, conventionally prefixed svc_.
	PublishedServiceID *string `json:"published_service_id,omitempty"`
	// Agent session, conventionally prefixed ags_.
	AgentSessionID *string `json:"agent_session_id,omitempty"`
	// Browser session, conventionally prefixed brs_.
	BrowserSessionID *string `json:"browser_session_id,omitempty"`
	// Browser worker, conventionally prefixed wkr_.
	WorkerID *string `json:"worker_id,omitempty"`
	// Artefact, conventionally prefixed art_.
	ArtefactID *string `json:"artefact_id,omitempty"`
	// Review, conventionally prefixed rev_.
	ReviewID *string `json:"review_id,omitempty"`
	// Finding, conventionally prefixed fin_.
	FindingID *string `json:"finding_id,omitempty"`
	// Annotation, conventionally prefixed ann_.
	AnnotationID *string `json:"annotation_id,omitempty"`
	// Durable job, conventionally prefixed job_.
	JobID *string `json:"job_id,omitempty"`
}

// Envelope is defined by the connector protocol schema.
//
// The docs/EVENTS.md section 2 event envelope. Every event names the organisation it
// belongs to, its position in a stream, and the actor that caused it; the payload
// schema is selected by type. project_id is optional because an occurrence can precede
// any project association — a connector enrolment does — and every project-scoped read
// filters on it.
type Envelope struct {
	// Event identifier, conventionally prefixed evt_. Consumers deduplicate on it.
	ID string `json:"id"`
	// Envelope schema version. Stage 1 accepts 1 only; any other value is rejected rather
	// than best-effort parsed.
	SchemaVersion int64 `json:"schema_version"`
	// Monotonic position within the stream.
	Sequence int64 `json:"sequence"`
	// Event type. This codec owns the types in message_type; an event of another type is
	// decoded by the schema source that owns it.
	Type MessageType `json:"type"`
	// When the occurrence happened.
	OccurredAt string `json:"occurred_at"`
	// When the control plane committed the record.
	RecordedAt string `json:"recorded_at"`
	// Owning organisation, conventionally prefixed org_.
	OrganisationID string `json:"organisation_id"`
	// Owning project, conventionally prefixed prj_. Every project-scoped read of this
	// stream filters on it.
	ProjectID *string `json:"project_id,omitempty"`
	// Principal the occurrence is attributed to.
	Actor Actor `json:"actor"`
	// Correlation identifiers.
	Correlation *Correlation `json:"correlation,omitempty"`
}

// OrganisationCreatedPayload is defined by the connector protocol schema.
//
// Payload of organisation.created.
type OrganisationCreatedPayload struct {
	// Mutable human-friendly alias. The identifier is authoritative; this is not.
	Slug string `json:"slug"`
	// Display name.
	Name string `json:"name"`
}

// ProjectCreatedPayload is defined by the connector protocol schema.
//
// Payload of project.created.
type ProjectCreatedPayload struct {
	// Project-scoped alias. Mutable, and never a substitute for the identifier.
	Slug string `json:"slug"`
	// Display name.
	Name string `json:"name"`
	// Branch the project captures reviews against. Absent on a project created before the
	// field existed.
	DefaultBranch *string `json:"default_branch,omitempty"`
	// Normalised repository identity the project was created with, when one was supplied.
	// The canonical form alone: the clone URLs are queryable on the record and add
	// nothing an auditor needs.
	RepositoryCanonical *string `json:"repository_canonical,omitempty"`
}

// ProjectRepositoryChangedPayload is defined by the connector protocol schema.
//
// Payload of project.repository_changed. It carries both sides of the move, because a
// review captured before it was interpreted against the previous repository
// (docs/DOMAIN_MODEL.md section 6).
type ProjectRepositoryChangedPayload struct {
	// Normalised identity before the change. Absent when the project had no repository
	// association.
	PreviousCanonical *string `json:"previous_canonical,omitempty"`
	// Normalised identity after the change.
	NewCanonical string `json:"new_canonical"`
}

// UserInvitedPayload is defined by the connector protocol schema.
//
// Payload of user.invited. Issuing a credential-establishing token is a permission
// change, and docs/SECURITY.md section 16 requires an audit record for one. It never
// carries the token: a reader learns that a way in exists and when it closes, not what
// it is.
type UserInvitedPayload struct {
	// User the token establishes credentials for.
	UserID string `json:"user_id"`
	// Kind of token that was issued.
	Method LoginMethod `json:"method"`
	// When the token stops being usable, whether or not it was used.
	ExpiresAt string `json:"expires_at"`
}

// UserCredentialsSetPayload is defined by the connector protocol schema.
//
// Payload of user.credentials_set. Setting a password is a permission change and
// docs/SECURITY.md section 16 requires an audit record for one; the record names the
// user and the route the credential arrived by, and nothing else.
type UserCredentialsSetPayload struct {
	// User whose password changed.
	UserID string `json:"user_id"`
	// How the credential was established.
	Method LoginMethod `json:"method"`
}

// AuthenticationLoginSucceededPayload is defined by the connector protocol schema.
//
// Payload of authentication.login_succeeded.
type AuthenticationLoginSucceededPayload struct {
	// Session that was issued.
	SessionID string `json:"session_id"`
	// User that authenticated. Absent for the bootstrap-token exchange, which has no user
	// record behind it.
	UserID *string `json:"user_id,omitempty"`
	// How the human authenticated.
	Method LoginMethod `json:"method"`
}

// AuthenticationLoginFailedPayload is defined by the connector protocol schema.
//
// Payload of authentication.login_failed. It never carries the submitted credential,
// and never the identifier that was typed beside it: a password mistyped into an email
// field would otherwise be written to an append-only table (docs/SECURITY.md section
// 18).
type AuthenticationLoginFailedPayload struct {
	// Stable failure class.
	Reason LoginFailureReason `json:"reason"`
	// Route the attempt arrived by.
	Method LoginMethod `json:"method"`
	// User the attempt named, when it named one that exists. Absent for an unknown
	// address, which is what stops the audit trail confirming which addresses have
	// accounts.
	UserID *string `json:"user_id,omitempty"`
}

// SessionRevokedPayload is defined by the connector protocol schema.
//
// Payload of session.revoked.
type SessionRevokedPayload struct {
	// Session that was revoked.
	SessionID string `json:"session_id"`
	// User the session belonged to, when it belonged to one.
	UserID *string `json:"user_id,omitempty"`
	// Why it was revoked.
	Reason SessionRevocationReason `json:"reason"`
}

// ProjectUpdatedPayload is defined by the connector protocol schema.
//
// Payload of project.updated. It names the fields that changed rather than restating
// the record: current state is queryable, and the audit question is what moved.
type ProjectUpdatedPayload struct {
	// Attribute names that changed, in schema order.
	ChangedFields []string `json:"changed_fields"`
}

// ProjectArchivedPayload is defined by the connector protocol schema.
//
// Payload of project.archived. It carries previous and new state, which docs/EVENTS.md
// section 8 requires of a state change.
type ProjectArchivedPayload struct {
	// Status before the change.
	PreviousStatus ProjectStatus `json:"previous_status"`
	// Status after the change.
	NewStatus ProjectStatus `json:"new_status"`
}

// JobEnqueuedPayload is defined by the connector protocol schema.
//
// Payload of job.enqueued.
type JobEnqueuedPayload struct {
	// Job identity, conventionally prefixed job_.
	JobID string `json:"job_id"`
	// Work the job performs.
	Kind JobKind `json:"kind"`
	// Earliest time the runner may claim it.
	RunAfter string `json:"run_after"`
}

// JobSucceededPayload is defined by the connector protocol schema.
//
// Payload of job.succeeded.
type JobSucceededPayload struct {
	// Job identity.
	JobID string `json:"job_id"`
	// Work the job performed.
	Kind JobKind `json:"kind"`
	// Attempts made, including the one that succeeded.
	Attempts int64 `json:"attempts"`
	// Wall-clock duration of the successful attempt.
	DurationMs int64 `json:"duration_ms"`
}

// JobFailedPayload is defined by the connector protocol schema.
//
// Payload of job.failed.
type JobFailedPayload struct {
	// Job identity.
	JobID string `json:"job_id"`
	// Work the job attempted.
	Kind JobKind `json:"kind"`
	// Attempts made, including the one that failed.
	Attempts int64 `json:"attempts"`
	// Stable failure class.
	Reason JobFailureReason `json:"reason"`
	// Whether another attempt is scheduled. Stated rather than inferred, so an operator
	// can tell a retry from a dead job without reading the runner's source.
	Retrying bool `json:"retrying"`
	// When the next attempt becomes claimable. Absent when no attempt will follow.
	NextAttemptAt *string `json:"next_attempt_at,omitempty"`
}

// StreamSubscribe is defined by the connector protocol schema.
//
// Subscription request (docs/API.md section 18.1).
type StreamSubscribe struct {
	// Message discriminator.
	Type StreamSubscribeType `json:"type"`
	// The highest project sequence the client has already applied. Zero means the client
	// holds nothing and wants the stream from its start; a client that has just loaded
	// current state sends the sequence that state was read at.
	LastSequence int64 `json:"last_sequence"`
	// Largest replay the client will accept. A gap larger than this is answered with a
	// refresh instruction rather than a long replay, which is cheaper for both sides than
	// paging through history the client is about to refetch anyway.
	MaxReplay *int64 `json:"max_replay,omitempty"`
}

// StreamSubscribed is defined by the connector protocol schema.
//
// Subscription accepted.
type StreamSubscribed struct {
	// Message discriminator.
	Type StreamSubscribedType `json:"type"`
	// Project the stream belongs to.
	ProjectID string `json:"project_id"`
	// Sequence the stream is at now. Zero when the project has no events yet.
	CurrentSequence int64 `json:"current_sequence"`
	// Oldest sequence still replayable. A client below it receives a refresh instruction
	// instead of a replay.
	EarliestAvailableSequence int64 `json:"earliest_available_sequence"`
	// Whether events between the client's position and current_sequence follow before
	// live delivery begins.
	Replaying bool `json:"replaying"`
}

// StreamRefreshRequired is defined by the connector protocol schema.
//
// The client's position cannot be served from the retained stream (docs/EVENTS.md
// section 10).
type StreamRefreshRequired struct {
	// Message discriminator.
	Type StreamRefreshRequiredType `json:"type"`
	// Why a replay was not possible.
	Reason StreamRefreshRequiredReason `json:"reason"`
	// Sequence the stream is at now. A client refetches state and resumes from it.
	CurrentSequence int64 `json:"current_sequence"`
	// Oldest sequence still replayable.
	EarliestAvailableSequence int64 `json:"earliest_available_sequence"`
}

// StreamHeartbeat is defined by the connector protocol schema.
//
// Liveness on a quiet stream.
type StreamHeartbeat struct {
	// Message discriminator.
	Type StreamHeartbeatType `json:"type"`
	// Sequence the stream is at now.
	CurrentSequence int64 `json:"current_sequence"`
	// When the control plane sent the heartbeat.
	SentAt string `json:"sent_at"`
}

// StreamError is defined by the connector protocol schema.
//
// A refusal on an open subscription.
type StreamError struct {
	// Message discriminator.
	Type StreamErrorType `json:"type"`
	// Stable error code.
	Code ErrorClass `json:"code"`
	// Human-readable explanation. It never carries request data, a credential or a stack
	// trace.
	Message string `json:"message"`
	// Whether repeating the subscription verbatim can succeed. Stated rather than
	// inferred from the code, because the answer is not derivable from the code's shape.
	Retryable bool `json:"retryable"`
}

// ApiErrorDetails is defined by the connector protocol schema.
//
// Code-specific refusal detail (docs/MCP_SPEC.md section 12). Every member is optional
// and the object refuses unknown members, so the detail a caller may rely on is a
// fixed vocabulary rather than whatever a handler happened to attach.
type ApiErrorDetails struct {
	// The version the record actually holds. Carried by VERSION_CONFLICT so a caller can
	// re-read and retry rather than guess.
	CurrentVersion *int64 `json:"current_version,omitempty"`
	// The version the caller supplied. Carried beside current_version so a log line
	// records both halves of the conflict without the caller having to quote its own
	// request back.
	ExpectedVersion *int64 `json:"expected_version,omitempty"`
	// The control epoch that is current. Carried by CONTROL_EPOCH_STALE.
	CurrentEpoch *int64 `json:"current_epoch,omitempty"`
	// Identifiers the caller may name to resolve the ambiguity. Carried by
	// PROJECT_CONTEXT_AMBIGUOUS.
	Candidates []string `json:"candidates,omitempty"`
	// Transitions that are legal from the record's current state. Carried by a refused
	// transition.
	AllowedTransitions []string `json:"allowed_transitions,omitempty"`
	// Evidence the operation needs before it can succeed. Carried by EVIDENCE_REQUIRED.
	RequiredEvidence []string `json:"required_evidence,omitempty"`
	// Captured context the request omitted. Carried by a refusal to store a finding that
	// could not be reproduced later.
	MissingContext []string `json:"missing_context,omitempty"`
	// How long to wait before repeating the request. Carried by RATE_LIMITED and by a
	// duplicate that arrived while the first call was still in flight.
	RetryAfterMs *int64 `json:"retry_after_ms,omitempty"`
	// The request member the refusal is about.
	Field *string `json:"field,omitempty"`
	// Stable sub-reason where one code covers several causes.
	Reason *string `json:"reason,omitempty"`
}

// ApiError is defined by the connector protocol schema.
//
// The refusal itself (docs/API.md section 5).
type ApiError struct {
	// Stable machine-readable code.
	Code ErrorClass `json:"code"`
	// Human-readable explanation. It never carries a credential, request data or a stack
	// trace (docs/SECURITY.md section 18).
	Message string `json:"message"`
	// Code-specific detail.
	Details *ApiErrorDetails `json:"details,omitempty"`
}

// ApiMeta is defined by the connector protocol schema.
//
// Response metadata carried by every API response (docs/API.md sections 5 and 6).
type ApiMeta struct {
	// Correlation identifier for this request, conventionally prefixed req_. It appears
	// on success and on refusal, so a caller can quote one identifier when reporting
	// either.
	RequestID string `json:"request_id"`
	// Cursor for the next page. Absent on the last page and on a response that is not a
	// collection.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ApiErrorResponse is defined by the connector protocol schema.
//
// The complete refusal body (docs/API.md section 5). A success body is {"data": ...,
// "meta": ...} whose data is endpoint-specific and therefore defined by the endpoint's
// own schema; meta is api_meta in both cases.
type ApiErrorResponse struct {
	// The refusal.
	Error ApiError `json:"error"`
	// Response metadata.
	Meta ApiMeta `json:"meta"`
}

// CursorClaims is defined by the connector protocol schema.
//
// What an opaque pagination cursor encodes. It is defined here so both languages
// encode and decode the same bytes, and never to invite a client to build one: the
// encoded form is base64url text and the API refuses a cursor whose shape it did not
// produce.
type CursorClaims struct {
	// Cursor format version. A cursor of another version is refused rather than guessed
	// at.
	Version int64 `json:"version"`
	// Value of the collection's sort column at the last row of the previous page.
	SortKey string `json:"sort_key"`
	// Identifier of the last row of the previous page, which breaks ties when the sort
	// column repeats.
	ID string `json:"id"`
}

// Payload is implemented by every version 1 message payload. The interface is closed:
// only payloads generated from the schema can satisfy it.
type Payload interface {
	// MessageType reports the envelope type this payload belongs to.
	MessageType() MessageType
	isConnectorPayload()
}

// MessageType reports the envelope type carrying a OrganisationCreatedPayload.
func (OrganisationCreatedPayload) MessageType() MessageType { return MessageTypeOrganisationCreated }

func (OrganisationCreatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectCreatedPayload.
func (ProjectCreatedPayload) MessageType() MessageType { return MessageTypeProjectCreated }

func (ProjectCreatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectUpdatedPayload.
func (ProjectUpdatedPayload) MessageType() MessageType { return MessageTypeProjectUpdated }

func (ProjectUpdatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectRepositoryChangedPayload.
func (ProjectRepositoryChangedPayload) MessageType() MessageType {
	return MessageTypeProjectRepositoryChanged
}

func (ProjectRepositoryChangedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectArchivedPayload.
func (ProjectArchivedPayload) MessageType() MessageType { return MessageTypeProjectArchived }

func (ProjectArchivedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a UserInvitedPayload.
func (UserInvitedPayload) MessageType() MessageType { return MessageTypeUserInvited }

func (UserInvitedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a UserCredentialsSetPayload.
func (UserCredentialsSetPayload) MessageType() MessageType { return MessageTypeUserCredentialsSet }

func (UserCredentialsSetPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a
// AuthenticationLoginSucceededPayload.
func (AuthenticationLoginSucceededPayload) MessageType() MessageType {
	return MessageTypeAuthenticationLoginSucceeded
}

func (AuthenticationLoginSucceededPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a AuthenticationLoginFailedPayload.
func (AuthenticationLoginFailedPayload) MessageType() MessageType {
	return MessageTypeAuthenticationLoginFailed
}

func (AuthenticationLoginFailedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a SessionRevokedPayload.
func (SessionRevokedPayload) MessageType() MessageType { return MessageTypeSessionRevoked }

func (SessionRevokedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobEnqueuedPayload.
func (JobEnqueuedPayload) MessageType() MessageType { return MessageTypeJobEnqueued }

func (JobEnqueuedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobSucceededPayload.
func (JobSucceededPayload) MessageType() MessageType { return MessageTypeJobSucceeded }

func (JobSucceededPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobFailedPayload.
func (JobFailedPayload) MessageType() MessageType { return MessageTypeJobFailed }

func (JobFailedPayload) isConnectorPayload() {}

// Frame is a decoded control frame: envelope header plus its typed payload.
type Frame struct {
	Envelope Envelope
	Payload  Payload
}
