// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

// ProtocolName is the protocol described by ReviewPlane platform foundation, version
// 1.
const ProtocolName = "platform"

// ProtocolVersion is the only version this build accepts. An envelope carrying any
// other value is rejected with ErrorClassProtocolUnsupported and is never best-effort
// parsed.
const ProtocolVersion int64 = 1

// Byte bounds enforced on raw frames before deserialisation.
const (
	MaxEventBytes         = 32768
	MaxStreamMessageBytes = 8192
	MaxAPIErrorBytes      = 8192
)

// Channel is a logical channel of the platform protocol.
type Channel string

const (
	// ChannelOrganisation carries organisation and project lifecycle (docs/EVENTS.md
	// section 7).
	ChannelOrganisation Channel = "organisation"
	// ChannelJobs carries durable background work (docs/ARCHITECTURE.md section 4.8).
	ChannelJobs Channel = "jobs"
	// ChannelStream carries the project event stream of docs/API.md section 18.1.
	ChannelStream Channel = "stream"
	// ChannelAPI carries the HTTP response metadata and refusal envelope of docs/API.md
	// section 5.
	ChannelAPI Channel = "api"
)

// ChannelValues lists every channel in declaration order.
var ChannelValues = []Channel{ChannelOrganisation, ChannelJobs, ChannelStream, ChannelAPI}

// MessageType is defined by the connector protocol schema.
//
// The event types this source owns. Unknown types are rejected by this codec, never
// ignored. This enumeration MUST equal the keys of x-protocol.messages, and is a
// subset of the event_types vocabulary: an event type defined in another schema source
// is decoded by that source.
type MessageType string

const (
	MessageTypeOrganisationCreated MessageType = "organisation.created"
	MessageTypeProjectCreated      MessageType = "project.created"
	MessageTypeProjectUpdated      MessageType = "project.updated"
	MessageTypeProjectArchived     MessageType = "project.archived"
	MessageTypeJobEnqueued         MessageType = "job.enqueued"
	MessageTypeJobSucceeded        MessageType = "job.succeeded"
	MessageTypeJobFailed           MessageType = "job.failed"
)

// MessageTypeValues lists every value in declaration order.
var MessageTypeValues = []MessageType{MessageTypeOrganisationCreated, MessageTypeProjectCreated, MessageTypeProjectUpdated, MessageTypeProjectArchived, MessageTypeJobEnqueued, MessageTypeJobSucceeded, MessageTypeJobFailed}

// ErrorClass is defined by the connector protocol schema.
//
// Stable API error code (docs/API.md section 5, docs/MCP_SPEC.md section 12). This
// enumeration MUST equal x-protocol.error_classes. Adding a code is additive within a
// protocol version, and clients MUST tolerate a code they do not recognise.
type ErrorClass string

const (
	ErrorClassAuthenticationRequired      ErrorClass = "AUTHENTICATION_REQUIRED"
	ErrorClassAuthorisationDenied         ErrorClass = "AUTHORISATION_DENIED"
	ErrorClassProjectContextAmbiguous     ErrorClass = "PROJECT_CONTEXT_AMBIGUOUS"
	ErrorClassProjectContextMismatch      ErrorClass = "PROJECT_CONTEXT_MISMATCH"
	ErrorClassResourceNotFound            ErrorClass = "RESOURCE_NOT_FOUND"
	ErrorClassResourceStale               ErrorClass = "RESOURCE_STALE"
	ErrorClassVersionConflict             ErrorClass = "VERSION_CONFLICT"
	ErrorClassIdempotencyConflict         ErrorClass = "IDEMPOTENCY_CONFLICT"
	ErrorClassValidationFailed            ErrorClass = "VALIDATION_FAILED"
	ErrorClassConnectorOffline            ErrorClass = "CONNECTOR_OFFLINE"
	ErrorClassPublishedServiceUnavailable ErrorClass = "PUBLISHED_SERVICE_UNAVAILABLE"
	ErrorClassBrowserCapacityExhausted    ErrorClass = "BROWSER_CAPACITY_EXHAUSTED"
	ErrorClassBrowserSessionNotActive     ErrorClass = "BROWSER_SESSION_NOT_ACTIVE"
	ErrorClassBrowserCommandTimeout       ErrorClass = "BROWSER_COMMAND_TIMEOUT"
	ErrorClassControlNotOwned             ErrorClass = "CONTROL_NOT_OWNED"
	ErrorClassControlEpochStale           ErrorClass = "CONTROL_EPOCH_STALE"
	ErrorClassPolicyDenied                ErrorClass = "POLICY_DENIED"
	ErrorClassApprovalRequired            ErrorClass = "APPROVAL_REQUIRED"
	ErrorClassEvidenceRequired            ErrorClass = "EVIDENCE_REQUIRED"
	ErrorClassArtefactUploadIncomplete    ErrorClass = "ARTEFACT_UPLOAD_INCOMPLETE"
	ErrorClassUnsupportedCapability       ErrorClass = "UNSUPPORTED_CAPABILITY"
	ErrorClassRateLimited                 ErrorClass = "RATE_LIMITED"
	ErrorClassInternalError               ErrorClass = "INTERNAL_ERROR"
)

// ErrorClassValues lists every value in declaration order.
var ErrorClassValues = []ErrorClass{ErrorClassAuthenticationRequired, ErrorClassAuthorisationDenied, ErrorClassProjectContextAmbiguous, ErrorClassProjectContextMismatch, ErrorClassResourceNotFound, ErrorClassResourceStale, ErrorClassVersionConflict, ErrorClassIdempotencyConflict, ErrorClassValidationFailed, ErrorClassConnectorOffline, ErrorClassPublishedServiceUnavailable, ErrorClassBrowserCapacityExhausted, ErrorClassBrowserSessionNotActive, ErrorClassBrowserCommandTimeout, ErrorClassControlNotOwned, ErrorClassControlEpochStale, ErrorClassPolicyDenied, ErrorClassApprovalRequired, ErrorClassEvidenceRequired, ErrorClassArtefactUploadIncomplete, ErrorClassUnsupportedCapability, ErrorClassRateLimited, ErrorClassInternalError}

// ActorType is defined by the connector protocol schema.
//
// Kind of principal an event is attributed to (docs/EVENTS.md section 5). Actor
// identity MUST never be inferred from display text.
type ActorType string

const (
	ActorTypeHumanUser     ActorType = "human_user"
	ActorTypeAgentSession  ActorType = "agent_session"
	ActorTypeConnector     ActorType = "connector"
	ActorTypeBrowserWorker ActorType = "browser_worker"
	ActorTypeSystem        ActorType = "system"
	ActorTypeIntegration   ActorType = "integration"
)

// ActorTypeValues lists every value in declaration order.
var ActorTypeValues = []ActorType{ActorTypeHumanUser, ActorTypeAgentSession, ActorTypeConnector, ActorTypeBrowserWorker, ActorTypeSystem, ActorTypeIntegration}

// JobKind is defined by the connector protocol schema.
//
// Durable background work the runner understands (docs/ARCHITECTURE.md section 4.8).
// It is an enumeration because an operator reading a failed job needs a name with a
// fixed meaning, not free text a caller chose.
type JobKind string

const (
	JobKindEventOutboxDispatch    JobKind = "event_outbox_dispatch"
	JobKindIdempotencyKeyExpiry   JobKind = "idempotency_key_expiry"
	JobKindPublishedServiceExpiry JobKind = "published_service_expiry"
)

// JobKindValues lists every value in declaration order.
var JobKindValues = []JobKind{JobKindEventOutboxDispatch, JobKindIdempotencyKeyExpiry, JobKindPublishedServiceExpiry}

// JobFailureReason is defined by the connector protocol schema.
//
// Why a job attempt failed. Stable, so a dead-lettered job can be diagnosed from the
// audit trail alone.
type JobFailureReason string

const (
	JobFailureReasonHandlerError      JobFailureReason = "handler_error"
	JobFailureReasonAttemptTimeout    JobFailureReason = "attempt_timeout"
	JobFailureReasonAttemptsExhausted JobFailureReason = "attempts_exhausted"
	JobFailureReasonHandlerUnknown    JobFailureReason = "handler_unknown"
)

// JobFailureReasonValues lists every value in declaration order.
var JobFailureReasonValues = []JobFailureReason{JobFailureReasonHandlerError, JobFailureReasonAttemptTimeout, JobFailureReasonAttemptsExhausted, JobFailureReasonHandlerUnknown}

// ProjectStatus is defined by the connector protocol schema.
//
// Project lifecycle status (docs/DOMAIN_MODEL.md section 5).
type ProjectStatus string

const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusArchived ProjectStatus = "archived"
)

// ProjectStatusValues lists every value in declaration order.
var ProjectStatusValues = []ProjectStatus{ProjectStatusActive, ProjectStatusArchived}

// StreamSubscribeType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamSubscribeType string

const (
	StreamSubscribeTypeStreamSubscribe StreamSubscribeType = "stream.subscribe"
)

// StreamSubscribeTypeValues lists every value in declaration order.
var StreamSubscribeTypeValues = []StreamSubscribeType{StreamSubscribeTypeStreamSubscribe}

// StreamSubscribedType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamSubscribedType string

const (
	StreamSubscribedTypeStreamSubscribed StreamSubscribedType = "stream.subscribed"
)

// StreamSubscribedTypeValues lists every value in declaration order.
var StreamSubscribedTypeValues = []StreamSubscribedType{StreamSubscribedTypeStreamSubscribed}

// StreamRefreshRequiredType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamRefreshRequiredType string

const (
	StreamRefreshRequiredTypeStreamRefreshRequired StreamRefreshRequiredType = "stream.refresh_required"
)

// StreamRefreshRequiredTypeValues lists every value in declaration order.
var StreamRefreshRequiredTypeValues = []StreamRefreshRequiredType{StreamRefreshRequiredTypeStreamRefreshRequired}

// StreamRefreshRequiredReason is defined by the connector protocol schema.
//
// Why a replay was not possible.
type StreamRefreshRequiredReason string

const (
	StreamRefreshRequiredReasonReplayWindowExceeded  StreamRefreshRequiredReason = "replay_window_exceeded"
	StreamRefreshRequiredReasonSequenceAheadOfStream StreamRefreshRequiredReason = "sequence_ahead_of_stream"
	StreamRefreshRequiredReasonReplayLimitExceeded   StreamRefreshRequiredReason = "replay_limit_exceeded"
)

// StreamRefreshRequiredReasonValues lists every value in declaration order.
var StreamRefreshRequiredReasonValues = []StreamRefreshRequiredReason{StreamRefreshRequiredReasonReplayWindowExceeded, StreamRefreshRequiredReasonSequenceAheadOfStream, StreamRefreshRequiredReasonReplayLimitExceeded}

// StreamHeartbeatType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamHeartbeatType string

const (
	StreamHeartbeatTypeStreamHeartbeat StreamHeartbeatType = "stream.heartbeat"
)

// StreamHeartbeatTypeValues lists every value in declaration order.
var StreamHeartbeatTypeValues = []StreamHeartbeatType{StreamHeartbeatTypeStreamHeartbeat}

// StreamErrorType is defined by the connector protocol schema.
//
// Message discriminator.
type StreamErrorType string

const (
	StreamErrorTypeStreamError StreamErrorType = "stream.error"
)

// StreamErrorTypeValues lists every value in declaration order.
var StreamErrorTypeValues = []StreamErrorType{StreamErrorTypeStreamError}

// MessageDirection states which side of the trust boundary sends a message.
type MessageDirection string

const (
	DirectionControlPlaneToSubscriber MessageDirection = "control_plane_to_subscriber"
	DirectionSubscriberToControlPlane MessageDirection = "subscriber_to_control_plane"
)

// MessageDirections records the sender of each message type.
var MessageDirections = map[MessageType]MessageDirection{
	MessageTypeOrganisationCreated: DirectionControlPlaneToSubscriber,
	MessageTypeProjectCreated:      DirectionControlPlaneToSubscriber,
	MessageTypeProjectUpdated:      DirectionControlPlaneToSubscriber,
	MessageTypeProjectArchived:     DirectionControlPlaneToSubscriber,
	MessageTypeJobEnqueued:         DirectionControlPlaneToSubscriber,
	MessageTypeJobSucceeded:        DirectionControlPlaneToSubscriber,
	MessageTypeJobFailed:           DirectionControlPlaneToSubscriber,
}

// MessageChannels records the channel each message type travels on.
var MessageChannels = map[MessageType]Channel{
	MessageTypeOrganisationCreated: ChannelOrganisation,
	MessageTypeProjectCreated:      ChannelOrganisation,
	MessageTypeProjectUpdated:      ChannelOrganisation,
	MessageTypeProjectArchived:     ChannelOrganisation,
	MessageTypeJobEnqueued:         ChannelJobs,
	MessageTypeJobSucceeded:        ChannelJobs,
	MessageTypeJobFailed:           ChannelJobs,
}

// PayloadMaxBytes records the maximum canonical payload size for each message type. A
// payload larger than its bound is rejected.
var PayloadMaxBytes = map[MessageType]int{
	MessageTypeOrganisationCreated: 1024,
	MessageTypeProjectCreated:      1024,
	MessageTypeProjectUpdated:      1024,
	MessageTypeProjectArchived:     512,
	MessageTypeJobEnqueued:         1024,
	MessageTypeJobSucceeded:        1024,
	MessageTypeJobFailed:           1024,
}

// ViolationReason classifies a refused frame. Only some reasons map to a wire error
// class.
type ViolationReason string

const (
	// ReasonFrameTooLarge reports that the encoded event or message exceeded its byte
	// bound. Detected on the raw bytes before deserialisation.
	ReasonFrameTooLarge ViolationReason = "frame_too_large"
	// ReasonMalformedJSON reports that the message was not well-formed JSON, or was
	// truncated.
	ReasonMalformedJSON ViolationReason = "malformed_json"
	// ReasonUnsupportedSchemaVersion reports that schema_version was absent, not an
	// integer, or not a version this build accepts.
	ReasonUnsupportedSchemaVersion ViolationReason = "unsupported_schema_version"
	// ReasonUnknownMessageType reports that type was absent or not an event type this
	// source owns. A consumer that receives an event type it does not know MUST ignore it
	// rather than fail; a producer that writes one through this codec is refused.
	ReasonUnknownMessageType ViolationReason = "unknown_message_type"
	// ReasonPayloadTooLarge reports that the payload exceeded the byte bound declared for
	// its event type.
	ReasonPayloadTooLarge ViolationReason = "payload_too_large"
	// ReasonSchemaViolation reports that the message parsed but did not satisfy the
	// schema for its type.
	ReasonSchemaViolation ViolationReason = "schema_violation"
)

// ViolationErrorClass maps a rejection reason to the connector error class reported
// for it.
var ViolationErrorClass = map[ViolationReason]ErrorClass{
	ReasonFrameTooLarge:            "",
	ReasonMalformedJSON:            "",
	ReasonUnsupportedSchemaVersion: ErrorClassUnsupportedCapability,
	ReasonUnknownMessageType:       ErrorClassUnsupportedCapability,
	ReasonPayloadTooLarge:          "",
	ReasonSchemaViolation:          ErrorClassValidationFailed,
}

// SchemaViolationCode identifies the kind of schema failure.
type SchemaViolationCode string

const (
	SchemaViolationType            SchemaViolationCode = "type"
	SchemaViolationRequired        SchemaViolationCode = "required"
	SchemaViolationForbidden       SchemaViolationCode = "forbidden"
	SchemaViolationUnknownProperty SchemaViolationCode = "unknown_property"
	SchemaViolationEnum            SchemaViolationCode = "enum"
	SchemaViolationConst           SchemaViolationCode = "const"
	SchemaViolationPattern         SchemaViolationCode = "pattern"
	SchemaViolationTooShort        SchemaViolationCode = "too_short"
	SchemaViolationTooLong         SchemaViolationCode = "too_long"
	SchemaViolationTooSmall        SchemaViolationCode = "too_small"
	SchemaViolationTooLarge        SchemaViolationCode = "too_large"
	SchemaViolationTooFewItems     SchemaViolationCode = "too_few_items"
	SchemaViolationTooManyItems    SchemaViolationCode = "too_many_items"
	SchemaViolationDuplicateItems  SchemaViolationCode = "duplicate_items"
	SchemaViolationNotInteger      SchemaViolationCode = "not_integer"
)

// SchemaViolation is one schema failure, located by JSON path.
type SchemaViolation struct {
	Path    string              `json:"path"`
	Code    SchemaViolationCode `json:"code"`
	Message string              `json:"message"`
}

// EventTypes lists the stage 1 event catalogue of docs/EVENTS.md section 7. Event
// names are stable public integration contracts; adding one is additive within a
// schema version, which is why the envelope's type field bounds a name's shape rather
// than enumerating it. A consumer that does not recognise a name MUST ignore the event
// rather than fail.
var EventTypes = []string{"organisation.created", "user.invited", "authentication.login_succeeded", "authentication.login_failed", "session.revoked", "project.created", "project.updated", "project.repository_changed", "project.archived", "connector.enrolled", "connector.connected", "connector.degraded", "connector.disconnected", "connector.revoked", "workspace.observed", "workspace.head_changed", "published_service.requested", "published_service.ready", "published_service.failed", "published_service.expired", "published_service.revoked", "agent_credential.issued", "agent_session.started", "agent_session.waiting", "agent_session.blocked", "agent_session.completed", "agent_session.failed", "agent_session.disconnected", "browser_session.requested", "browser_session.allocated", "browser_session.ready", "browser_session.navigated", "browser_session.paused", "browser_session.resumed", "browser_session.degraded", "browser_session.terminated", "browser_session.failed", "browser.control_requested", "browser.control_transferred", "browser.control_released", "browser.command_rejected", "browser.command_executed", "browser.live_view_started", "browser.live_view_stopped", "screenshot.captured", "artefact.upload_started", "artefact.upload_completed", "artefact.upload_failed", "artefact.access_granted", "artefact.redacted", "artefact.expired", "review.created", "review.named", "review.assigned", "review.claimed", "review.status_changed", "review.accepted", "review.reopened", "review.archived", "finding.created", "finding.annotated", "finding.claimed", "finding.status_changed", "finding.comment_added", "finding.verification_submitted", "finding.verification_accepted", "finding.verification_rejected", "finding.resolved", "finding.reopened", "job.enqueued", "job.succeeded", "job.failed"}

// StreamMessageTypes lists the discriminator values carried by the stream control
// messages of docs/API.md section 18.1. An event envelope carries its own event type
// in the same field, so one member distinguishes every message on the channel.
var StreamMessageTypes = []string{"stream.subscribe", "stream.subscribed", "stream.refresh_required", "stream.heartbeat", "stream.error"}

// IdempotencyHeaders lists the request headers that carry an idempotency key on a
// state-changing HTTP request (docs/API.md section 2, docs/MCP_SPEC.md section 10).
// The key is scoped to actor, operation and project; the header only carries it.
var IdempotencyHeaders = []string{"Idempotency-Key"}

// CorrelationHeaders lists the request headers that carry a correlation identifier
// (docs/ARCHITECTURE.md section 15). The control plane mints one when the caller
// supplies none and returns it as meta.request_id on every response.
var CorrelationHeaders = []string{"X-Request-Id"}

// PaginationParameters lists the query parameters of a paginated collection
// (docs/API.md section 6). The cursor is opaque and MUST NOT be constructed by a
// client.
var PaginationParameters = []string{"cursor", "limit"}

// IdentifierPrefixes records the conventional prefixes of the opaque identifiers this
// protocol carries. They are documentation only: consumers must treat identifiers as
// opaque and validators must not require a prefix.
var IdentifierPrefixes = map[string]string{
	"organisation":      "org_",
	"user":              "usr_",
	"project":           "prj_",
	"environment":       "env_",
	"connector":         "con_",
	"workspace":         "wsp_",
	"published_service": "svc_",
	"agent_credential":  "agc_",
	"agent_session":     "ags_",
	"browser_worker":    "wkr_",
	"browser_session":   "brs_",
	"control_lease":     "lse_",
	"review":            "rev_",
	"finding":           "fin_",
	"comment":           "cmt_",
	"annotation":        "ann_",
	"artefact":          "art_",
	"artefact_grant":    "agr_",
	"verification":      "ver_",
	"event":             "evt_",
	"job":               "job_",
	"request":           "req_",
}

// Identifier is defined by the connector protocol schema.
//
// Opaque durable identifier (docs/DOMAIN_MODEL.md section 3). Consumers MUST treat the
// value as opaque: the schema bounds only its length and character class and never its
// documented prefix, and the value encodes no tenant, no timestamp and no database
// sequence.
type Identifier = string

// Timestamp is defined by the connector protocol schema.
//
// RFC 3339 timestamp in UTC, with a mandatory trailing Z.
type Timestamp = string

// SequenceNumber is defined by the connector protocol schema.
//
// Position in a project's event stream. Monotonically increasing within a project and
// never reused. Global ordering across projects is not guaranteed, and the value is
// not a database row identifier a consumer may depend on.
type SequenceNumber = int64

// Cursor is defined by the connector protocol schema.
//
// Opaque pagination cursor (docs/API.md section 6). It is base64url text without
// padding; its contents are the server's business and a client MUST NOT parse,
// construct or modify one.
type Cursor = string

// Actor is defined by the connector protocol schema.
//
// The principal an event is attributed to (docs/EVENTS.md section 2).
type Actor struct {
	// Principal kind. It is the authoritative part of an actor; display is not.
	Type ActorType `json:"type"`
	// Identifier of the principal, absent for a system actor that has none.
	ID *string `json:"id,omitempty"`
	// Human-readable label for a timeline. It is description and never an authorisation
	// input.
	Display *string `json:"display,omitempty"`
}

// Correlation is defined by the connector protocol schema.
//
// Correlation identifiers (docs/EVENTS.md section 2, docs/ARCHITECTURE.md section 15).
// Every member is an opaque identifier: correlation never carries a header, a body or
// a secret.
type Correlation struct {
	// The API request that caused the event, conventionally prefixed req_.
	RequestID *string `json:"request_id,omitempty"`
	// The event that caused this one, conventionally prefixed evt_.
	CausationEventID *string `json:"causation_event_id,omitempty"`
	// Connector, conventionally prefixed con_.
	ConnectorID *string `json:"connector_id,omitempty"`
	// Environment, conventionally prefixed env_.
	EnvironmentID *string `json:"environment_id,omitempty"`
	// Workspace, conventionally prefixed wsp_.
	WorkspaceID *string `json:"workspace_id,omitempty"`
	// Published service, conventionally prefixed svc_.
	PublishedServiceID *string `json:"published_service_id,omitempty"`
	// Agent session, conventionally prefixed ags_.
	AgentSessionID *string `json:"agent_session_id,omitempty"`
	// Browser session, conventionally prefixed brs_.
	BrowserSessionID *string `json:"browser_session_id,omitempty"`
	// Browser worker, conventionally prefixed wkr_.
	WorkerID *string `json:"worker_id,omitempty"`
	// Artefact, conventionally prefixed art_.
	ArtefactID *string `json:"artefact_id,omitempty"`
	// Review, conventionally prefixed rev_.
	ReviewID *string `json:"review_id,omitempty"`
	// Finding, conventionally prefixed fin_.
	FindingID *string `json:"finding_id,omitempty"`
	// Annotation, conventionally prefixed ann_.
	AnnotationID *string `json:"annotation_id,omitempty"`
	// Durable job, conventionally prefixed job_.
	JobID *string `json:"job_id,omitempty"`
}

// Envelope is defined by the connector protocol schema.
//
// The docs/EVENTS.md section 2 event envelope. Every event names the organisation it
// belongs to, its position in a stream, and the actor that caused it; the payload
// schema is selected by type. project_id is optional because an occurrence can precede
// any project association — a connector enrolment does — and every project-scoped read
// filters on it.
type Envelope struct {
	// Event identifier, conventionally prefixed evt_. Consumers deduplicate on it.
	ID string `json:"id"`
	// Envelope schema version. Stage 1 accepts 1 only; any other value is rejected rather
	// than best-effort parsed.
	SchemaVersion int64 `json:"schema_version"`
	// Monotonic position within the stream.
	Sequence int64 `json:"sequence"`
	// Event type. This codec owns the types in message_type; an event of another type is
	// decoded by the schema source that owns it.
	Type MessageType `json:"type"`
	// When the occurrence happened.
	OccurredAt string `json:"occurred_at"`
	// When the control plane committed the record.
	RecordedAt string `json:"recorded_at"`
	// Owning organisation, conventionally prefixed org_.
	OrganisationID string `json:"organisation_id"`
	// Owning project, conventionally prefixed prj_. Every project-scoped read of this
	// stream filters on it.
	ProjectID *string `json:"project_id,omitempty"`
	// Principal the occurrence is attributed to.
	Actor Actor `json:"actor"`
	// Correlation identifiers.
	Correlation *Correlation `json:"correlation,omitempty"`
}

// OrganisationCreatedPayload is defined by the connector protocol schema.
//
// Payload of organisation.created.
type OrganisationCreatedPayload struct {
	// Mutable human-friendly alias. The identifier is authoritative; this is not.
	Slug string `json:"slug"`
	// Display name.
	Name string `json:"name"`
}

// ProjectCreatedPayload is defined by the connector protocol schema.
//
// Payload of project.created.
type ProjectCreatedPayload struct {
	// Project-scoped alias. Mutable, and never a substitute for the identifier.
	Slug string `json:"slug"`
	// Display name.
	Name string `json:"name"`
}

// ProjectUpdatedPayload is defined by the connector protocol schema.
//
// Payload of project.updated. It names the fields that changed rather than restating
// the record: current state is queryable, and the audit question is what moved.
type ProjectUpdatedPayload struct {
	// Attribute names that changed, in schema order.
	ChangedFields []string `json:"changed_fields"`
}

// ProjectArchivedPayload is defined by the connector protocol schema.
//
// Payload of project.archived. It carries previous and new state, which docs/EVENTS.md
// section 8 requires of a state change.
type ProjectArchivedPayload struct {
	// Status before the change.
	PreviousStatus ProjectStatus `json:"previous_status"`
	// Status after the change.
	NewStatus ProjectStatus `json:"new_status"`
}

// JobEnqueuedPayload is defined by the connector protocol schema.
//
// Payload of job.enqueued.
type JobEnqueuedPayload struct {
	// Job identity, conventionally prefixed job_.
	JobID string `json:"job_id"`
	// Work the job performs.
	Kind JobKind `json:"kind"`
	// Earliest time the runner may claim it.
	RunAfter string `json:"run_after"`
}

// JobSucceededPayload is defined by the connector protocol schema.
//
// Payload of job.succeeded.
type JobSucceededPayload struct {
	// Job identity.
	JobID string `json:"job_id"`
	// Work the job performed.
	Kind JobKind `json:"kind"`
	// Attempts made, including the one that succeeded.
	Attempts int64 `json:"attempts"`
	// Wall-clock duration of the successful attempt.
	DurationMs int64 `json:"duration_ms"`
}

// JobFailedPayload is defined by the connector protocol schema.
//
// Payload of job.failed.
type JobFailedPayload struct {
	// Job identity.
	JobID string `json:"job_id"`
	// Work the job attempted.
	Kind JobKind `json:"kind"`
	// Attempts made, including the one that failed.
	Attempts int64 `json:"attempts"`
	// Stable failure class.
	Reason JobFailureReason `json:"reason"`
	// Whether another attempt is scheduled. Stated rather than inferred, so an operator
	// can tell a retry from a dead job without reading the runner's source.
	Retrying bool `json:"retrying"`
	// When the next attempt becomes claimable. Absent when no attempt will follow.
	NextAttemptAt *string `json:"next_attempt_at,omitempty"`
}

// StreamSubscribe is defined by the connector protocol schema.
//
// Subscription request (docs/API.md section 18.1).
type StreamSubscribe struct {
	// Message discriminator.
	Type StreamSubscribeType `json:"type"`
	// The highest project sequence the client has already applied. Zero means the client
	// holds nothing and wants the stream from its start; a client that has just loaded
	// current state sends the sequence that state was read at.
	LastSequence int64 `json:"last_sequence"`
	// Largest replay the client will accept. A gap larger than this is answered with a
	// refresh instruction rather than a long replay, which is cheaper for both sides than
	// paging through history the client is about to refetch anyway.
	MaxReplay *int64 `json:"max_replay,omitempty"`
}

// StreamSubscribed is defined by the connector protocol schema.
//
// Subscription accepted.
type StreamSubscribed struct {
	// Message discriminator.
	Type StreamSubscribedType `json:"type"`
	// Project the stream belongs to.
	ProjectID string `json:"project_id"`
	// Sequence the stream is at now. Zero when the project has no events yet.
	CurrentSequence int64 `json:"current_sequence"`
	// Oldest sequence still replayable. A client below it receives a refresh instruction
	// instead of a replay.
	EarliestAvailableSequence int64 `json:"earliest_available_sequence"`
	// Whether events between the client's position and current_sequence follow before
	// live delivery begins.
	Replaying bool `json:"replaying"`
}

// StreamRefreshRequired is defined by the connector protocol schema.
//
// The client's position cannot be served from the retained stream (docs/EVENTS.md
// section 10).
type StreamRefreshRequired struct {
	// Message discriminator.
	Type StreamRefreshRequiredType `json:"type"`
	// Why a replay was not possible.
	Reason StreamRefreshRequiredReason `json:"reason"`
	// Sequence the stream is at now. A client refetches state and resumes from it.
	CurrentSequence int64 `json:"current_sequence"`
	// Oldest sequence still replayable.
	EarliestAvailableSequence int64 `json:"earliest_available_sequence"`
}

// StreamHeartbeat is defined by the connector protocol schema.
//
// Liveness on a quiet stream.
type StreamHeartbeat struct {
	// Message discriminator.
	Type StreamHeartbeatType `json:"type"`
	// Sequence the stream is at now.
	CurrentSequence int64 `json:"current_sequence"`
	// When the control plane sent the heartbeat.
	SentAt string `json:"sent_at"`
}

// StreamError is defined by the connector protocol schema.
//
// A refusal on an open subscription.
type StreamError struct {
	// Message discriminator.
	Type StreamErrorType `json:"type"`
	// Stable error code.
	Code ErrorClass `json:"code"`
	// Human-readable explanation. It never carries request data, a credential or a stack
	// trace.
	Message string `json:"message"`
	// Whether repeating the subscription verbatim can succeed. Stated rather than
	// inferred from the code, because the answer is not derivable from the code's shape.
	Retryable bool `json:"retryable"`
}

// ApiErrorDetails is defined by the connector protocol schema.
//
// Code-specific refusal detail (docs/MCP_SPEC.md section 12). Every member is optional
// and the object refuses unknown members, so the detail a caller may rely on is a
// fixed vocabulary rather than whatever a handler happened to attach.
type ApiErrorDetails struct {
	// The version the record actually holds. Carried by VERSION_CONFLICT so a caller can
	// re-read and retry rather than guess.
	CurrentVersion *int64 `json:"current_version,omitempty"`
	// The version the caller supplied. Carried beside current_version so a log line
	// records both halves of the conflict without the caller having to quote its own
	// request back.
	ExpectedVersion *int64 `json:"expected_version,omitempty"`
	// The control epoch that is current. Carried by CONTROL_EPOCH_STALE.
	CurrentEpoch *int64 `json:"current_epoch,omitempty"`
	// Identifiers the caller may name to resolve the ambiguity. Carried by
	// PROJECT_CONTEXT_AMBIGUOUS.
	Candidates []string `json:"candidates,omitempty"`
	// Transitions that are legal from the record's current state. Carried by a refused
	// transition.
	AllowedTransitions []string `json:"allowed_transitions,omitempty"`
	// Evidence the operation needs before it can succeed. Carried by EVIDENCE_REQUIRED.
	RequiredEvidence []string `json:"required_evidence,omitempty"`
	// Captured context the request omitted. Carried by a refusal to store a finding that
	// could not be reproduced later.
	MissingContext []string `json:"missing_context,omitempty"`
	// How long to wait before repeating the request. Carried by RATE_LIMITED and by a
	// duplicate that arrived while the first call was still in flight.
	RetryAfterMs *int64 `json:"retry_after_ms,omitempty"`
	// The request member the refusal is about.
	Field *string `json:"field,omitempty"`
	// Stable sub-reason where one code covers several causes.
	Reason *string `json:"reason,omitempty"`
}

// ApiError is defined by the connector protocol schema.
//
// The refusal itself (docs/API.md section 5).
type ApiError struct {
	// Stable machine-readable code.
	Code ErrorClass `json:"code"`
	// Human-readable explanation. It never carries a credential, request data or a stack
	// trace (docs/SECURITY.md section 18).
	Message string `json:"message"`
	// Code-specific detail.
	Details *ApiErrorDetails `json:"details,omitempty"`
}

// ApiMeta is defined by the connector protocol schema.
//
// Response metadata carried by every API response (docs/API.md sections 5 and 6).
type ApiMeta struct {
	// Correlation identifier for this request, conventionally prefixed req_. It appears
	// on success and on refusal, so a caller can quote one identifier when reporting
	// either.
	RequestID string `json:"request_id"`
	// Cursor for the next page. Absent on the last page and on a response that is not a
	// collection.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// ApiErrorResponse is defined by the connector protocol schema.
//
// The complete refusal body (docs/API.md section 5). A success body is {"data": ...,
// "meta": ...} whose data is endpoint-specific and therefore defined by the endpoint's
// own schema; meta is api_meta in both cases.
type ApiErrorResponse struct {
	// The refusal.
	Error ApiError `json:"error"`
	// Response metadata.
	Meta ApiMeta `json:"meta"`
}

// CursorClaims is defined by the connector protocol schema.
//
// What an opaque pagination cursor encodes. It is defined here so both languages
// encode and decode the same bytes, and never to invite a client to build one: the
// encoded form is base64url text and the API refuses a cursor whose shape it did not
// produce.
type CursorClaims struct {
	// Cursor format version. A cursor of another version is refused rather than guessed
	// at.
	Version int64 `json:"version"`
	// Value of the collection's sort column at the last row of the previous page.
	SortKey string `json:"sort_key"`
	// Identifier of the last row of the previous page, which breaks ties when the sort
	// column repeats.
	ID string `json:"id"`
}

// Payload is implemented by every version 1 message payload. The interface is closed:
// only payloads generated from the schema can satisfy it.
type Payload interface {
	// MessageType reports the envelope type this payload belongs to.
	MessageType() MessageType
	isConnectorPayload()
}

// MessageType reports the envelope type carrying a OrganisationCreatedPayload.
func (OrganisationCreatedPayload) MessageType() MessageType { return MessageTypeOrganisationCreated }

func (OrganisationCreatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectCreatedPayload.
func (ProjectCreatedPayload) MessageType() MessageType { return MessageTypeProjectCreated }

func (ProjectCreatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectUpdatedPayload.
func (ProjectUpdatedPayload) MessageType() MessageType { return MessageTypeProjectUpdated }

func (ProjectUpdatedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ProjectArchivedPayload.
func (ProjectArchivedPayload) MessageType() MessageType { return MessageTypeProjectArchived }

func (ProjectArchivedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobEnqueuedPayload.
func (JobEnqueuedPayload) MessageType() MessageType { return MessageTypeJobEnqueued }

func (JobEnqueuedPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobSucceededPayload.
func (JobSucceededPayload) MessageType() MessageType { return MessageTypeJobSucceeded }

func (JobSucceededPayload) isConnectorPayload() {}

// MessageType reports the envelope type carrying a JobFailedPayload.
func (JobFailedPayload) MessageType() MessageType { return MessageTypeJobFailed }

func (JobFailedPayload) isConnectorPayload() {}

// Frame is a decoded control frame: envelope header plus its typed payload.
type Frame struct {
	Envelope Envelope
	Payload  Payload
}
