// Code generated by packages/protocol/tools/generate.ts from
// schemas/platform/v1.schema.json. DO NOT EDIT.

package platformv1

import "regexp"

var pattern0 = regexp.MustCompile("^[A-Za-z0-9_-]+$")
var pattern1 = regexp.MustCompile("^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,9})?Z$")
var pattern2 = regexp.MustCompile("^[^\\x00-\\x1f]+$")
var pattern3 = regexp.MustCompile("^[a-z0-9][a-z0-9-]*$")
var pattern4 = regexp.MustCompile("^[a-z][a-z0-9_]*$")
var pattern5 = regexp.MustCompile("^[^\\x00]+$")
var pattern6 = regexp.MustCompile("^[A-Za-z0-9_.-]+$")
var pattern7 = regexp.MustCompile("^[a-z][a-z0-9_.]*$")
var pattern8 = regexp.MustCompile("^[a-z][a-z0-9_.\\[\\]]*$")

// validateIdentifier checks opaque durable identifier (docs/DOMAIN_MODEL.md section
// 3). Consumers MUST treat the value as opaque: the schema bounds only its length and
// character class and never its documented prefix, and the value encodes no tenant, no
// timestamp and no database sequence.
func validateIdentifier(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern0})
}

// validateTimestamp checks rFC 3339 timestamp in UTC, with a mandatory trailing Z.
func validateTimestamp(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 20, maxLength: 30, pattern: pattern1})
}

// validateSequenceNumber checks position in a project's event stream. Monotonically
// increasing within a project and never reused. Global ordering across projects is not
// guaranteed, and the value is not a database row identifier a consumer may depend on.
func validateSequenceNumber(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 9007199254740991)
}

// validateCursor checks opaque pagination cursor (docs/API.md section 6). It is
// base64url text without padding; its contents are the server's business and a client
// MUST NOT parse, construct or modify one.
func validateCursor(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 512, pattern: pattern0})
}

// validateMessageType checks the event types this source owns. Unknown types are
// rejected by this codec, never ignored. This enumeration MUST equal the keys of
// x-protocol.messages, and is a subset of the event_types vocabulary: an event type
// defined in another schema source is decoded by that source.
func validateMessageType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"organisation.created", "project.created", "project.updated", "project.archived", "job.enqueued", "job.succeeded", "job.failed"}})
}

// validateErrorClass checks stable API error code (docs/API.md section 5,
// docs/MCP_SPEC.md section 12). This enumeration MUST equal x-protocol.error_classes.
// Adding a code is additive within a protocol version, and clients MUST tolerate a
// code they do not recognise.
func validateErrorClass(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"AUTHENTICATION_REQUIRED", "AUTHORISATION_DENIED", "PROJECT_CONTEXT_AMBIGUOUS", "PROJECT_CONTEXT_MISMATCH", "RESOURCE_NOT_FOUND", "RESOURCE_STALE", "VERSION_CONFLICT", "IDEMPOTENCY_CONFLICT", "VALIDATION_FAILED", "CONNECTOR_OFFLINE", "PUBLISHED_SERVICE_UNAVAILABLE", "BROWSER_CAPACITY_EXHAUSTED", "BROWSER_SESSION_NOT_ACTIVE", "BROWSER_COMMAND_TIMEOUT", "CONTROL_NOT_OWNED", "CONTROL_EPOCH_STALE", "POLICY_DENIED", "APPROVAL_REQUIRED", "EVIDENCE_REQUIRED", "ARTEFACT_UPLOAD_INCOMPLETE", "UNSUPPORTED_CAPABILITY", "RATE_LIMITED", "INTERNAL_ERROR"}})
}

// validateActorType checks kind of principal an event is attributed to (docs/EVENTS.md
// section 5). Actor identity MUST never be inferred from display text.
func validateActorType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"human_user", "agent_session", "connector", "browser_worker", "system", "integration"}})
}

// validateJobKind checks durable background work the runner understands
// (docs/ARCHITECTURE.md section 4.8). It is an enumeration because an operator reading
// a failed job needs a name with a fixed meaning, not free text a caller chose.
func validateJobKind(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"event_outbox_dispatch", "idempotency_key_expiry", "published_service_expiry"}})
}

// validateJobFailureReason checks why a job attempt failed. Stable, so a dead-lettered
// job can be diagnosed from the audit trail alone.
func validateJobFailureReason(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"handler_error", "attempt_timeout", "attempts_exhausted", "handler_unknown"}})
}

// validateProjectStatus checks project lifecycle status (docs/DOMAIN_MODEL.md section
// 5).
func validateProjectStatus(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"active", "archived"}})
}

// validateActorDisplay checks human-readable label for a timeline. It is description
// and never an authorisation input.
func validateActorDisplay(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 200, pattern: pattern2})
}

// validateActor checks a Actor value.
func validateActor(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "id", "display"}, []string{"type"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateActorType(field, path+".type", out)
	}
	if field, present := source["id"]; present {
		validateIdentifier(field, path+".id", out)
	}
	if field, present := source["display"]; present {
		validateActorDisplay(field, path+".display", out)
	}
}

// validateCorrelation checks a Correlation value.
func validateCorrelation(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"request_id", "causation_event_id", "connector_id", "environment_id", "workspace_id", "published_service_id", "agent_session_id", "browser_session_id", "worker_id", "artefact_id", "review_id", "finding_id", "annotation_id", "job_id"}, []string{})
	if !ok {
		return
	}
	if field, present := source["request_id"]; present {
		validateIdentifier(field, path+".request_id", out)
	}
	if field, present := source["causation_event_id"]; present {
		validateIdentifier(field, path+".causation_event_id", out)
	}
	if field, present := source["connector_id"]; present {
		validateIdentifier(field, path+".connector_id", out)
	}
	if field, present := source["environment_id"]; present {
		validateIdentifier(field, path+".environment_id", out)
	}
	if field, present := source["workspace_id"]; present {
		validateIdentifier(field, path+".workspace_id", out)
	}
	if field, present := source["published_service_id"]; present {
		validateIdentifier(field, path+".published_service_id", out)
	}
	if field, present := source["agent_session_id"]; present {
		validateIdentifier(field, path+".agent_session_id", out)
	}
	if field, present := source["browser_session_id"]; present {
		validateIdentifier(field, path+".browser_session_id", out)
	}
	if field, present := source["worker_id"]; present {
		validateIdentifier(field, path+".worker_id", out)
	}
	if field, present := source["artefact_id"]; present {
		validateIdentifier(field, path+".artefact_id", out)
	}
	if field, present := source["review_id"]; present {
		validateIdentifier(field, path+".review_id", out)
	}
	if field, present := source["finding_id"]; present {
		validateIdentifier(field, path+".finding_id", out)
	}
	if field, present := source["annotation_id"]; present {
		validateIdentifier(field, path+".annotation_id", out)
	}
	if field, present := source["job_id"]; present {
		validateIdentifier(field, path+".job_id", out)
	}
}

// validateEnvelopeSchemaVersion checks envelope schema version. Stage 1 accepts 1
// only; any other value is rejected rather than best-effort parsed.
func validateEnvelopeSchemaVersion(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 1)
}

// validateEnvelopePayload checks event payload. Its schema is selected by type.
// Payloads exclude raw secrets, cookies and authorisation headers (docs/EVENTS.md
// section 8); the event is bounded by x-protocol.limits.max_event_bytes and each
// payload by its own x-max-bytes.
func validateEnvelopePayload(value any, path string, out *[]SchemaViolation) {
	checkPlainObject(value, path, out)
}

// validateEnvelope checks a Envelope value.
func validateEnvelope(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"id", "schema_version", "sequence", "type", "occurred_at", "recorded_at", "organisation_id", "project_id", "actor", "correlation", "payload"}, []string{"id", "schema_version", "sequence", "type", "occurred_at", "recorded_at", "organisation_id", "actor", "payload"})
	if !ok {
		return
	}
	if field, present := source["id"]; present {
		validateIdentifier(field, path+".id", out)
	}
	if field, present := source["schema_version"]; present {
		validateEnvelopeSchemaVersion(field, path+".schema_version", out)
	}
	if field, present := source["sequence"]; present {
		validateSequenceNumber(field, path+".sequence", out)
	}
	if field, present := source["type"]; present {
		validateMessageType(field, path+".type", out)
	}
	if field, present := source["occurred_at"]; present {
		validateTimestamp(field, path+".occurred_at", out)
	}
	if field, present := source["recorded_at"]; present {
		validateTimestamp(field, path+".recorded_at", out)
	}
	if field, present := source["organisation_id"]; present {
		validateIdentifier(field, path+".organisation_id", out)
	}
	if field, present := source["project_id"]; present {
		validateIdentifier(field, path+".project_id", out)
	}
	if field, present := source["actor"]; present {
		validateActor(field, path+".actor", out)
	}
	if field, present := source["correlation"]; present {
		validateCorrelation(field, path+".correlation", out)
	}
	if field, present := source["payload"]; present {
		validateEnvelopePayload(field, path+".payload", out)
	}
}

// validateOrganisationCreatedPayloadSlug checks mutable human-friendly alias. The
// identifier is authoritative; this is not.
func validateOrganisationCreatedPayloadSlug(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 63, pattern: pattern3})
}

// validateOrganisationCreatedPayloadName checks display name.
func validateOrganisationCreatedPayloadName(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 200, pattern: pattern2})
}

// validateOrganisationCreatedPayload checks a OrganisationCreatedPayload value.
func validateOrganisationCreatedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"slug", "name"}, []string{"slug", "name"})
	if !ok {
		return
	}
	if field, present := source["slug"]; present {
		validateOrganisationCreatedPayloadSlug(field, path+".slug", out)
	}
	if field, present := source["name"]; present {
		validateOrganisationCreatedPayloadName(field, path+".name", out)
	}
}

// validateProjectCreatedPayloadSlug checks project-scoped alias. Mutable, and never a
// substitute for the identifier.
func validateProjectCreatedPayloadSlug(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 63, pattern: pattern3})
}

// validateProjectCreatedPayloadName checks display name.
func validateProjectCreatedPayloadName(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 200, pattern: pattern2})
}

// validateProjectCreatedPayload checks a ProjectCreatedPayload value.
func validateProjectCreatedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"slug", "name"}, []string{"slug", "name"})
	if !ok {
		return
	}
	if field, present := source["slug"]; present {
		validateProjectCreatedPayloadSlug(field, path+".slug", out)
	}
	if field, present := source["name"]; present {
		validateProjectCreatedPayloadName(field, path+".name", out)
	}
}

// validateProjectUpdatedPayloadChangedFieldsItem checks a generated schema node.
func validateProjectUpdatedPayloadChangedFieldsItem(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern4})
}

// validateProjectUpdatedPayloadChangedFields checks attribute names that changed, in
// schema order.
func validateProjectUpdatedPayloadChangedFields(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 1, 16, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateProjectUpdatedPayloadChangedFieldsItem(item, indexPath(path, index), out)
	}
}

// validateProjectUpdatedPayload checks a ProjectUpdatedPayload value.
func validateProjectUpdatedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"changed_fields"}, []string{"changed_fields"})
	if !ok {
		return
	}
	if field, present := source["changed_fields"]; present {
		validateProjectUpdatedPayloadChangedFields(field, path+".changed_fields", out)
	}
}

// validateProjectArchivedPayload checks a ProjectArchivedPayload value.
func validateProjectArchivedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"previous_status", "new_status"}, []string{"previous_status", "new_status"})
	if !ok {
		return
	}
	if field, present := source["previous_status"]; present {
		validateProjectStatus(field, path+".previous_status", out)
	}
	if field, present := source["new_status"]; present {
		validateProjectStatus(field, path+".new_status", out)
	}
}

// validateJobEnqueuedPayload checks a JobEnqueuedPayload value.
func validateJobEnqueuedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"job_id", "kind", "run_after"}, []string{"job_id", "kind", "run_after"})
	if !ok {
		return
	}
	if field, present := source["job_id"]; present {
		validateIdentifier(field, path+".job_id", out)
	}
	if field, present := source["kind"]; present {
		validateJobKind(field, path+".kind", out)
	}
	if field, present := source["run_after"]; present {
		validateTimestamp(field, path+".run_after", out)
	}
}

// validateJobSucceededPayloadAttempts checks attempts made, including the one that
// succeeded.
func validateJobSucceededPayloadAttempts(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 1000)
}

// validateJobSucceededPayloadDurationMs checks wall-clock duration of the successful
// attempt.
func validateJobSucceededPayloadDurationMs(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 86400000)
}

// validateJobSucceededPayload checks a JobSucceededPayload value.
func validateJobSucceededPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"job_id", "kind", "attempts", "duration_ms"}, []string{"job_id", "kind", "attempts", "duration_ms"})
	if !ok {
		return
	}
	if field, present := source["job_id"]; present {
		validateIdentifier(field, path+".job_id", out)
	}
	if field, present := source["kind"]; present {
		validateJobKind(field, path+".kind", out)
	}
	if field, present := source["attempts"]; present {
		validateJobSucceededPayloadAttempts(field, path+".attempts", out)
	}
	if field, present := source["duration_ms"]; present {
		validateJobSucceededPayloadDurationMs(field, path+".duration_ms", out)
	}
}

// validateJobFailedPayloadAttempts checks attempts made, including the one that
// failed.
func validateJobFailedPayloadAttempts(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 1000)
}

// validateJobFailedPayloadRetrying checks whether another attempt is scheduled. Stated
// rather than inferred, so an operator can tell a retry from a dead job without
// reading the runner's source.
func validateJobFailedPayloadRetrying(value any, path string, out *[]SchemaViolation) {
	checkBoolean(value, path, out)
}

// validateJobFailedPayload checks a JobFailedPayload value.
func validateJobFailedPayload(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"job_id", "kind", "attempts", "reason", "retrying", "next_attempt_at"}, []string{"job_id", "kind", "attempts", "reason", "retrying"})
	if !ok {
		return
	}
	if field, present := source["job_id"]; present {
		validateIdentifier(field, path+".job_id", out)
	}
	if field, present := source["kind"]; present {
		validateJobKind(field, path+".kind", out)
	}
	if field, present := source["attempts"]; present {
		validateJobFailedPayloadAttempts(field, path+".attempts", out)
	}
	if field, present := source["reason"]; present {
		validateJobFailureReason(field, path+".reason", out)
	}
	if field, present := source["retrying"]; present {
		validateJobFailedPayloadRetrying(field, path+".retrying", out)
	}
	if field, present := source["next_attempt_at"]; present {
		validateTimestamp(field, path+".next_attempt_at", out)
	}
}

// validateStreamSubscribeType checks message discriminator.
func validateStreamSubscribeType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"stream.subscribe"}})
}

// validateStreamSubscribeLastSequence checks the highest project sequence the client
// has already applied. Zero means the client holds nothing and wants the stream from
// its start; a client that has just loaded current state sends the sequence that state
// was read at.
func validateStreamSubscribeLastSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamSubscribeMaxReplay checks largest replay the client will accept. A gap
// larger than this is answered with a refresh instruction rather than a long replay,
// which is cheaper for both sides than paging through history the client is about to
// refetch anyway.
func validateStreamSubscribeMaxReplay(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 10000)
}

// validateStreamSubscribe checks a StreamSubscribe value.
func validateStreamSubscribe(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "last_sequence", "max_replay"}, []string{"type", "last_sequence"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateStreamSubscribeType(field, path+".type", out)
	}
	if field, present := source["last_sequence"]; present {
		validateStreamSubscribeLastSequence(field, path+".last_sequence", out)
	}
	if field, present := source["max_replay"]; present {
		validateStreamSubscribeMaxReplay(field, path+".max_replay", out)
	}
}

// validateStreamSubscribedType checks message discriminator.
func validateStreamSubscribedType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"stream.subscribed"}})
}

// validateStreamSubscribedCurrentSequence checks sequence the stream is at now. Zero
// when the project has no events yet.
func validateStreamSubscribedCurrentSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamSubscribedEarliestAvailableSequence checks oldest sequence still
// replayable. A client below it receives a refresh instruction instead of a replay.
func validateStreamSubscribedEarliestAvailableSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamSubscribedReplaying checks whether events between the client's
// position and current_sequence follow before live delivery begins.
func validateStreamSubscribedReplaying(value any, path string, out *[]SchemaViolation) {
	checkBoolean(value, path, out)
}

// validateStreamSubscribed checks a StreamSubscribed value.
func validateStreamSubscribed(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "project_id", "current_sequence", "earliest_available_sequence", "replaying"}, []string{"type", "project_id", "current_sequence", "earliest_available_sequence", "replaying"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateStreamSubscribedType(field, path+".type", out)
	}
	if field, present := source["project_id"]; present {
		validateIdentifier(field, path+".project_id", out)
	}
	if field, present := source["current_sequence"]; present {
		validateStreamSubscribedCurrentSequence(field, path+".current_sequence", out)
	}
	if field, present := source["earliest_available_sequence"]; present {
		validateStreamSubscribedEarliestAvailableSequence(field, path+".earliest_available_sequence", out)
	}
	if field, present := source["replaying"]; present {
		validateStreamSubscribedReplaying(field, path+".replaying", out)
	}
}

// validateStreamRefreshRequiredType checks message discriminator.
func validateStreamRefreshRequiredType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"stream.refresh_required"}})
}

// validateStreamRefreshRequiredReason checks why a replay was not possible.
func validateStreamRefreshRequiredReason(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"replay_window_exceeded", "sequence_ahead_of_stream", "replay_limit_exceeded"}})
}

// validateStreamRefreshRequiredCurrentSequence checks sequence the stream is at now. A
// client refetches state and resumes from it.
func validateStreamRefreshRequiredCurrentSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamRefreshRequiredEarliestAvailableSequence checks oldest sequence still
// replayable.
func validateStreamRefreshRequiredEarliestAvailableSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamRefreshRequired checks a StreamRefreshRequired value.
func validateStreamRefreshRequired(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "reason", "current_sequence", "earliest_available_sequence"}, []string{"type", "reason", "current_sequence", "earliest_available_sequence"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateStreamRefreshRequiredType(field, path+".type", out)
	}
	if field, present := source["reason"]; present {
		validateStreamRefreshRequiredReason(field, path+".reason", out)
	}
	if field, present := source["current_sequence"]; present {
		validateStreamRefreshRequiredCurrentSequence(field, path+".current_sequence", out)
	}
	if field, present := source["earliest_available_sequence"]; present {
		validateStreamRefreshRequiredEarliestAvailableSequence(field, path+".earliest_available_sequence", out)
	}
}

// validateStreamHeartbeatType checks message discriminator.
func validateStreamHeartbeatType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"stream.heartbeat"}})
}

// validateStreamHeartbeatCurrentSequence checks sequence the stream is at now.
func validateStreamHeartbeatCurrentSequence(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateStreamHeartbeat checks a StreamHeartbeat value.
func validateStreamHeartbeat(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "current_sequence", "sent_at"}, []string{"type", "current_sequence", "sent_at"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateStreamHeartbeatType(field, path+".type", out)
	}
	if field, present := source["current_sequence"]; present {
		validateStreamHeartbeatCurrentSequence(field, path+".current_sequence", out)
	}
	if field, present := source["sent_at"]; present {
		validateTimestamp(field, path+".sent_at", out)
	}
}

// validateStreamErrorType checks message discriminator.
func validateStreamErrorType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"stream.error"}})
}

// validateStreamErrorMessage checks human-readable explanation. It never carries
// request data, a credential or a stack trace.
func validateStreamErrorMessage(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 1024, pattern: pattern5})
}

// validateStreamErrorRetryable checks whether repeating the subscription verbatim can
// succeed. Stated rather than inferred from the code, because the answer is not
// derivable from the code's shape.
func validateStreamErrorRetryable(value any, path string, out *[]SchemaViolation) {
	checkBoolean(value, path, out)
}

// validateStreamError checks a StreamError value.
func validateStreamError(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"type", "code", "message", "retryable"}, []string{"type", "code", "message", "retryable"})
	if !ok {
		return
	}
	if field, present := source["type"]; present {
		validateStreamErrorType(field, path+".type", out)
	}
	if field, present := source["code"]; present {
		validateErrorClass(field, path+".code", out)
	}
	if field, present := source["message"]; present {
		validateStreamErrorMessage(field, path+".message", out)
	}
	if field, present := source["retryable"]; present {
		validateStreamErrorRetryable(field, path+".retryable", out)
	}
}

// validateApiErrorDetailsCurrentVersion checks the version the record actually holds.
// Carried by VERSION_CONFLICT so a caller can re-read and retry rather than guess.
func validateApiErrorDetailsCurrentVersion(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateApiErrorDetailsExpectedVersion checks the version the caller supplied.
// Carried beside current_version so a log line records both halves of the conflict
// without the caller having to quote its own request back.
func validateApiErrorDetailsExpectedVersion(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateApiErrorDetailsCurrentEpoch checks the control epoch that is current.
// Carried by CONTROL_EPOCH_STALE.
func validateApiErrorDetailsCurrentEpoch(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateApiErrorDetailsCandidates checks identifiers the caller may name to resolve
// the ambiguity. Carried by PROJECT_CONTEXT_AMBIGUOUS.
func validateApiErrorDetailsCandidates(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 1, 50, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateIdentifier(item, indexPath(path, index), out)
	}
}

// validateApiErrorDetailsAllowedTransitionsItem checks a generated schema node.
func validateApiErrorDetailsAllowedTransitionsItem(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern6})
}

// validateApiErrorDetailsAllowedTransitions checks transitions that are legal from the
// record's current state. Carried by a refused transition.
func validateApiErrorDetailsAllowedTransitions(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 0, 50, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateApiErrorDetailsAllowedTransitionsItem(item, indexPath(path, index), out)
	}
}

// validateApiErrorDetailsRequiredEvidenceItem checks a generated schema node.
func validateApiErrorDetailsRequiredEvidenceItem(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern4})
}

// validateApiErrorDetailsRequiredEvidence checks evidence the operation needs before
// it can succeed. Carried by EVIDENCE_REQUIRED.
func validateApiErrorDetailsRequiredEvidence(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 1, 50, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateApiErrorDetailsRequiredEvidenceItem(item, indexPath(path, index), out)
	}
}

// validateApiErrorDetailsMissingContextItem checks a generated schema node.
func validateApiErrorDetailsMissingContextItem(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern7})
}

// validateApiErrorDetailsMissingContext checks captured context the request omitted.
// Carried by a refusal to store a finding that could not be reproduced later.
func validateApiErrorDetailsMissingContext(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 1, 50, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateApiErrorDetailsMissingContextItem(item, indexPath(path, index), out)
	}
}

// validateApiErrorDetailsRetryAfterMs checks how long to wait before repeating the
// request. Carried by RATE_LIMITED and by a duplicate that arrived while the first
// call was still in flight.
func validateApiErrorDetailsRetryAfterMs(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 86400000)
}

// validateApiErrorDetailsField checks the request member the refusal is about.
func validateApiErrorDetailsField(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 128, pattern: pattern8})
}

// validateApiErrorDetailsReason checks stable sub-reason where one code covers several
// causes.
func validateApiErrorDetailsReason(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern4})
}

// validateAPIErrorDetails checks a ApiErrorDetails value.
func validateAPIErrorDetails(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"current_version", "expected_version", "current_epoch", "candidates", "allowed_transitions", "required_evidence", "missing_context", "retry_after_ms", "field", "reason"}, []string{})
	if !ok {
		return
	}
	if field, present := source["current_version"]; present {
		validateApiErrorDetailsCurrentVersion(field, path+".current_version", out)
	}
	if field, present := source["expected_version"]; present {
		validateApiErrorDetailsExpectedVersion(field, path+".expected_version", out)
	}
	if field, present := source["current_epoch"]; present {
		validateApiErrorDetailsCurrentEpoch(field, path+".current_epoch", out)
	}
	if field, present := source["candidates"]; present {
		validateApiErrorDetailsCandidates(field, path+".candidates", out)
	}
	if field, present := source["allowed_transitions"]; present {
		validateApiErrorDetailsAllowedTransitions(field, path+".allowed_transitions", out)
	}
	if field, present := source["required_evidence"]; present {
		validateApiErrorDetailsRequiredEvidence(field, path+".required_evidence", out)
	}
	if field, present := source["missing_context"]; present {
		validateApiErrorDetailsMissingContext(field, path+".missing_context", out)
	}
	if field, present := source["retry_after_ms"]; present {
		validateApiErrorDetailsRetryAfterMs(field, path+".retry_after_ms", out)
	}
	if field, present := source["field"]; present {
		validateApiErrorDetailsField(field, path+".field", out)
	}
	if field, present := source["reason"]; present {
		validateApiErrorDetailsReason(field, path+".reason", out)
	}
}

// validateApiErrorMessage checks human-readable explanation. It never carries a
// credential, request data or a stack trace (docs/SECURITY.md section 18).
func validateApiErrorMessage(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 1024, pattern: pattern5})
}

// validateAPIError checks a ApiError value.
func validateAPIError(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"code", "message", "details"}, []string{"code", "message"})
	if !ok {
		return
	}
	if field, present := source["code"]; present {
		validateErrorClass(field, path+".code", out)
	}
	if field, present := source["message"]; present {
		validateApiErrorMessage(field, path+".message", out)
	}
	if field, present := source["details"]; present {
		validateAPIErrorDetails(field, path+".details", out)
	}
}

// validateAPIMeta checks a ApiMeta value.
func validateAPIMeta(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"request_id", "next_cursor"}, []string{"request_id"})
	if !ok {
		return
	}
	if field, present := source["request_id"]; present {
		validateIdentifier(field, path+".request_id", out)
	}
	if field, present := source["next_cursor"]; present {
		validateCursor(field, path+".next_cursor", out)
	}
}

// validateAPIErrorResponse checks a ApiErrorResponse value.
func validateAPIErrorResponse(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"error", "meta"}, []string{"error", "meta"})
	if !ok {
		return
	}
	if field, present := source["error"]; present {
		validateAPIError(field, path+".error", out)
	}
	if field, present := source["meta"]; present {
		validateAPIMeta(field, path+".meta", out)
	}
}

// validateCursorClaimsVersion checks cursor format version. A cursor of another
// version is refused rather than guessed at.
func validateCursorClaimsVersion(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 1)
}

// validateCursorClaimsSortKey checks value of the collection's sort column at the last
// row of the previous page.
func validateCursorClaimsSortKey(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 128, pattern: pattern5})
}

// validateCursorClaims checks a CursorClaims value.
func validateCursorClaims(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"version", "sort_key", "id"}, []string{"version", "sort_key", "id"})
	if !ok {
		return
	}
	if field, present := source["version"]; present {
		validateCursorClaimsVersion(field, path+".version", out)
	}
	if field, present := source["sort_key"]; present {
		validateCursorClaimsSortKey(field, path+".sort_key", out)
	}
	if field, present := source["id"]; present {
		validateIdentifier(field, path+".id", out)
	}
}
