/**
 * Connector-module configuration (`docs/CONFIGURATION.md` §1: validate at
 * startup, fail clearly, publish defaults).
 */

import {
  ConfigurationError,
  optionalString,
  readInteger,
  readList,
  type Environment,
} from "../../config.ts";

/** Channel paths on the connector listener. */
export const ENROLMENT_PATH = "/connector/v1/enrol";
export const CONTROL_PATH = "/connector/v1/control";
export const DATA_PATH = "/connector/v1/data";

export interface ConnectorModuleConfig {
  /**
   * The organisation this control plane enrols connectors into. Stage 0 is
   * single-organisation, so an enrolment token scoped to another organisation
   * is refused rather than silently honoured.
   */
  readonly organisationId: string;
  readonly organisationName: string;
  /** Port for the mutually authenticated connector listener. */
  readonly listenPort: number;
  readonly listenHost: string;
  /** Host names and addresses the listener certificate is valid for. */
  readonly tlsHosts: readonly string[];
  /** Operator-supplied listener certificate, if TLS is not terminated here. */
  readonly tlsCertificateFile: string | undefined;
  readonly tlsPrivateKeyFile: string | undefined;
  /**
   * Public `wss://host:port` base the registration response advertises. It may
   * differ from the listen address when a reverse proxy sits in front.
   */
  readonly publicUrl: string;
  /**
   * Where a connector opens its multiplexed data channel.
   *
   * This is the tunnel gateway, not the control plane: `docs/ARCHITECTURE.md`
   * §4.6 puts data-channel termination in the gateway, and the control plane
   * never carries tunnelled bytes. It is advertised in the registration
   * response so that a connector learns both endpoints at enrolment
   * (`docs/CONNECTOR_PROTOCOL.md` §4.3).
   */
  readonly dataUrl: string;
  /** Lifetime of an issued device identity. Identities are bounded in time. */
  readonly identityTtlDays: number;
  /** Expiry applied to an enrolment token when the request names none. */
  readonly defaultTokenTtlSeconds: number;
  /** Heartbeat interval the connector is expected to keep to. */
  readonly heartbeatIntervalSeconds: number;
  /** Silence after which an ACTIVE connector becomes DEGRADED. */
  readonly degradedAfterSeconds: number;
  /** Silence after which a DEGRADED connector becomes DISCONNECTED. */
  readonly disconnectedAfterSeconds: number;
  /** How often the heartbeat monitor sweeps. */
  readonly monitorIntervalSeconds: number;
  /**
   * Connector release below which a reconnect is classified `upgrade_required`
   * (`docs/CONNECTOR_PROTOCOL.md` §19). The connector reports the classification
   * and stops; Stage 0 does not self-update. The default accepts every build,
   * because refusing a connector is an operator decision rather than a default.
   */
  readonly minimumConnectorVersion: string;
  /**
   * Connector release below which an upgrade is recommended. The connector logs
   * the recommendation and keeps running.
   */
  readonly recommendedConnectorVersion: string;
  /**
   * Where the connector certificate authority's **certificate** is written at
   * startup, for the tunnel gateway to trust connector identities with
   * (ADR-0014, `docs/CONNECTOR_PROTOCOL.md` §4.2).
   *
   * The authority is generated by this process on first start and kept in the
   * database, so no installer can produce it in advance; the tunnel gateway
   * reads a file and refuses to start without one. Exporting it here is what
   * makes `docker compose up -d` a complete installation rather than one that
   * needs an operator to fetch a certificate and restart a container.
   *
   * The private key is never written. Signing happens in this process, and a CA
   * key on a shared volume would be a CA key one container away from the
   * component that terminates untrusted connections.
   */
  readonly certificateAuthorityExportFile: string | undefined;
}

/** Accepts the schema's `semantic_version` shape and nothing looser. */
const VERSION_PATTERN = /^[0-9A-Za-z][0-9A-Za-z.+-]*$/u;

function readVersion(environment: Environment, name: string, fallback: string): string {
  const value = optionalString(environment, name);
  if (value === undefined) return fallback;
  if (!VERSION_PATTERN.test(value)) {
    throw new ConfigurationError(
      `${name} must be a connector release version such as 0.1.0, found ${JSON.stringify(value)}`,
    );
  }
  return value;
}

export function loadConnectorModuleConfig(environment: Environment = process.env): ConnectorModuleConfig {
  const listenPort = readInteger(environment, "REVIEWPLANE_CONNECTOR_PORT", 8443, {
    minimum: 0,
    maximum: 65535,
  });
  const listenHost = optionalString(environment, "REVIEWPLANE_CONNECTOR_HOST") ?? "0.0.0.0";
  const tlsHosts = readList(environment, "REVIEWPLANE_CONNECTOR_TLS_HOSTS", ["localhost", "127.0.0.1"]);

  const certificateFile = optionalString(environment, "REVIEWPLANE_CONNECTOR_TLS_CERT_FILE");
  const privateKeyFile = optionalString(environment, "REVIEWPLANE_CONNECTOR_TLS_KEY_FILE");
  if ((certificateFile === undefined) !== (privateKeyFile === undefined)) {
    throw new ConfigurationError(
      "REVIEWPLANE_CONNECTOR_TLS_CERT_FILE and REVIEWPLANE_CONNECTOR_TLS_KEY_FILE must be set together",
    );
  }

  const publicUrl = optionalString(environment, "REVIEWPLANE_CONNECTOR_PUBLIC_URL");
  const dataUrl = optionalString(environment, "REVIEWPLANE_CONNECTOR_DATA_URL");
  if (dataUrl !== undefined && !dataUrl.startsWith("wss://")) {
    throw new ConfigurationError(
      `REVIEWPLANE_CONNECTOR_DATA_URL must use the wss scheme, found ${JSON.stringify(dataUrl)}`,
    );
  }
  if (publicUrl !== undefined && !publicUrl.startsWith("wss://")) {
    throw new ConfigurationError(
      `REVIEWPLANE_CONNECTOR_PUBLIC_URL must use the wss scheme, found ${JSON.stringify(publicUrl)}`,
    );
  }

  const degradedAfterSeconds = readInteger(environment, "REVIEWPLANE_CONNECTOR_DEGRADED_AFTER_SECONDS", 45, {
    minimum: 1,
    maximum: 86_400,
  });
  const disconnectedAfterSeconds = readInteger(
    environment,
    "REVIEWPLANE_CONNECTOR_DISCONNECTED_AFTER_SECONDS",
    90,
    { minimum: 1, maximum: 86_400 },
  );
  if (disconnectedAfterSeconds <= degradedAfterSeconds) {
    throw new ConfigurationError(
      "REVIEWPLANE_CONNECTOR_DISCONNECTED_AFTER_SECONDS must be greater than " +
        "REVIEWPLANE_CONNECTOR_DEGRADED_AFTER_SECONDS",
    );
  }

  return {
    organisationId: optionalString(environment, "REVIEWPLANE_ORGANISATION_ID") ?? "org_default",
    organisationName: optionalString(environment, "REVIEWPLANE_ORGANISATION_NAME") ?? "ReviewPlane",
    listenPort,
    listenHost,
    tlsHosts,
    tlsCertificateFile: certificateFile,
    tlsPrivateKeyFile: privateKeyFile,
    publicUrl: publicUrl ?? `wss://${tlsHosts[0] ?? "localhost"}:${listenPort}`,
    // The default keeps a single-host development stack working, where the
    // control plane also terminates the data channel. A real deployment names
    // the tunnel gateway.
    dataUrl: dataUrl ?? `${publicUrl ?? `wss://${tlsHosts[0] ?? "localhost"}:${listenPort}`}${DATA_PATH}`,
    identityTtlDays: readInteger(environment, "REVIEWPLANE_CONNECTOR_IDENTITY_TTL_DAYS", 365, {
      minimum: 1,
      maximum: 3650,
    }),
    defaultTokenTtlSeconds: readInteger(environment, "REVIEWPLANE_ENROLMENT_TOKEN_TTL_SECONDS", 3600, {
      minimum: 60,
      maximum: 604_800,
    }),
    heartbeatIntervalSeconds: readInteger(
      environment,
      "REVIEWPLANE_CONNECTOR_HEARTBEAT_INTERVAL_SECONDS",
      15,
      { minimum: 1, maximum: 300 },
    ),
    degradedAfterSeconds,
    disconnectedAfterSeconds,
    monitorIntervalSeconds: readInteger(environment, "REVIEWPLANE_CONNECTOR_MONITOR_INTERVAL_SECONDS", 5, {
      minimum: 1,
      maximum: 3600,
    }),
    minimumConnectorVersion: readVersion(environment, "REVIEWPLANE_CONNECTOR_MINIMUM_VERSION", "0.0.0"),
    recommendedConnectorVersion: readVersion(
      environment,
      "REVIEWPLANE_CONNECTOR_RECOMMENDED_VERSION",
      "0.0.0",
    ),
    certificateAuthorityExportFile: optionalString(
      environment,
      "REVIEWPLANE_CONNECTOR_CA_EXPORT_FILE",
    ),
  };
}
