// Code generated by packages/protocol/tools/generate.ts from
// schemas/connector/v1.schema.json. DO NOT EDIT.

package connectorv1

// Decoders build typed values from an already validated JSON tree. Calling a decoder
// on a value that has not passed its validator is a programming error; the frame entry
// points in frame.go always validate first.

// DecodeEnvelope builds a Envelope from a validated tree.
func DecodeEnvelope(value any) Envelope {
	source, _ := value.(map[string]any)
	var out Envelope
	out.ProtocolVersion = decodeInt(source["protocol_version"])
	out.MessageID = decodeString(source["message_id"])
	out.Type = MessageType(decodeString(source["type"]))
	out.SentAt = decodeString(source["sent_at"])
	if field, present := source["connector_id"]; present {
		decoded := decodeString(field)
		out.ConnectorID = &decoded
	}
	if field, present := source["correlation_id"]; present {
		decoded := decodeString(field)
		out.CorrelationID = &decoded
	}
	return out
}

// DecodeEnvironmentDescriptor builds a EnvironmentDescriptor from a validated tree.
func DecodeEnvironmentDescriptor(value any) EnvironmentDescriptor {
	source, _ := value.(map[string]any)
	var out EnvironmentDescriptor
	out.Name = decodeString(source["name"])
	out.Platform = decodeString(source["platform"])
	out.Architecture = decodeString(source["architecture"])
	if field, present := source["labels"]; present {
		out.Labels = decodeSlice(field, func(item any) string { return decodeString(item) })
	}
	return out
}

// DecodeConnectorDescriptor builds a ConnectorDescriptor from a validated tree.
func DecodeConnectorDescriptor(value any) ConnectorDescriptor {
	source, _ := value.(map[string]any)
	var out ConnectorDescriptor
	out.Version = decodeString(source["version"])
	out.Capabilities = decodeSlice(source["capabilities"], func(item any) string { return decodeString(item) })
	return out
}

// DecodeRegistrationRequest builds a RegistrationRequest from a validated tree.
func DecodeRegistrationRequest(value any) RegistrationRequest {
	source, _ := value.(map[string]any)
	var out RegistrationRequest
	out.EnrolmentToken = SensitiveString(decodeString(source["enrolment_token"]))
	out.PublicKey = decodeString(source["public_key"])
	out.Environment = DecodeEnvironmentDescriptor(source["environment"])
	out.Connector = DecodeConnectorDescriptor(source["connector"])
	return out
}

// DecodeSignedIdentity builds a SignedIdentity from a validated tree.
func DecodeSignedIdentity(value any) SignedIdentity {
	source, _ := value.(map[string]any)
	var out SignedIdentity
	out.Certificate = decodeString(source["certificate"])
	out.CertificateFingerprint = decodeString(source["certificate_fingerprint"])
	out.ExpiresAt = decodeString(source["expires_at"])
	return out
}

// DecodeControlPlaneEndpoints builds a ControlPlaneEndpoints from a validated tree.
func DecodeControlPlaneEndpoints(value any) ControlPlaneEndpoints {
	source, _ := value.(map[string]any)
	var out ControlPlaneEndpoints
	out.ControlURL = decodeString(source["control_url"])
	out.DataURL = decodeString(source["data_url"])
	return out
}

// DecodeRegistrationResponse builds a RegistrationResponse from a validated tree.
func DecodeRegistrationResponse(value any) RegistrationResponse {
	source, _ := value.(map[string]any)
	var out RegistrationResponse
	out.ConnectorID = decodeString(source["connector_id"])
	out.SignedIdentity = DecodeSignedIdentity(source["signed_identity"])
	out.ControlPlaneEndpoints = DecodeControlPlaneEndpoints(source["control_plane_endpoints"])
	out.PolicyDigest = decodeString(source["policy_digest"])
	return out
}

// DecodeResourceSummary builds a ResourceSummary from a validated tree.
func DecodeResourceSummary(value any) ResourceSummary {
	source, _ := value.(map[string]any)
	var out ResourceSummary
	if field, present := source["load"]; present {
		decoded := decodeFloat(field)
		out.Load = &decoded
	}
	if field, present := source["memory_available_bytes"]; present {
		decoded := decodeInt(field)
		out.MemoryAvailableBytes = &decoded
	}
	return out
}

// DecodeHeartbeat builds a Heartbeat from a validated tree.
func DecodeHeartbeat(value any) Heartbeat {
	source, _ := value.(map[string]any)
	var out Heartbeat
	out.Status = HeartbeatStatus(decodeString(source["status"]))
	out.UptimeSeconds = decodeInt(source["uptime_seconds"])
	out.Version = decodeString(source["version"])
	out.ActiveRoutes = decodeInt(source["active_routes"])
	out.ActiveStreams = decodeInt(source["active_streams"])
	if field, present := source["resource_summary"]; present {
		decoded := DecodeResourceSummary(field)
		out.ResourceSummary = &decoded
	}
	return out
}

// DecodeRoutePublish builds a RoutePublish from a validated tree.
func DecodeRoutePublish(value any) RoutePublish {
	source, _ := value.(map[string]any)
	var out RoutePublish
	out.RouteID = decodeString(source["route_id"])
	out.ProjectID = decodeString(source["project_id"])
	out.WorkspaceID = decodeString(source["workspace_id"])
	out.LocalHost = decodeString(source["local_host"])
	out.LocalPort = decodeInt(source["local_port"])
	out.Protocol = DestinationProtocol(decodeString(source["protocol"]))
	out.ExpiresAt = decodeString(source["expires_at"])
	out.AllowedBrowserSessionIDs = decodeSlice(source["allowed_browser_session_ids"], func(item any) string { return decodeString(item) })
	return out
}

// DecodeRoutePublishAck builds a RoutePublishAck from a validated tree.
func DecodeRoutePublishAck(value any) RoutePublishAck {
	source, _ := value.(map[string]any)
	var out RoutePublishAck
	out.RouteID = decodeString(source["route_id"])
	out.Status = RoutePublishAckStatus(decodeString(source["status"]))
	if field, present := source["observed_destination"]; present {
		decoded := decodeString(field)
		out.ObservedDestination = &decoded
	}
	if field, present := source["error_class"]; present {
		decoded := ErrorClass(decodeString(field))
		out.ErrorClass = &decoded
	}
	return out
}

// DecodeDataStreamHeader builds a DataStreamHeader from a validated tree.
func DecodeDataStreamHeader(value any) DataStreamHeader {
	source, _ := value.(map[string]any)
	var out DataStreamHeader
	out.RouteID = decodeString(source["route_id"])
	out.BrowserSessionID = decodeString(source["browser_session_id"])
	out.SessionCapability = SensitiveString(decodeString(source["session_capability"]))
	out.StreamID = decodeString(source["stream_id"])
	out.DestinationProtocol = DestinationProtocol(decodeString(source["destination_protocol"]))
	out.Deadline = decodeString(source["deadline"])
	if field, present := source["stream_mode"]; present {
		decoded := StreamMode(decodeString(field))
		out.StreamMode = &decoded
	}
	return out
}

// DecodeReconnectRoute builds a ReconnectRoute from a validated tree.
func DecodeReconnectRoute(value any) ReconnectRoute {
	source, _ := value.(map[string]any)
	var out ReconnectRoute
	out.RouteID = decodeString(source["route_id"])
	out.ProjectID = decodeString(source["project_id"])
	out.WorkspaceID = decodeString(source["workspace_id"])
	out.ObservedDestination = decodeString(source["observed_destination"])
	out.ExpiresAt = decodeString(source["expires_at"])
	return out
}

// DecodeReconnectStream builds a ReconnectStream from a validated tree.
func DecodeReconnectStream(value any) ReconnectStream {
	source, _ := value.(map[string]any)
	var out ReconnectStream
	out.StreamID = decodeString(source["stream_id"])
	out.RouteID = decodeString(source["route_id"])
	out.BrowserSessionID = decodeString(source["browser_session_id"])
	out.Deadline = decodeString(source["deadline"])
	return out
}

// DecodeWorkspaceHead builds a WorkspaceHead from a validated tree.
func DecodeWorkspaceHead(value any) WorkspaceHead {
	source, _ := value.(map[string]any)
	var out WorkspaceHead
	out.WorkspaceID = decodeString(source["workspace_id"])
	out.Branch = decodeString(source["branch"])
	out.HeadCommit = decodeString(source["head_commit"])
	out.Dirty = decodeBool(source["dirty"])
	return out
}

// DecodeReconnectRequest builds a ReconnectRequest from a validated tree.
func DecodeReconnectRequest(value any) ReconnectRequest {
	source, _ := value.(map[string]any)
	var out ReconnectRequest
	out.ConnectorVersion = decodeString(source["connector_version"])
	out.Capabilities = decodeSlice(source["capabilities"], func(item any) string { return decodeString(item) })
	out.ActiveRoutes = decodeSlice(source["active_routes"], func(item any) ReconnectRoute { return DecodeReconnectRoute(item) })
	out.ActiveStreams = decodeSlice(source["active_streams"], func(item any) ReconnectStream { return DecodeReconnectStream(item) })
	out.KnownAgentSessions = decodeSlice(source["known_agent_sessions"], func(item any) string { return decodeString(item) })
	out.WorkspaceHeadState = decodeSlice(source["workspace_head_state"], func(item any) WorkspaceHead { return DecodeWorkspaceHead(item) })
	return out
}

// DecodeRouteDecision builds a RouteDecision from a validated tree.
func DecodeRouteDecision(value any) RouteDecision {
	source, _ := value.(map[string]any)
	var out RouteDecision
	out.RouteID = decodeString(source["route_id"])
	out.Decision = RouteReconciliationDecision(decodeString(source["decision"]))
	out.Reason = RouteReconciliationReason(decodeString(source["reason"]))
	if field, present := source["route"]; present {
		decoded := DecodeRoutePublish(field)
		out.Route = &decoded
	}
	return out
}

// DecodeSessionDecision builds a SessionDecision from a validated tree.
func DecodeSessionDecision(value any) SessionDecision {
	source, _ := value.(map[string]any)
	var out SessionDecision
	out.BrowserSessionID = decodeString(source["browser_session_id"])
	out.Decision = SessionReconciliationDecision(decodeString(source["decision"]))
	out.Reason = SessionReconciliationReason(decodeString(source["reason"]))
	return out
}

// DecodeReconnectResponse builds a ReconnectResponse from a validated tree.
func DecodeReconnectResponse(value any) ReconnectResponse {
	source, _ := value.(map[string]any)
	var out ReconnectResponse
	out.ReconciledAt = decodeString(source["reconciled_at"])
	out.Upgrade = UpgradeClassification(decodeString(source["upgrade"]))
	out.Routes = decodeSlice(source["routes"], func(item any) RouteDecision { return DecodeRouteDecision(item) })
	out.Sessions = decodeSlice(source["sessions"], func(item any) SessionDecision { return DecodeSessionDecision(item) })
	return out
}
