// Code generated by packages/protocol/tools/generate.ts from
// schemas/connector/v1.schema.json. DO NOT EDIT.

package connectorv1

// ProtocolName is the protocol described by ReviewPlane connector protocol, version 1.
const ProtocolName = "connector"

// ProtocolVersion is the only version this build accepts. An envelope carrying any
// other value is rejected with ErrorClassProtocolUnsupported and is never best-effort
// parsed.
const ProtocolVersion int64 = 1

// Byte bounds enforced on raw frames before deserialisation.
const (
	MaxControlFrameBytes     = 65536
	MaxDataStreamHeaderBytes = 4096
)

// Channel is a logical channel of the connector protocol.
type Channel string

const (
	// ChannelControl carries commands, acknowledgements, policy and registration.
	ChannelControl Channel = "control"
	// ChannelHeartbeat carries health and capacity.
	ChannelHeartbeat Channel = "heartbeat"
	// ChannelRoutes carries published-service lifecycle.
	ChannelRoutes Channel = "routes"
	// ChannelData carries multiplexed route traffic.
	ChannelData Channel = "data"
	// ChannelEvents carries local project and agent-session observations.
	ChannelEvents Channel = "events"
	// ChannelUpgrade carries version and compatibility notices.
	ChannelUpgrade Channel = "upgrade"
)

// ChannelValues lists every channel in declaration order.
var ChannelValues = []Channel{ChannelControl, ChannelHeartbeat, ChannelRoutes, ChannelData, ChannelEvents, ChannelUpgrade}

// DestinationProtocol is defined by the connector protocol schema.
//
// Application protocol spoken to the local development service. HTTP upgrade to
// WebSocket is carried inside http and https (docs/CONNECTOR_PROTOCOL.md section 13).
type DestinationProtocol string

const (
	DestinationProtocolHTTP  DestinationProtocol = "http"
	DestinationProtocolHTTPS DestinationProtocol = "https"
)

// DestinationProtocolValues lists every value in declaration order.
var DestinationProtocolValues = []DestinationProtocol{DestinationProtocolHTTP, DestinationProtocolHTTPS}

// StreamMode is defined by the connector protocol schema.
//
// Framing the stream carries after its header (docs/CONNECTOR_PROTOCOL.md section
// 13.3). request_response is one bounded HTTP exchange; upgrade is a connection the
// gateway has switched to another framing, such as WebSocket, and which therefore
// lives as long as its route allows rather than as long as one exchange takes. The
// connector reads it to choose a stream's idle window; it never influences which
// destination is opened, because the destination is fixed at publication and this
// header carries no host or port. Absent means request_response.
type StreamMode string

const (
	StreamModeRequestResponse StreamMode = "request_response"
	StreamModeUpgrade         StreamMode = "upgrade"
)

// StreamModeValues lists every value in declaration order.
var StreamModeValues = []StreamMode{StreamModeRequestResponse, StreamModeUpgrade}

// MessageType is defined by the connector protocol schema.
//
// Version 1 message type. Unknown types are rejected, never ignored. This enumeration
// MUST equal the keys of x-protocol.messages.
type MessageType string

const (
	MessageTypeConnectorRegistrationRequest  MessageType = "connector.registration.request"
	MessageTypeConnectorRegistrationResponse MessageType = "connector.registration.response"
	MessageTypeHeartbeat                     MessageType = "heartbeat"
	MessageTypeRoutePublish                  MessageType = "route.publish"
	MessageTypeRoutePublishAck               MessageType = "route.publish.ack"
	MessageTypeConnectorReconnectRequest     MessageType = "connector.reconnect.request"
	MessageTypeConnectorReconnectResponse    MessageType = "connector.reconnect.response"
)

// MessageTypeValues lists every value in declaration order.
var MessageTypeValues = []MessageType{MessageTypeConnectorRegistrationRequest, MessageTypeConnectorRegistrationResponse, MessageTypeHeartbeat, MessageTypeRoutePublish, MessageTypeRoutePublishAck, MessageTypeConnectorReconnectRequest, MessageTypeConnectorReconnectResponse}

// ErrorClass is defined by the connector protocol schema.
//
// Stable connector error class (docs/CONNECTOR_PROTOCOL.md section 21). This
// enumeration MUST equal x-protocol.error_classes.
type ErrorClass string

const (
	ErrorClassEnrolmentTokenInvalid   ErrorClass = "ENROLMENT_TOKEN_INVALID"
	ErrorClassIdentityRevoked         ErrorClass = "IDENTITY_REVOKED"
	ErrorClassProtocolUnsupported     ErrorClass = "PROTOCOL_UNSUPPORTED"
	ErrorClassProjectNotAuthorised    ErrorClass = "PROJECT_NOT_AUTHORISED"
	ErrorClassWorkspaceNotFound       ErrorClass = "WORKSPACE_NOT_FOUND"
	ErrorClassDestinationNotAllowed   ErrorClass = "DESTINATION_NOT_ALLOWED"
	ErrorClassPortNotListening        ErrorClass = "PORT_NOT_LISTENING"
	ErrorClassRouteLimitExceeded      ErrorClass = "ROUTE_LIMIT_EXCEEDED"
	ErrorClassRouteExpired            ErrorClass = "ROUTE_EXPIRED"
	ErrorClassStreamLimitExceeded     ErrorClass = "STREAM_LIMIT_EXCEEDED"
	ErrorClassControlPlaneUnavailable ErrorClass = "CONTROL_PLANE_UNAVAILABLE"
	ErrorClassUpgradeRequired         ErrorClass = "UPGRADE_REQUIRED"
)

// ErrorClassValues lists every value in declaration order.
var ErrorClassValues = []ErrorClass{ErrorClassEnrolmentTokenInvalid, ErrorClassIdentityRevoked, ErrorClassProtocolUnsupported, ErrorClassProjectNotAuthorised, ErrorClassWorkspaceNotFound, ErrorClassDestinationNotAllowed, ErrorClassPortNotListening, ErrorClassRouteLimitExceeded, ErrorClassRouteExpired, ErrorClassStreamLimitExceeded, ErrorClassControlPlaneUnavailable, ErrorClassUpgradeRequired}

// HeartbeatStatus is defined by the connector protocol schema.
//
// Connector self-reported health. Delayed and disconnected are control-plane
// conclusions, not self-reports.
type HeartbeatStatus string

const (
	HeartbeatStatusHealthy  HeartbeatStatus = "healthy"
	HeartbeatStatusDegraded HeartbeatStatus = "degraded"
)

// HeartbeatStatusValues lists every value in declaration order.
var HeartbeatStatusValues = []HeartbeatStatus{HeartbeatStatusHealthy, HeartbeatStatusDegraded}

// RoutePublishAckStatus is defined by the connector protocol schema.
//
// Outcome of connector validation.
type RoutePublishAckStatus string

const (
	RoutePublishAckStatusReady    RoutePublishAckStatus = "ready"
	RoutePublishAckStatusRejected RoutePublishAckStatus = "rejected"
)

// RoutePublishAckStatusValues lists every value in declaration order.
var RoutePublishAckStatusValues = []RoutePublishAckStatus{RoutePublishAckStatusReady, RoutePublishAckStatusRejected}

// UpgradeClassification is defined by the connector protocol schema.
//
// Control-plane classification of the connector build (docs/CONNECTOR_PROTOCOL.md
// section 19). upgrade_required and unsupported are terminal: the connector reports
// the classification and stops rather than retrying with a build the control plane has
// just refused (section 5.3).
type UpgradeClassification string

const (
	UpgradeClassificationCompatible         UpgradeClassification = "compatible"
	UpgradeClassificationUpgradeRecommended UpgradeClassification = "upgrade_recommended"
	UpgradeClassificationUpgradeRequired    UpgradeClassification = "upgrade_required"
	UpgradeClassificationUnsupported        UpgradeClassification = "unsupported"
)

// UpgradeClassificationValues lists every value in declaration order.
var UpgradeClassificationValues = []UpgradeClassification{UpgradeClassificationCompatible, UpgradeClassificationUpgradeRecommended, UpgradeClassificationUpgradeRequired, UpgradeClassificationUnsupported}

// RouteReconciliationDecision is defined by the connector protocol schema.
//
// The control plane's authoritative answer for one route on reconnect
// (docs/CONNECTOR_PROTOCOL.md section 17). continue resumes the route under the same
// route_id without re-publication; revoke closes it.
type RouteReconciliationDecision string

const (
	RouteReconciliationDecisionContinue RouteReconciliationDecision = "continue"
	RouteReconciliationDecisionRevoke   RouteReconciliationDecision = "revoke"
)

// RouteReconciliationDecisionValues lists every value in declaration order.
var RouteReconciliationDecisionValues = []RouteReconciliationDecision{RouteReconciliationDecisionContinue, RouteReconciliationDecisionRevoke}

// RouteReconciliationReason is defined by the connector protocol schema.
//
// Why a route was continued or closed. It is a closed vocabulary so that every
// decision is loggable and auditable without free text (docs/SECURITY.md section 18).
type RouteReconciliationReason string

const (
	RouteReconciliationReasonAuthorised          RouteReconciliationReason = "authorised"
	RouteReconciliationReasonUnknownRoute        RouteReconciliationReason = "unknown_route"
	RouteReconciliationReasonExpired             RouteReconciliationReason = "expired"
	RouteReconciliationReasonRevoked             RouteReconciliationReason = "revoked"
	RouteReconciliationReasonNotAuthorised       RouteReconciliationReason = "not_authorised"
	RouteReconciliationReasonDestinationMismatch RouteReconciliationReason = "destination_mismatch"
)

// RouteReconciliationReasonValues lists every value in declaration order.
var RouteReconciliationReasonValues = []RouteReconciliationReason{RouteReconciliationReasonAuthorised, RouteReconciliationReasonUnknownRoute, RouteReconciliationReasonExpired, RouteReconciliationReasonRevoked, RouteReconciliationReasonNotAuthorised, RouteReconciliationReasonDestinationMismatch}

// SessionReconciliationDecision is defined by the connector protocol schema.
//
// The control plane's authoritative answer for one browser session on reconnect
// (docs/CONNECTOR_PROTOCOL.md section 17). re_establish rebuilds the session's data
// path; end closes what the connector still holds for it.
type SessionReconciliationDecision string

const (
	SessionReconciliationDecisionReEstablish SessionReconciliationDecision = "re_establish"
	SessionReconciliationDecisionEnd         SessionReconciliationDecision = "end"
)

// SessionReconciliationDecisionValues lists every value in declaration order.
var SessionReconciliationDecisionValues = []SessionReconciliationDecision{SessionReconciliationDecisionReEstablish, SessionReconciliationDecisionEnd}

// SessionReconciliationReason is defined by the connector protocol schema.
//
// Why a session was re-established or ended. A closed vocabulary, for the same reason
// as route_reconciliation_reason.
type SessionReconciliationReason string

const (
	SessionReconciliationReasonRouteResumed         SessionReconciliationReason = "route_resumed"
	SessionReconciliationReasonRouteRevoked         SessionReconciliationReason = "route_revoked"
	SessionReconciliationReasonSessionEnded         SessionReconciliationReason = "session_ended"
	SessionReconciliationReasonConnectorReconnected SessionReconciliationReason = "connector_reconnected"
)

// SessionReconciliationReasonValues lists every value in declaration order.
var SessionReconciliationReasonValues = []SessionReconciliationReason{SessionReconciliationReasonRouteResumed, SessionReconciliationReasonRouteRevoked, SessionReconciliationReasonSessionEnded, SessionReconciliationReasonConnectorReconnected}

// MessageDirection states which side of the trust boundary sends a message.
type MessageDirection string

const (
	DirectionConnectorToControlPlane MessageDirection = "connector_to_control_plane"
	DirectionControlPlaneToConnector MessageDirection = "control_plane_to_connector"
)

// MessageDirections records the sender of each message type.
var MessageDirections = map[MessageType]MessageDirection{
	MessageTypeConnectorRegistrationRequest:  DirectionConnectorToControlPlane,
	MessageTypeConnectorRegistrationResponse: DirectionControlPlaneToConnector,
	MessageTypeHeartbeat:                     DirectionConnectorToControlPlane,
	MessageTypeRoutePublish:                  DirectionControlPlaneToConnector,
	MessageTypeRoutePublishAck:               DirectionConnectorToControlPlane,
	MessageTypeConnectorReconnectRequest:     DirectionConnectorToControlPlane,
	MessageTypeConnectorReconnectResponse:    DirectionControlPlaneToConnector,
}

// MessageChannels records the channel each message type travels on.
var MessageChannels = map[MessageType]Channel{
	MessageTypeConnectorRegistrationRequest:  ChannelControl,
	MessageTypeConnectorRegistrationResponse: ChannelControl,
	MessageTypeHeartbeat:                     ChannelHeartbeat,
	MessageTypeRoutePublish:                  ChannelRoutes,
	MessageTypeRoutePublishAck:               ChannelRoutes,
	MessageTypeConnectorReconnectRequest:     ChannelControl,
	MessageTypeConnectorReconnectResponse:    ChannelControl,
}

// PayloadMaxBytes records the maximum canonical payload size for each message type. A
// payload larger than its bound is rejected.
var PayloadMaxBytes = map[MessageType]int{
	MessageTypeConnectorRegistrationRequest:  4096,
	MessageTypeConnectorRegistrationResponse: 8192,
	MessageTypeHeartbeat:                     1024,
	MessageTypeRoutePublish:                  2048,
	MessageTypeRoutePublishAck:               1024,
	MessageTypeConnectorReconnectRequest:     32768,
	MessageTypeConnectorReconnectResponse:    57344,
}

// ViolationReason classifies a refused frame. Only some reasons map to a wire error
// class.
type ViolationReason string

const (
	// ReasonFrameTooLarge reports that the encoded frame exceeded its byte bound.
	// Detected on the raw bytes before deserialisation.
	ReasonFrameTooLarge ViolationReason = "frame_too_large"
	// ReasonMalformedJSON reports that the frame was not well-formed JSON, or was
	// truncated.
	ReasonMalformedJSON ViolationReason = "malformed_json"
	// ReasonUnsupportedProtocolVersion reports that protocol_version was absent, not an
	// integer, or not a version this build accepts.
	ReasonUnsupportedProtocolVersion ViolationReason = "unsupported_protocol_version"
	// ReasonUnknownMessageType reports that type was absent or not a version 1 message
	// type. Unknown types are rejected, never ignored.
	ReasonUnknownMessageType ViolationReason = "unknown_message_type"
	// ReasonPayloadTooLarge reports that the payload exceeded the byte bound declared for
	// its message type.
	ReasonPayloadTooLarge ViolationReason = "payload_too_large"
	// ReasonSchemaViolation reports that the frame parsed but did not satisfy the schema
	// for its message type.
	ReasonSchemaViolation ViolationReason = "schema_violation"
)

// ViolationErrorClass maps a rejection reason to the connector error class reported
// for it.
var ViolationErrorClass = map[ViolationReason]ErrorClass{
	ReasonFrameTooLarge:              "",
	ReasonMalformedJSON:              "",
	ReasonUnsupportedProtocolVersion: ErrorClassProtocolUnsupported,
	ReasonUnknownMessageType:         ErrorClassProtocolUnsupported,
	ReasonPayloadTooLarge:            "",
	ReasonSchemaViolation:            "",
}

// SchemaViolationCode identifies the kind of schema failure.
type SchemaViolationCode string

const (
	SchemaViolationType            SchemaViolationCode = "type"
	SchemaViolationRequired        SchemaViolationCode = "required"
	SchemaViolationForbidden       SchemaViolationCode = "forbidden"
	SchemaViolationUnknownProperty SchemaViolationCode = "unknown_property"
	SchemaViolationEnum            SchemaViolationCode = "enum"
	SchemaViolationConst           SchemaViolationCode = "const"
	SchemaViolationPattern         SchemaViolationCode = "pattern"
	SchemaViolationTooShort        SchemaViolationCode = "too_short"
	SchemaViolationTooLong         SchemaViolationCode = "too_long"
	SchemaViolationTooSmall        SchemaViolationCode = "too_small"
	SchemaViolationTooLarge        SchemaViolationCode = "too_large"
	SchemaViolationTooFewItems     SchemaViolationCode = "too_few_items"
	SchemaViolationTooManyItems    SchemaViolationCode = "too_many_items"
	SchemaViolationDuplicateItems  SchemaViolationCode = "duplicate_items"
	SchemaViolationNotInteger      SchemaViolationCode = "not_integer"
)

// SchemaViolation is one schema failure, located by JSON path.
type SchemaViolation struct {
	Path    string              `json:"path"`
	Code    SchemaViolationCode `json:"code"`
	Message string              `json:"message"`
}

// KnownCapabilities lists the capabilities known at this protocol version. Unknown
// capabilities are accepted so that a newer connector is classified rather than
// rejected.
var KnownCapabilities = []string{"http-tunnel", "websocket-tunnel", "git-context", "local-mcp-bridge"}

// KnownPlatforms lists the platforms known at this protocol version.
var KnownPlatforms = []string{"linux", "darwin", "windows"}

// KnownArchitectures lists the architectures known at this protocol version.
var KnownArchitectures = []string{"amd64", "arm64"}

// IdentifierPrefixes records the conventional prefixes of the opaque identifiers this
// protocol carries. They are documentation only: consumers must treat identifiers as
// opaque and validators must not require a prefix.
var IdentifierPrefixes = map[string]string{
	"message_id":         "msg_",
	"connector_id":       "con_",
	"project_id":         "prj_",
	"workspace_id":       "wsp_",
	"browser_session_id": "brs_",
	"route_id":           "svc_",
}

// Identifier is defined by the connector protocol schema.
//
// Opaque durable identifier (docs/DOMAIN_MODEL.md section 3). Consumers MUST treat the
// value as opaque: the schema bounds only its length and character class and never its
// documented prefix.
type Identifier = string

// Timestamp is defined by the connector protocol schema.
//
// RFC 3339 timestamp in UTC, with a mandatory trailing Z.
type Timestamp = string

// WebsocketURL is defined by the connector protocol schema.
//
// Outbound WebSocket endpoint. TLS is mandatory, so only the wss scheme is accepted
// (docs/SECURITY.md section 15).
type WebsocketURL = string

// SemanticVersion is defined by the connector protocol schema.
//
// Connector release version, for example 0.1.0.
type SemanticVersion = string

// Digest is defined by the connector protocol schema.
//
// Opaque digest or fingerprint. Bounded in length and character class only.
type Digest = string

// EnrolmentToken is defined by the connector protocol schema.
//
// One-time enrolment token (docs/SECURITY.md section 6.2). Sensitive: generated models
// wrap this value so that log, debug and default JSON representations redact it. The
// wire value is produced only by the generated canonical encoder.
type EnrolmentToken = SensitiveString

// SessionCapability is defined by the connector protocol schema.
//
// Session-scoped route capability presented when opening a data stream
// (docs/SECURITY.md section 9). Sensitive: it is a bearer credential and is redacted
// in log, debug and default JSON representations.
type SessionCapability = SensitiveString

// PublicKey is defined by the connector protocol schema.
//
// Base64-encoded SubjectPublicKeyInfo for the connector device key. The matching
// private key never leaves the development environment and this protocol has no field
// capable of carrying it (docs/CONNECTOR_PROTOCOL.md section 4.2).
type PublicKey = string

// Certificate is defined by the connector protocol schema.
//
// Base64-encoded signed device identity issued by the control plane.
type Certificate = string

// EnvironmentLabel is defined by the connector protocol schema.
//
// Operator-assigned environment label.
type EnvironmentLabel = string

// ConnectorCapability is defined by the connector protocol schema.
//
// Capability advertised by the connector build. Known version 1 values are listed in
// x-protocol.known_capabilities; unknown values are accepted so that a newer connector
// is classified by docs/CONNECTOR_PROTOCOL.md section 19 rather than rejected
// outright.
type ConnectorCapability = string

// Envelope is defined by the connector protocol schema.
//
// Control-channel message envelope (docs/CONNECTOR_PROTOCOL.md section 7).
type Envelope struct {
	// Protocol version. Stage 0 accepts 1 only; any other value is rejected with
	// PROTOCOL_UNSUPPORTED and is never best-effort parsed.
	ProtocolVersion int64 `json:"protocol_version"`
	// Sender-assigned message identifier, conventionally prefixed msg_.
	MessageID string `json:"message_id"`
	// Version 1 message type. Unknown types are rejected.
	Type MessageType `json:"type"`
	// Time the sender emitted the message.
	SentAt string `json:"sent_at"`
	// Connector identity, conventionally prefixed con_. Absent on the registration
	// exchange, where the identity is still being established, and required on every
	// other message type.
	ConnectorID *string `json:"connector_id,omitempty"`
	// Identifier of the message or command this message answers.
	CorrelationID *string `json:"correlation_id,omitempty"`
}

// EnvironmentDescriptor is defined by the connector protocol schema.
//
// Development environment self-description (docs/CONNECTOR_PROTOCOL.md section 4.3,
// docs/DOMAIN_MODEL.md section 7).
type EnvironmentDescriptor struct {
	// Operator-visible environment name.
	Name string `json:"name"`
	// Operating system. Known version 1 values are in x-protocol.known_platforms.
	Platform string `json:"platform"`
	// CPU architecture. Known version 1 values are in x-protocol.known_architectures.
	Architecture string `json:"architecture"`
	// Optional operator-assigned labels.
	Labels []string `json:"labels,omitempty"`
}

// ConnectorDescriptor is defined by the connector protocol schema.
//
// Connector build self-description (docs/CONNECTOR_PROTOCOL.md section 4.3).
type ConnectorDescriptor struct {
	// Connector release version.
	Version string `json:"version"`
	// Capabilities this connector build supports.
	Capabilities []string `json:"capabilities"`
}

// RegistrationRequest is defined by the connector protocol schema.
//
// Registration request (docs/CONNECTOR_PROTOCOL.md section 4.3). protocol_version is
// carried by the envelope and is not repeated here.
type RegistrationRequest struct {
	// One-time enrolment token. Consumed on success.
	EnrolmentToken SensitiveString `json:"enrolment_token"`
	// Connector device public key.
	PublicKey string `json:"public_key"`
	// Development environment description.
	Environment EnvironmentDescriptor `json:"environment"`
	// Connector build description.
	Connector ConnectorDescriptor `json:"connector"`
}

// SignedIdentity is defined by the connector protocol schema.
//
// Signed device identity issued in exchange for the enrolment token (docs/SECURITY.md
// section 6.2).
type SignedIdentity struct {
	// Signed device identity.
	Certificate string `json:"certificate"`
	// Fingerprint recorded on the connector record (docs/DOMAIN_MODEL.md section 8).
	CertificateFingerprint string `json:"certificate_fingerprint"`
	// Identity expiry. Identities are bounded in time.
	ExpiresAt string `json:"expires_at"`
}

// ControlPlaneEndpoints is defined by the connector protocol schema.
//
// Endpoints the connector dials outbound after enrolment (docs/CONNECTOR_PROTOCOL.md
// section 5).
type ControlPlaneEndpoints struct {
	// Control, heartbeat, routes, events and upgrade channels.
	ControlURL string `json:"control_url"`
	// Multiplexed data streams.
	DataURL string `json:"data_url"`
}

// RegistrationResponse is defined by the connector protocol schema.
//
// Registration response (docs/CONNECTOR_PROTOCOL.md section 4.3): connector ID, signed
// identity, control-plane endpoints and organisation policy digest.
type RegistrationResponse struct {
	// Assigned connector identity, conventionally prefixed con_.
	ConnectorID string `json:"connector_id"`
	// Signed device identity.
	SignedIdentity SignedIdentity `json:"signed_identity"`
	// Outbound endpoints for subsequent connections.
	ControlPlaneEndpoints ControlPlaneEndpoints `json:"control_plane_endpoints"`
	// Digest of the organisation policy the connector must apply.
	PolicyDigest string `json:"policy_digest"`
}

// ResourceSummary is defined by the connector protocol schema.
//
// Optional coarse resource report. additionalProperties is false so that no sensitive
// process detail can be attached (docs/CONNECTOR_PROTOCOL.md section 8).
type ResourceSummary struct {
	// Normalised system load average.
	Load *float64 `json:"load,omitempty"`
	// Available memory in bytes.
	MemoryAvailableBytes *int64 `json:"memory_available_bytes,omitempty"`
}

// Heartbeat is defined by the connector protocol schema.
//
// Heartbeat payload (docs/CONNECTOR_PROTOCOL.md section 8).
type Heartbeat struct {
	// Connector self-reported health. Delayed and disconnected are control-plane
	// conclusions, not self-reports.
	Status HeartbeatStatus `json:"status"`
	// Seconds since connector start.
	UptimeSeconds int64 `json:"uptime_seconds"`
	// Connector release version.
	Version string `json:"version"`
	// Currently published routes.
	ActiveRoutes int64 `json:"active_routes"`
	// Currently open data streams.
	ActiveStreams int64 `json:"active_streams"`
	// Optional resource report.
	ResourceSummary *ResourceSummary `json:"resource_summary,omitempty"`
}

// RoutePublish is defined by the connector protocol schema.
//
// Route publication request from the control plane (docs/CONNECTOR_PROTOCOL.md section
// 11).
type RoutePublish struct {
	// Published-service identity, conventionally prefixed svc_.
	RouteID string `json:"route_id"`
	// Owning project, conventionally prefixed prj_.
	ProjectID string `json:"project_id"`
	// Owning workspace, conventionally prefixed wsp_.
	WorkspaceID string `json:"workspace_id"`
	// Local destination host. The connector still applies its own allow-list; schema
	// acceptance is not authorisation.
	LocalHost string `json:"local_host"`
	// Local destination port.
	LocalPort int64 `json:"local_port"`
	// Protocol spoken to the local destination.
	Protocol DestinationProtocol `json:"protocol"`
	// Publication expiry. Publication always expires.
	ExpiresAt string `json:"expires_at"`
	// Browser sessions authorised to use the route, conventionally prefixed brs_.
	AllowedBrowserSessionIDs []string `json:"allowed_browser_session_ids"`
}

// RoutePublishAck is defined by the connector protocol schema.
//
// Connector acknowledgement of a route publication request (docs/CONNECTOR_PROTOCOL.md
// section 11). Rejection carries a stable error class and no free text, per
// docs/SECURITY.md section 18.
type RoutePublishAck struct {
	// Route this acknowledgement answers.
	RouteID string `json:"route_id"`
	// Outcome of connector validation.
	Status RoutePublishAckStatus `json:"status"`
	// Destination the connector actually opened, as host:port.
	ObservedDestination *string `json:"observed_destination,omitempty"`
	// Stable connector error class explaining a rejection (docs/CONNECTOR_PROTOCOL.md
	// section 21).
	ErrorClass *ErrorClass `json:"error_class,omitempty"`
}

// DataStreamHeader is defined by the connector protocol schema.
//
// Header opening one tunnelled connection on the data channel
// (docs/CONNECTOR_PROTOCOL.md section 12). The connector opens only the pre-authorised
// destination bound to route_id; this header carries no host or port.
type DataStreamHeader struct {
	// Published route this stream belongs to.
	RouteID string `json:"route_id"`
	// Browser session requesting the stream, conventionally prefixed brs_.
	BrowserSessionID string `json:"browser_session_id"`
	// Session-scoped capability authorising use of the route.
	SessionCapability SensitiveString `json:"session_capability"`
	// Application-level stream identifier, unique for the connection.
	StreamID string `json:"stream_id"`
	// Protocol spoken to the local destination.
	DestinationProtocol DestinationProtocol `json:"destination_protocol"`
	// Absolute deadline after which the stream is closed. It never exceeds the expiry of
	// the route the stream belongs to.
	Deadline string `json:"deadline"`
	// Framing carried after this header. Absent means request_response.
	StreamMode *StreamMode `json:"stream_mode,omitempty"`
}

// ReconnectRoute is defined by the connector protocol schema.
//
// One route the connector believes it is still serving (docs/CONNECTOR_PROTOCOL.md
// section 17). It is a claim, not an authorisation: the control plane decides whether
// the route continues.
type ReconnectRoute struct {
	// Published-service identity the connector holds.
	RouteID string `json:"route_id"`
	// Project the connector believes the route belongs to.
	ProjectID string `json:"project_id"`
	// Workspace the connector believes the route belongs to.
	WorkspaceID string `json:"workspace_id"`
	// Destination the connector is opening for this route, as host:port. A destination
	// that differs from the authoritative record is closed rather than continued, because
	// docs/ARCHITECTURE.md section 14 forbids silently redirecting traffic to a different
	// environment.
	ObservedDestination string `json:"observed_destination"`
	// Expiry the connector recorded at publication.
	ExpiresAt string `json:"expires_at"`
}

// ReconnectStream is defined by the connector protocol schema.
//
// One data stream the connector still holds open (docs/CONNECTOR_PROTOCOL.md section
// 17). A stream whose route is revoked is closed with the route.
type ReconnectStream struct {
	// Application-level stream identifier from the data-stream header.
	StreamID string `json:"stream_id"`
	// Route the stream belongs to.
	RouteID string `json:"route_id"`
	// Browser session the stream was opened for.
	BrowserSessionID string `json:"browser_session_id"`
	// Absolute deadline the stream carries.
	Deadline string `json:"deadline"`
}

// WorkspaceHead is defined by the connector protocol schema.
//
// Head state of one workspace (docs/CONNECTOR_PROTOCOL.md section 9). Stage 0 reports
// no workspace head state; the field exists so that Stage 1 Git context does not
// change the message shape. Source file contents are never reported and this object
// has no field capable of carrying them.
type WorkspaceHead struct {
	// Workspace this head state describes.
	WorkspaceID string `json:"workspace_id"`
	// Checked-out branch.
	Branch string `json:"branch"`
	// HEAD commit identifier.
	HeadCommit string `json:"head_commit"`
	// Whether the working tree has uncommitted changes.
	Dirty bool `json:"dirty"`
}

// ReconnectRequest is defined by the connector protocol schema.
//
// What the connector believes it holds, sent on every control-channel establishment
// (docs/CONNECTOR_PROTOCOL.md section 17). All six fields are always present; Stage 0
// sends empty collections for known_agent_sessions and workspace_head_state, which are
// Stage 1 capabilities. The payload carries no credential: the identity is the
// mutually authenticated client certificate the channel already presented.
type ReconnectRequest struct {
	// Connector release version, which the control plane classifies per section 19.
	ConnectorVersion string `json:"connector_version"`
	// Capabilities this connector build supports.
	Capabilities []string `json:"capabilities"`
	// Routes the connector believes it is still serving.
	ActiveRoutes []ReconnectRoute `json:"active_routes"`
	// Data streams the connector still holds open.
	ActiveStreams []ReconnectStream `json:"active_streams"`
	// Agent sessions the connector has observed locally, conventionally prefixed ags_.
	// Stage 0 sends an empty array; agent-session re-establishment is Stage 1.
	KnownAgentSessions []string `json:"known_agent_sessions"`
	// Head state of the workspaces this connector serves. Stage 0 sends an empty array;
	// workspace discovery is Stage 1 (section 9).
	WorkspaceHeadState []WorkspaceHead `json:"workspace_head_state"`
}

// RouteDecision is defined by the connector protocol schema.
//
// The control plane's authoritative answer for one route (docs/CONNECTOR_PROTOCOL.md
// section 17). A continued route restates the whole publication, so a connector that
// lost its route table to a restart resumes the same route_id and the same destination
// without re-publication; the connector still applies its own section 11 validation,
// because schema acceptance is not authorisation.
type RouteDecision struct {
	// Route this decision answers for.
	RouteID string `json:"route_id"`
	// Continue or revoke. The control plane's answer wins in every disagreement.
	Decision RouteReconciliationDecision `json:"decision"`
	// Why the decision was reached, for the connector's log and the control plane's audit
	// trail.
	Reason RouteReconciliationReason `json:"reason"`
	// The authoritative publication to resume. Present only when the decision is
	// continue.
	Route *RoutePublish `json:"route,omitempty"`
}

// SessionDecision is defined by the connector protocol schema.
//
// The control plane's authoritative answer for one browser session
// (docs/CONNECTOR_PROTOCOL.md section 17).
type SessionDecision struct {
	// Browser session this decision answers for, conventionally prefixed brs_.
	BrowserSessionID string `json:"browser_session_id"`
	// Re-establish the session's data path, or end what the connector still holds for it.
	Decision SessionReconciliationDecision `json:"decision"`
	// Why the decision was reached.
	Reason SessionReconciliationReason `json:"reason"`
}

// ReconnectResponse is defined by the connector protocol schema.
//
// The control plane's authoritative desired state (docs/CONNECTOR_PROTOCOL.md section
// 17). It is the answer to exactly one connector.reconnect.request, correlated by the
// envelope's correlation_id. A route the control plane does not name is not
// authorised: the connector closes anything the response does not continue.
type ReconnectResponse struct {
	// The instant the control plane reconciled. It is authoritative for expiry
	// arithmetic, so that clock skew on the development machine cannot extend a route.
	ReconciledAt string `json:"reconciled_at"`
	// Section 19 classification of the reported connector version.
	Upgrade UpgradeClassification `json:"upgrade"`
	// One decision per route, covering both the routes the connector claimed and the
	// routes the control plane holds for it.
	Routes []RouteDecision `json:"routes"`
	// One decision per affected browser session.
	Sessions []SessionDecision `json:"sessions"`
}

// Payload is implemented by every version 1 message payload. The interface is closed:
// only payloads generated from the schema can satisfy it.
type Payload interface {
	// MessageType reports the envelope type this payload belongs to.
	MessageType() MessageType
	isConnectorPayload()
}

// MessageType reports the envelope type carrying a RegistrationRequest.
func (RegistrationRequest) MessageType() MessageType { return MessageTypeConnectorRegistrationRequest }

func (RegistrationRequest) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RegistrationResponse.
func (RegistrationResponse) MessageType() MessageType {
	return MessageTypeConnectorRegistrationResponse
}

func (RegistrationResponse) isConnectorPayload() {}

// MessageType reports the envelope type carrying a Heartbeat.
func (Heartbeat) MessageType() MessageType { return MessageTypeHeartbeat }

func (Heartbeat) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RoutePublish.
func (RoutePublish) MessageType() MessageType { return MessageTypeRoutePublish }

func (RoutePublish) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RoutePublishAck.
func (RoutePublishAck) MessageType() MessageType { return MessageTypeRoutePublishAck }

func (RoutePublishAck) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ReconnectRequest.
func (ReconnectRequest) MessageType() MessageType { return MessageTypeConnectorReconnectRequest }

func (ReconnectRequest) isConnectorPayload() {}

// MessageType reports the envelope type carrying a ReconnectResponse.
func (ReconnectResponse) MessageType() MessageType { return MessageTypeConnectorReconnectResponse }

func (ReconnectResponse) isConnectorPayload() {}

// Frame is a decoded control frame: envelope header plus its typed payload.
type Frame struct {
	Envelope Envelope
	Payload  Payload
}
