// Code generated by packages/protocol/tools/generate.ts from
// schemas/connector/v1.schema.json. DO NOT EDIT.

package connectorv1

// ProtocolName is the protocol described by ReviewPlane connector protocol, version 1.
const ProtocolName = "connector"

// ProtocolVersion is the only version this build accepts. An envelope carrying any
// other value is rejected with ErrorClassProtocolUnsupported and is never best-effort
// parsed.
const ProtocolVersion int64 = 1

// Byte bounds enforced on raw frames before deserialisation.
const (
	MaxControlFrameBytes     = 65536
	MaxDataStreamHeaderBytes = 4096
)

// Channel is a logical channel of the connector protocol.
type Channel string

const (
	// ChannelControl carries commands, acknowledgements, policy and registration.
	ChannelControl Channel = "control"
	// ChannelHeartbeat carries health and capacity.
	ChannelHeartbeat Channel = "heartbeat"
	// ChannelRoutes carries published-service lifecycle.
	ChannelRoutes Channel = "routes"
	// ChannelData carries multiplexed route traffic.
	ChannelData Channel = "data"
	// ChannelEvents carries local project and agent-session observations.
	ChannelEvents Channel = "events"
	// ChannelUpgrade carries version and compatibility notices.
	ChannelUpgrade Channel = "upgrade"
)

// ChannelValues lists every channel in declaration order.
var ChannelValues = []Channel{ChannelControl, ChannelHeartbeat, ChannelRoutes, ChannelData, ChannelEvents, ChannelUpgrade}

// DestinationProtocol is defined by the connector protocol schema.
//
// Application protocol spoken to the local development service. HTTP upgrade to
// WebSocket is carried inside http and https (docs/CONNECTOR_PROTOCOL.md section 13).
type DestinationProtocol string

const (
	DestinationProtocolHTTP  DestinationProtocol = "http"
	DestinationProtocolHTTPS DestinationProtocol = "https"
)

// DestinationProtocolValues lists every value in declaration order.
var DestinationProtocolValues = []DestinationProtocol{DestinationProtocolHTTP, DestinationProtocolHTTPS}

// MessageType is defined by the connector protocol schema.
//
// Version 1 message type. Unknown types are rejected, never ignored. This enumeration
// MUST equal the keys of x-protocol.messages.
type MessageType string

const (
	MessageTypeConnectorRegistrationRequest  MessageType = "connector.registration.request"
	MessageTypeConnectorRegistrationResponse MessageType = "connector.registration.response"
	MessageTypeHeartbeat                     MessageType = "heartbeat"
	MessageTypeRoutePublish                  MessageType = "route.publish"
	MessageTypeRoutePublishAck               MessageType = "route.publish.ack"
)

// MessageTypeValues lists every value in declaration order.
var MessageTypeValues = []MessageType{MessageTypeConnectorRegistrationRequest, MessageTypeConnectorRegistrationResponse, MessageTypeHeartbeat, MessageTypeRoutePublish, MessageTypeRoutePublishAck}

// ErrorClass is defined by the connector protocol schema.
//
// Stable connector error class (docs/CONNECTOR_PROTOCOL.md section 21). This
// enumeration MUST equal x-protocol.error_classes.
type ErrorClass string

const (
	ErrorClassEnrolmentTokenInvalid   ErrorClass = "ENROLMENT_TOKEN_INVALID"
	ErrorClassIdentityRevoked         ErrorClass = "IDENTITY_REVOKED"
	ErrorClassProtocolUnsupported     ErrorClass = "PROTOCOL_UNSUPPORTED"
	ErrorClassProjectNotAuthorised    ErrorClass = "PROJECT_NOT_AUTHORISED"
	ErrorClassWorkspaceNotFound       ErrorClass = "WORKSPACE_NOT_FOUND"
	ErrorClassDestinationNotAllowed   ErrorClass = "DESTINATION_NOT_ALLOWED"
	ErrorClassPortNotListening        ErrorClass = "PORT_NOT_LISTENING"
	ErrorClassRouteLimitExceeded      ErrorClass = "ROUTE_LIMIT_EXCEEDED"
	ErrorClassRouteExpired            ErrorClass = "ROUTE_EXPIRED"
	ErrorClassStreamLimitExceeded     ErrorClass = "STREAM_LIMIT_EXCEEDED"
	ErrorClassControlPlaneUnavailable ErrorClass = "CONTROL_PLANE_UNAVAILABLE"
	ErrorClassUpgradeRequired         ErrorClass = "UPGRADE_REQUIRED"
)

// ErrorClassValues lists every value in declaration order.
var ErrorClassValues = []ErrorClass{ErrorClassEnrolmentTokenInvalid, ErrorClassIdentityRevoked, ErrorClassProtocolUnsupported, ErrorClassProjectNotAuthorised, ErrorClassWorkspaceNotFound, ErrorClassDestinationNotAllowed, ErrorClassPortNotListening, ErrorClassRouteLimitExceeded, ErrorClassRouteExpired, ErrorClassStreamLimitExceeded, ErrorClassControlPlaneUnavailable, ErrorClassUpgradeRequired}

// HeartbeatStatus is defined by the connector protocol schema.
//
// Connector self-reported health. Delayed and disconnected are control-plane
// conclusions, not self-reports.
type HeartbeatStatus string

const (
	HeartbeatStatusHealthy  HeartbeatStatus = "healthy"
	HeartbeatStatusDegraded HeartbeatStatus = "degraded"
)

// HeartbeatStatusValues lists every value in declaration order.
var HeartbeatStatusValues = []HeartbeatStatus{HeartbeatStatusHealthy, HeartbeatStatusDegraded}

// RoutePublishAckStatus is defined by the connector protocol schema.
//
// Outcome of connector validation.
type RoutePublishAckStatus string

const (
	RoutePublishAckStatusReady    RoutePublishAckStatus = "ready"
	RoutePublishAckStatusRejected RoutePublishAckStatus = "rejected"
)

// RoutePublishAckStatusValues lists every value in declaration order.
var RoutePublishAckStatusValues = []RoutePublishAckStatus{RoutePublishAckStatusReady, RoutePublishAckStatusRejected}

// MessageDirection states which side of the trust boundary sends a message.
type MessageDirection string

const (
	DirectionConnectorToControlPlane MessageDirection = "connector_to_control_plane"
	DirectionControlPlaneToConnector MessageDirection = "control_plane_to_connector"
)

// MessageDirections records the sender of each message type.
var MessageDirections = map[MessageType]MessageDirection{
	MessageTypeConnectorRegistrationRequest:  DirectionConnectorToControlPlane,
	MessageTypeConnectorRegistrationResponse: DirectionControlPlaneToConnector,
	MessageTypeHeartbeat:                     DirectionConnectorToControlPlane,
	MessageTypeRoutePublish:                  DirectionControlPlaneToConnector,
	MessageTypeRoutePublishAck:               DirectionConnectorToControlPlane,
}

// MessageChannels records the channel each message type travels on.
var MessageChannels = map[MessageType]Channel{
	MessageTypeConnectorRegistrationRequest:  ChannelControl,
	MessageTypeConnectorRegistrationResponse: ChannelControl,
	MessageTypeHeartbeat:                     ChannelHeartbeat,
	MessageTypeRoutePublish:                  ChannelRoutes,
	MessageTypeRoutePublishAck:               ChannelRoutes,
}

// PayloadMaxBytes records the maximum canonical payload size for each message type. A
// payload larger than its bound is rejected.
var PayloadMaxBytes = map[MessageType]int{
	MessageTypeConnectorRegistrationRequest:  4096,
	MessageTypeConnectorRegistrationResponse: 8192,
	MessageTypeHeartbeat:                     1024,
	MessageTypeRoutePublish:                  2048,
	MessageTypeRoutePublishAck:               1024,
}

// ViolationReason classifies a refused frame. Only some reasons map to a wire error
// class.
type ViolationReason string

const (
	// ReasonFrameTooLarge reports that the encoded frame exceeded its byte bound.
	// Detected on the raw bytes before deserialisation.
	ReasonFrameTooLarge ViolationReason = "frame_too_large"
	// ReasonMalformedJSON reports that the frame was not well-formed JSON, or was
	// truncated.
	ReasonMalformedJSON ViolationReason = "malformed_json"
	// ReasonUnsupportedProtocolVersion reports that protocol_version was absent, not an
	// integer, or not a version this build accepts.
	ReasonUnsupportedProtocolVersion ViolationReason = "unsupported_protocol_version"
	// ReasonUnknownMessageType reports that type was absent or not a version 1 message
	// type. Unknown types are rejected, never ignored.
	ReasonUnknownMessageType ViolationReason = "unknown_message_type"
	// ReasonPayloadTooLarge reports that the payload exceeded the byte bound declared for
	// its message type.
	ReasonPayloadTooLarge ViolationReason = "payload_too_large"
	// ReasonSchemaViolation reports that the frame parsed but did not satisfy the schema
	// for its message type.
	ReasonSchemaViolation ViolationReason = "schema_violation"
)

// ViolationErrorClass maps a rejection reason to the connector error class reported
// for it.
var ViolationErrorClass = map[ViolationReason]ErrorClass{
	ReasonFrameTooLarge:              "",
	ReasonMalformedJSON:              "",
	ReasonUnsupportedProtocolVersion: ErrorClassProtocolUnsupported,
	ReasonUnknownMessageType:         ErrorClassProtocolUnsupported,
	ReasonPayloadTooLarge:            "",
	ReasonSchemaViolation:            "",
}

// SchemaViolationCode identifies the kind of schema failure.
type SchemaViolationCode string

const (
	SchemaViolationType            SchemaViolationCode = "type"
	SchemaViolationRequired        SchemaViolationCode = "required"
	SchemaViolationForbidden       SchemaViolationCode = "forbidden"
	SchemaViolationUnknownProperty SchemaViolationCode = "unknown_property"
	SchemaViolationEnum            SchemaViolationCode = "enum"
	SchemaViolationConst           SchemaViolationCode = "const"
	SchemaViolationPattern         SchemaViolationCode = "pattern"
	SchemaViolationTooShort        SchemaViolationCode = "too_short"
	SchemaViolationTooLong         SchemaViolationCode = "too_long"
	SchemaViolationTooSmall        SchemaViolationCode = "too_small"
	SchemaViolationTooLarge        SchemaViolationCode = "too_large"
	SchemaViolationTooFewItems     SchemaViolationCode = "too_few_items"
	SchemaViolationTooManyItems    SchemaViolationCode = "too_many_items"
	SchemaViolationDuplicateItems  SchemaViolationCode = "duplicate_items"
	SchemaViolationNotInteger      SchemaViolationCode = "not_integer"
)

// SchemaViolation is one schema failure, located by JSON path.
type SchemaViolation struct {
	Path    string              `json:"path"`
	Code    SchemaViolationCode `json:"code"`
	Message string              `json:"message"`
}

// KnownCapabilities lists the capabilities known at this protocol version. Unknown
// capabilities are accepted so that a newer connector is classified rather than
// rejected.
var KnownCapabilities = []string{"http-tunnel", "websocket-tunnel", "git-context", "local-mcp-bridge"}

// KnownPlatforms lists the platforms known at this protocol version.
var KnownPlatforms = []string{"linux", "darwin", "windows"}

// KnownArchitectures lists the architectures known at this protocol version.
var KnownArchitectures = []string{"amd64", "arm64"}

// IdentifierPrefixes records the conventional prefixes of the opaque identifiers this
// protocol carries. They are documentation only: consumers must treat identifiers as
// opaque and validators must not require a prefix.
var IdentifierPrefixes = map[string]string{
	"message_id":         "msg_",
	"connector_id":       "con_",
	"project_id":         "prj_",
	"workspace_id":       "wsp_",
	"browser_session_id": "brs_",
	"route_id":           "svc_",
}

// Identifier is defined by the connector protocol schema.
//
// Opaque durable identifier (docs/DOMAIN_MODEL.md section 3). Consumers MUST treat the
// value as opaque: the schema bounds only its length and character class and never its
// documented prefix.
type Identifier = string

// Timestamp is defined by the connector protocol schema.
//
// RFC 3339 timestamp in UTC, with a mandatory trailing Z.
type Timestamp = string

// WebsocketURL is defined by the connector protocol schema.
//
// Outbound WebSocket endpoint. TLS is mandatory, so only the wss scheme is accepted
// (docs/SECURITY.md section 15).
type WebsocketURL = string

// SemanticVersion is defined by the connector protocol schema.
//
// Connector release version, for example 0.1.0.
type SemanticVersion = string

// Digest is defined by the connector protocol schema.
//
// Opaque digest or fingerprint. Bounded in length and character class only.
type Digest = string

// EnrolmentToken is defined by the connector protocol schema.
//
// One-time enrolment token (docs/SECURITY.md section 6.2). Sensitive: generated models
// wrap this value so that log, debug and default JSON representations redact it. The
// wire value is produced only by the generated canonical encoder.
type EnrolmentToken = SensitiveString

// SessionCapability is defined by the connector protocol schema.
//
// Session-scoped route capability presented when opening a data stream
// (docs/SECURITY.md section 9). Sensitive: it is a bearer credential and is redacted
// in log, debug and default JSON representations.
type SessionCapability = SensitiveString

// PublicKey is defined by the connector protocol schema.
//
// Base64-encoded SubjectPublicKeyInfo for the connector device key. The matching
// private key never leaves the development environment and this protocol has no field
// capable of carrying it (docs/CONNECTOR_PROTOCOL.md section 4.2).
type PublicKey = string

// Certificate is defined by the connector protocol schema.
//
// Base64-encoded signed device identity issued by the control plane.
type Certificate = string

// EnvironmentLabel is defined by the connector protocol schema.
//
// Operator-assigned environment label.
type EnvironmentLabel = string

// ConnectorCapability is defined by the connector protocol schema.
//
// Capability advertised by the connector build. Known version 1 values are listed in
// x-protocol.known_capabilities; unknown values are accepted so that a newer connector
// is classified by docs/CONNECTOR_PROTOCOL.md section 19 rather than rejected
// outright.
type ConnectorCapability = string

// Envelope is defined by the connector protocol schema.
//
// Control-channel message envelope (docs/CONNECTOR_PROTOCOL.md section 7).
type Envelope struct {
	// Protocol version. Stage 0 accepts 1 only; any other value is rejected with
	// PROTOCOL_UNSUPPORTED and is never best-effort parsed.
	ProtocolVersion int64 `json:"protocol_version"`
	// Sender-assigned message identifier, conventionally prefixed msg_.
	MessageID string `json:"message_id"`
	// Version 1 message type. Unknown types are rejected.
	Type MessageType `json:"type"`
	// Time the sender emitted the message.
	SentAt string `json:"sent_at"`
	// Connector identity, conventionally prefixed con_. Absent on the registration
	// exchange, where the identity is still being established, and required on every
	// other message type.
	ConnectorID *string `json:"connector_id,omitempty"`
	// Identifier of the message or command this message answers.
	CorrelationID *string `json:"correlation_id,omitempty"`
}

// EnvironmentDescriptor is defined by the connector protocol schema.
//
// Development environment self-description (docs/CONNECTOR_PROTOCOL.md section 4.3,
// docs/DOMAIN_MODEL.md section 7).
type EnvironmentDescriptor struct {
	// Operator-visible environment name.
	Name string `json:"name"`
	// Operating system. Known version 1 values are in x-protocol.known_platforms.
	Platform string `json:"platform"`
	// CPU architecture. Known version 1 values are in x-protocol.known_architectures.
	Architecture string `json:"architecture"`
	// Optional operator-assigned labels.
	Labels []string `json:"labels,omitempty"`
}

// ConnectorDescriptor is defined by the connector protocol schema.
//
// Connector build self-description (docs/CONNECTOR_PROTOCOL.md section 4.3).
type ConnectorDescriptor struct {
	// Connector release version.
	Version string `json:"version"`
	// Capabilities this connector build supports.
	Capabilities []string `json:"capabilities"`
}

// RegistrationRequest is defined by the connector protocol schema.
//
// Registration request (docs/CONNECTOR_PROTOCOL.md section 4.3). protocol_version is
// carried by the envelope and is not repeated here.
type RegistrationRequest struct {
	// One-time enrolment token. Consumed on success.
	EnrolmentToken SensitiveString `json:"enrolment_token"`
	// Connector device public key.
	PublicKey string `json:"public_key"`
	// Development environment description.
	Environment EnvironmentDescriptor `json:"environment"`
	// Connector build description.
	Connector ConnectorDescriptor `json:"connector"`
}

// SignedIdentity is defined by the connector protocol schema.
//
// Signed device identity issued in exchange for the enrolment token (docs/SECURITY.md
// section 6.2).
type SignedIdentity struct {
	// Signed device identity.
	Certificate string `json:"certificate"`
	// Fingerprint recorded on the connector record (docs/DOMAIN_MODEL.md section 8).
	CertificateFingerprint string `json:"certificate_fingerprint"`
	// Identity expiry. Identities are bounded in time.
	ExpiresAt string `json:"expires_at"`
}

// ControlPlaneEndpoints is defined by the connector protocol schema.
//
// Endpoints the connector dials outbound after enrolment (docs/CONNECTOR_PROTOCOL.md
// section 5).
type ControlPlaneEndpoints struct {
	// Control, heartbeat, routes, events and upgrade channels.
	ControlURL string `json:"control_url"`
	// Multiplexed data streams.
	DataURL string `json:"data_url"`
}

// RegistrationResponse is defined by the connector protocol schema.
//
// Registration response (docs/CONNECTOR_PROTOCOL.md section 4.3): connector ID, signed
// identity, control-plane endpoints and organisation policy digest.
type RegistrationResponse struct {
	// Assigned connector identity, conventionally prefixed con_.
	ConnectorID string `json:"connector_id"`
	// Signed device identity.
	SignedIdentity SignedIdentity `json:"signed_identity"`
	// Outbound endpoints for subsequent connections.
	ControlPlaneEndpoints ControlPlaneEndpoints `json:"control_plane_endpoints"`
	// Digest of the organisation policy the connector must apply.
	PolicyDigest string `json:"policy_digest"`
}

// ResourceSummary is defined by the connector protocol schema.
//
// Optional coarse resource report. additionalProperties is false so that no sensitive
// process detail can be attached (docs/CONNECTOR_PROTOCOL.md section 8).
type ResourceSummary struct {
	// Normalised system load average.
	Load *float64 `json:"load,omitempty"`
	// Available memory in bytes.
	MemoryAvailableBytes *int64 `json:"memory_available_bytes,omitempty"`
}

// Heartbeat is defined by the connector protocol schema.
//
// Heartbeat payload (docs/CONNECTOR_PROTOCOL.md section 8).
type Heartbeat struct {
	// Connector self-reported health. Delayed and disconnected are control-plane
	// conclusions, not self-reports.
	Status HeartbeatStatus `json:"status"`
	// Seconds since connector start.
	UptimeSeconds int64 `json:"uptime_seconds"`
	// Connector release version.
	Version string `json:"version"`
	// Currently published routes.
	ActiveRoutes int64 `json:"active_routes"`
	// Currently open data streams.
	ActiveStreams int64 `json:"active_streams"`
	// Optional resource report.
	ResourceSummary *ResourceSummary `json:"resource_summary,omitempty"`
}

// RoutePublish is defined by the connector protocol schema.
//
// Route publication request from the control plane (docs/CONNECTOR_PROTOCOL.md section
// 11).
type RoutePublish struct {
	// Published-service identity, conventionally prefixed svc_.
	RouteID string `json:"route_id"`
	// Owning project, conventionally prefixed prj_.
	ProjectID string `json:"project_id"`
	// Owning workspace, conventionally prefixed wsp_.
	WorkspaceID string `json:"workspace_id"`
	// Local destination host. The connector still applies its own allow-list; schema
	// acceptance is not authorisation.
	LocalHost string `json:"local_host"`
	// Local destination port.
	LocalPort int64 `json:"local_port"`
	// Protocol spoken to the local destination.
	Protocol DestinationProtocol `json:"protocol"`
	// Publication expiry. Publication always expires.
	ExpiresAt string `json:"expires_at"`
	// Browser sessions authorised to use the route, conventionally prefixed brs_.
	AllowedBrowserSessionIDs []string `json:"allowed_browser_session_ids"`
}

// RoutePublishAck is defined by the connector protocol schema.
//
// Connector acknowledgement of a route publication request (docs/CONNECTOR_PROTOCOL.md
// section 11). Rejection carries a stable error class and no free text, per
// docs/SECURITY.md section 18.
type RoutePublishAck struct {
	// Route this acknowledgement answers.
	RouteID string `json:"route_id"`
	// Outcome of connector validation.
	Status RoutePublishAckStatus `json:"status"`
	// Destination the connector actually opened, as host:port.
	ObservedDestination *string `json:"observed_destination,omitempty"`
	// Stable connector error class explaining a rejection (docs/CONNECTOR_PROTOCOL.md
	// section 21).
	ErrorClass *ErrorClass `json:"error_class,omitempty"`
}

// DataStreamHeader is defined by the connector protocol schema.
//
// Header opening one tunnelled connection on the data channel
// (docs/CONNECTOR_PROTOCOL.md section 12). The connector opens only the pre-authorised
// destination bound to route_id; this header carries no host or port.
type DataStreamHeader struct {
	// Published route this stream belongs to.
	RouteID string `json:"route_id"`
	// Browser session requesting the stream, conventionally prefixed brs_.
	BrowserSessionID string `json:"browser_session_id"`
	// Session-scoped capability authorising use of the route.
	SessionCapability SensitiveString `json:"session_capability"`
	// Application-level stream identifier, unique for the connection.
	StreamID string `json:"stream_id"`
	// Protocol spoken to the local destination.
	DestinationProtocol DestinationProtocol `json:"destination_protocol"`
	// Absolute deadline after which the stream is closed.
	Deadline string `json:"deadline"`
}

// Payload is implemented by every version 1 message payload. The interface is closed:
// only payloads generated from the schema can satisfy it.
type Payload interface {
	// MessageType reports the envelope type this payload belongs to.
	MessageType() MessageType
	isConnectorPayload()
}

// MessageType reports the envelope type carrying a RegistrationRequest.
func (RegistrationRequest) MessageType() MessageType { return MessageTypeConnectorRegistrationRequest }

func (RegistrationRequest) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RegistrationResponse.
func (RegistrationResponse) MessageType() MessageType {
	return MessageTypeConnectorRegistrationResponse
}

func (RegistrationResponse) isConnectorPayload() {}

// MessageType reports the envelope type carrying a Heartbeat.
func (Heartbeat) MessageType() MessageType { return MessageTypeHeartbeat }

func (Heartbeat) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RoutePublish.
func (RoutePublish) MessageType() MessageType { return MessageTypeRoutePublish }

func (RoutePublish) isConnectorPayload() {}

// MessageType reports the envelope type carrying a RoutePublishAck.
func (RoutePublishAck) MessageType() MessageType { return MessageTypeRoutePublishAck }

func (RoutePublishAck) isConnectorPayload() {}

// Frame is a decoded control frame: envelope header plus its typed payload.
type Frame struct {
	Envelope Envelope
	Payload  Payload
}
