// Code generated by packages/protocol/tools/generate.ts from
// schemas/connector/v1.schema.json. DO NOT EDIT.

package connectorv1

import "regexp"

var pattern0 = regexp.MustCompile("^[A-Za-z0-9_-]+$")
var pattern1 = regexp.MustCompile("^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]{1,9})?Z$")
var pattern2 = regexp.MustCompile("^wss://[!-~]+$")
var pattern3 = regexp.MustCompile("^[0-9A-Za-z][0-9A-Za-z.+-]*$")
var pattern4 = regexp.MustCompile("^[A-Za-z0-9:._-]+$")
var pattern5 = regexp.MustCompile("^[A-Za-z0-9._~+/=-]+$")
var pattern6 = regexp.MustCompile("^[A-Za-z0-9+/]+={0,2}$")
var pattern7 = regexp.MustCompile("^[a-z0-9][a-z0-9._-]*$")
var pattern8 = regexp.MustCompile("^[a-z][a-z0-9-]*$")
var pattern9 = regexp.MustCompile("^[^\\x00-\\x1f\\x7f]+$")
var pattern10 = regexp.MustCompile("^[a-z0-9]+$")
var pattern11 = regexp.MustCompile("^[a-z0-9_]+$")
var pattern12 = regexp.MustCompile("^[A-Za-z0-9.:_-]+$")
var pattern13 = regexp.MustCompile("^[A-Za-z0-9.:_\\[\\]-]+:[0-9]{1,5}$")

// validateIdentifier checks opaque durable identifier (docs/DOMAIN_MODEL.md section
// 3). Consumers MUST treat the value as opaque: the schema bounds only its length and
// character class and never its documented prefix.
func validateIdentifier(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern0})
}

// validateTimestamp checks rFC 3339 timestamp in UTC, with a mandatory trailing Z.
func validateTimestamp(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 20, maxLength: 30, pattern: pattern1})
}

// validateWebsocketURL checks outbound WebSocket endpoint. TLS is mandatory, so only
// the wss scheme is accepted (docs/SECURITY.md section 15).
func validateWebsocketURL(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 8, maxLength: 2048, pattern: pattern2})
}

// validateSemanticVersion checks connector release version, for example 0.1.0.
func validateSemanticVersion(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 32, pattern: pattern3})
}

// validateDigest checks opaque digest or fingerprint. Bounded in length and character
// class only.
func validateDigest(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 8, maxLength: 128, pattern: pattern4})
}

// validateEnrolmentToken checks one-time enrolment token (docs/SECURITY.md section
// 6.2). Sensitive: generated models wrap this value so that log, debug and default
// JSON representations redact it. The wire value is produced only by the generated
// canonical encoder.
func validateEnrolmentToken(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 16, maxLength: 256, pattern: pattern5})
}

// validateSessionCapability checks session-scoped route capability presented when
// opening a data stream (docs/SECURITY.md section 9). Sensitive: it is a bearer
// credential and is redacted in log, debug and default JSON representations.
func validateSessionCapability(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 16, maxLength: 512, pattern: pattern5})
}

// validatePublicKey checks base64-encoded SubjectPublicKeyInfo for the connector
// device key. The matching private key never leaves the development environment and
// this protocol has no field capable of carrying it (docs/CONNECTOR_PROTOCOL.md
// section 4.2).
func validatePublicKey(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 32, maxLength: 2048, pattern: pattern6})
}

// validateCertificate checks base64-encoded signed device identity issued by the
// control plane.
func validateCertificate(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 32, maxLength: 8192, pattern: pattern6})
}

// validateEnvironmentLabel checks operator-assigned environment label.
func validateEnvironmentLabel(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern7})
}

// validateConnectorCapability checks capability advertised by the connector build.
// Known version 1 values are listed in x-protocol.known_capabilities; unknown values
// are accepted so that a newer connector is classified by docs/CONNECTOR_PROTOCOL.md
// section 19 rather than rejected outright.
func validateConnectorCapability(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 64, pattern: pattern8})
}

// validateDestinationProtocol checks application protocol spoken to the local
// development service. HTTP upgrade to WebSocket is carried inside http and https
// (docs/CONNECTOR_PROTOCOL.md section 13).
func validateDestinationProtocol(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"http", "https"}})
}

// validateMessageType checks version 1 message type. Unknown types are rejected, never
// ignored. This enumeration MUST equal the keys of x-protocol.messages.
func validateMessageType(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"connector.registration.request", "connector.registration.response", "heartbeat", "route.publish", "route.publish.ack"}})
}

// validateErrorClass checks stable connector error class (docs/CONNECTOR_PROTOCOL.md
// section 21). This enumeration MUST equal x-protocol.error_classes.
func validateErrorClass(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"ENROLMENT_TOKEN_INVALID", "IDENTITY_REVOKED", "PROTOCOL_UNSUPPORTED", "PROJECT_NOT_AUTHORISED", "WORKSPACE_NOT_FOUND", "DESTINATION_NOT_ALLOWED", "PORT_NOT_LISTENING", "ROUTE_LIMIT_EXCEEDED", "ROUTE_EXPIRED", "STREAM_LIMIT_EXCEEDED", "CONTROL_PLANE_UNAVAILABLE", "UPGRADE_REQUIRED"}})
}

// validateEnvelopeProtocolVersion checks protocol version. Stage 0 accepts 1 only; any
// other value is rejected with PROTOCOL_UNSUPPORTED and is never best-effort parsed.
func validateEnvelopeProtocolVersion(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 1)
}

// validateEnvelopePayload checks message payload. Its schema is selected by type.
// Large payloads MUST NOT travel on the control channel; the frame is bounded by
// x-protocol.limits.max_control_frame_bytes and each payload by its own x-max-bytes.
func validateEnvelopePayload(value any, path string, out *[]SchemaViolation) {
	checkPlainObject(value, path, out)
}

// validateEnvelope checks a Envelope value.
func validateEnvelope(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"protocol_version", "message_id", "type", "sent_at", "connector_id", "correlation_id", "payload"}, []string{"protocol_version", "message_id", "type", "sent_at", "payload"})
	if !ok {
		return
	}
	if field, present := source["protocol_version"]; present {
		validateEnvelopeProtocolVersion(field, path+".protocol_version", out)
	}
	if field, present := source["message_id"]; present {
		validateIdentifier(field, path+".message_id", out)
	}
	if field, present := source["type"]; present {
		validateMessageType(field, path+".type", out)
	}
	if field, present := source["sent_at"]; present {
		validateTimestamp(field, path+".sent_at", out)
	}
	if field, present := source["connector_id"]; present {
		validateIdentifier(field, path+".connector_id", out)
	}
	if field, present := source["correlation_id"]; present {
		validateIdentifier(field, path+".correlation_id", out)
	}
	if field, present := source["payload"]; present {
		validateEnvelopePayload(field, path+".payload", out)
	}
	if matchesCondition(source["type"], []string{"connector.registration.request", "connector.registration.response"}) {
		forbidProperty(source, path, "connector_id", "the registration exchange precedes connector identity assignment", out)
	}
	if matchesCondition(source["type"], []string{"heartbeat", "route.publish", "route.publish.ack"}) {
		requireProperty(source, path, "connector_id", "every post-enrolment message is attributed to a connector identity", out)
	}
}

// validateEnvironmentDescriptorName checks operator-visible environment name.
func validateEnvironmentDescriptorName(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 128, pattern: pattern9})
}

// validateEnvironmentDescriptorPlatform checks operating system. Known version 1
// values are in x-protocol.known_platforms.
func validateEnvironmentDescriptorPlatform(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 32, pattern: pattern10})
}

// validateEnvironmentDescriptorArchitecture checks cPU architecture. Known version 1
// values are in x-protocol.known_architectures.
func validateEnvironmentDescriptorArchitecture(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 32, pattern: pattern11})
}

// validateEnvironmentDescriptorLabels checks optional operator-assigned labels.
func validateEnvironmentDescriptorLabels(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 0, 16, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateEnvironmentLabel(item, indexPath(path, index), out)
	}
}

// validateEnvironmentDescriptor checks a EnvironmentDescriptor value.
func validateEnvironmentDescriptor(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"name", "platform", "architecture", "labels"}, []string{"name", "platform", "architecture"})
	if !ok {
		return
	}
	if field, present := source["name"]; present {
		validateEnvironmentDescriptorName(field, path+".name", out)
	}
	if field, present := source["platform"]; present {
		validateEnvironmentDescriptorPlatform(field, path+".platform", out)
	}
	if field, present := source["architecture"]; present {
		validateEnvironmentDescriptorArchitecture(field, path+".architecture", out)
	}
	if field, present := source["labels"]; present {
		validateEnvironmentDescriptorLabels(field, path+".labels", out)
	}
}

// validateConnectorDescriptorCapabilities checks capabilities this connector build
// supports.
func validateConnectorDescriptorCapabilities(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 0, 32, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateConnectorCapability(item, indexPath(path, index), out)
	}
}

// validateConnectorDescriptor checks a ConnectorDescriptor value.
func validateConnectorDescriptor(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"version", "capabilities"}, []string{"version", "capabilities"})
	if !ok {
		return
	}
	if field, present := source["version"]; present {
		validateSemanticVersion(field, path+".version", out)
	}
	if field, present := source["capabilities"]; present {
		validateConnectorDescriptorCapabilities(field, path+".capabilities", out)
	}
}

// validateRegistrationRequest checks a RegistrationRequest value.
func validateRegistrationRequest(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"enrolment_token", "public_key", "environment", "connector"}, []string{"enrolment_token", "public_key", "environment", "connector"})
	if !ok {
		return
	}
	if field, present := source["enrolment_token"]; present {
		validateEnrolmentToken(field, path+".enrolment_token", out)
	}
	if field, present := source["public_key"]; present {
		validatePublicKey(field, path+".public_key", out)
	}
	if field, present := source["environment"]; present {
		validateEnvironmentDescriptor(field, path+".environment", out)
	}
	if field, present := source["connector"]; present {
		validateConnectorDescriptor(field, path+".connector", out)
	}
}

// validateSignedIdentity checks a SignedIdentity value.
func validateSignedIdentity(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"certificate", "certificate_fingerprint", "expires_at"}, []string{"certificate", "certificate_fingerprint", "expires_at"})
	if !ok {
		return
	}
	if field, present := source["certificate"]; present {
		validateCertificate(field, path+".certificate", out)
	}
	if field, present := source["certificate_fingerprint"]; present {
		validateDigest(field, path+".certificate_fingerprint", out)
	}
	if field, present := source["expires_at"]; present {
		validateTimestamp(field, path+".expires_at", out)
	}
}

// validateControlPlaneEndpoints checks a ControlPlaneEndpoints value.
func validateControlPlaneEndpoints(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"control_url", "data_url"}, []string{"control_url", "data_url"})
	if !ok {
		return
	}
	if field, present := source["control_url"]; present {
		validateWebsocketURL(field, path+".control_url", out)
	}
	if field, present := source["data_url"]; present {
		validateWebsocketURL(field, path+".data_url", out)
	}
}

// validateRegistrationResponse checks a RegistrationResponse value.
func validateRegistrationResponse(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"connector_id", "signed_identity", "control_plane_endpoints", "policy_digest"}, []string{"connector_id", "signed_identity", "control_plane_endpoints", "policy_digest"})
	if !ok {
		return
	}
	if field, present := source["connector_id"]; present {
		validateIdentifier(field, path+".connector_id", out)
	}
	if field, present := source["signed_identity"]; present {
		validateSignedIdentity(field, path+".signed_identity", out)
	}
	if field, present := source["control_plane_endpoints"]; present {
		validateControlPlaneEndpoints(field, path+".control_plane_endpoints", out)
	}
	if field, present := source["policy_digest"]; present {
		validateDigest(field, path+".policy_digest", out)
	}
}

// validateResourceSummaryLoad checks normalised system load average.
func validateResourceSummaryLoad(value any, path string, out *[]SchemaViolation) {
	checkNumber(value, path, out, 0, 1024)
}

// validateResourceSummaryMemoryAvailableBytes checks available memory in bytes.
func validateResourceSummaryMemoryAvailableBytes(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 9007199254740991)
}

// validateResourceSummary checks a ResourceSummary value.
func validateResourceSummary(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"load", "memory_available_bytes"}, []string{})
	if !ok {
		return
	}
	if field, present := source["load"]; present {
		validateResourceSummaryLoad(field, path+".load", out)
	}
	if field, present := source["memory_available_bytes"]; present {
		validateResourceSummaryMemoryAvailableBytes(field, path+".memory_available_bytes", out)
	}
}

// validateHeartbeatStatus checks connector self-reported health. Delayed and
// disconnected are control-plane conclusions, not self-reports.
func validateHeartbeatStatus(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"healthy", "degraded"}})
}

// validateHeartbeatUptimeSeconds checks seconds since connector start.
func validateHeartbeatUptimeSeconds(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 3153600000)
}

// validateHeartbeatActiveRoutes checks currently published routes.
func validateHeartbeatActiveRoutes(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 1024)
}

// validateHeartbeatActiveStreams checks currently open data streams.
func validateHeartbeatActiveStreams(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 0, 65535)
}

// validateHeartbeat checks a Heartbeat value.
func validateHeartbeat(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"status", "uptime_seconds", "version", "active_routes", "active_streams", "resource_summary"}, []string{"status", "uptime_seconds", "version", "active_routes", "active_streams"})
	if !ok {
		return
	}
	if field, present := source["status"]; present {
		validateHeartbeatStatus(field, path+".status", out)
	}
	if field, present := source["uptime_seconds"]; present {
		validateHeartbeatUptimeSeconds(field, path+".uptime_seconds", out)
	}
	if field, present := source["version"]; present {
		validateSemanticVersion(field, path+".version", out)
	}
	if field, present := source["active_routes"]; present {
		validateHeartbeatActiveRoutes(field, path+".active_routes", out)
	}
	if field, present := source["active_streams"]; present {
		validateHeartbeatActiveStreams(field, path+".active_streams", out)
	}
	if field, present := source["resource_summary"]; present {
		validateResourceSummary(field, path+".resource_summary", out)
	}
}

// validateRoutePublishLocalHost checks local destination host. The connector still
// applies its own allow-list; schema acceptance is not authorisation.
func validateRoutePublishLocalHost(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 1, maxLength: 255, pattern: pattern12})
}

// validateRoutePublishLocalPort checks local destination port.
func validateRoutePublishLocalPort(value any, path string, out *[]SchemaViolation) {
	checkInteger(value, path, out, 1, 65535)
}

// validateRoutePublishAllowedBrowserSessionIDs checks browser sessions authorised to
// use the route, conventionally prefixed brs_.
func validateRoutePublishAllowedBrowserSessionIDs(value any, path string, out *[]SchemaViolation) {
	items, ok := checkArray(value, path, out, 1, 32, true)
	if !ok {
		return
	}
	for index, item := range items {
		validateIdentifier(item, indexPath(path, index), out)
	}
}

// validateRoutePublish checks a RoutePublish value.
func validateRoutePublish(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"route_id", "project_id", "workspace_id", "local_host", "local_port", "protocol", "expires_at", "allowed_browser_session_ids"}, []string{"route_id", "project_id", "workspace_id", "local_host", "local_port", "protocol", "expires_at", "allowed_browser_session_ids"})
	if !ok {
		return
	}
	if field, present := source["route_id"]; present {
		validateIdentifier(field, path+".route_id", out)
	}
	if field, present := source["project_id"]; present {
		validateIdentifier(field, path+".project_id", out)
	}
	if field, present := source["workspace_id"]; present {
		validateIdentifier(field, path+".workspace_id", out)
	}
	if field, present := source["local_host"]; present {
		validateRoutePublishLocalHost(field, path+".local_host", out)
	}
	if field, present := source["local_port"]; present {
		validateRoutePublishLocalPort(field, path+".local_port", out)
	}
	if field, present := source["protocol"]; present {
		validateDestinationProtocol(field, path+".protocol", out)
	}
	if field, present := source["expires_at"]; present {
		validateTimestamp(field, path+".expires_at", out)
	}
	if field, present := source["allowed_browser_session_ids"]; present {
		validateRoutePublishAllowedBrowserSessionIDs(field, path+".allowed_browser_session_ids", out)
	}
}

// validateRoutePublishAckStatus checks outcome of connector validation.
func validateRoutePublishAckStatus(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{values: []string{"ready", "rejected"}})
}

// validateRoutePublishAckObservedDestination checks destination the connector actually
// opened, as host:port.
func validateRoutePublishAckObservedDestination(value any, path string, out *[]SchemaViolation) {
	checkString(value, path, out, stringOpts{minLength: 3, maxLength: 262, pattern: pattern13})
}

// validateRoutePublishAck checks a RoutePublishAck value.
func validateRoutePublishAck(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"route_id", "status", "observed_destination", "error_class"}, []string{"route_id", "status"})
	if !ok {
		return
	}
	if field, present := source["route_id"]; present {
		validateIdentifier(field, path+".route_id", out)
	}
	if field, present := source["status"]; present {
		validateRoutePublishAckStatus(field, path+".status", out)
	}
	if field, present := source["observed_destination"]; present {
		validateRoutePublishAckObservedDestination(field, path+".observed_destination", out)
	}
	if field, present := source["error_class"]; present {
		validateErrorClass(field, path+".error_class", out)
	}
	if matchesCondition(source["status"], []string{"ready"}) {
		requireProperty(source, path, "observed_destination", "a ready route reports the destination it opened and carries no error class", out)
		forbidProperty(source, path, "error_class", "a ready route reports the destination it opened and carries no error class", out)
	}
	if matchesCondition(source["status"], []string{"rejected"}) {
		requireProperty(source, path, "error_class", "a rejected route reports a stable error class and opens no destination", out)
		forbidProperty(source, path, "observed_destination", "a rejected route reports a stable error class and opens no destination", out)
	}
}

// validateDataStreamHeader checks a DataStreamHeader value.
func validateDataStreamHeader(value any, path string, out *[]SchemaViolation) {
	source, ok := checkObject(value, path, out, []string{"route_id", "browser_session_id", "session_capability", "stream_id", "destination_protocol", "deadline"}, []string{"route_id", "browser_session_id", "session_capability", "stream_id", "destination_protocol", "deadline"})
	if !ok {
		return
	}
	if field, present := source["route_id"]; present {
		validateIdentifier(field, path+".route_id", out)
	}
	if field, present := source["browser_session_id"]; present {
		validateIdentifier(field, path+".browser_session_id", out)
	}
	if field, present := source["session_capability"]; present {
		validateSessionCapability(field, path+".session_capability", out)
	}
	if field, present := source["stream_id"]; present {
		validateIdentifier(field, path+".stream_id", out)
	}
	if field, present := source["destination_protocol"]; present {
		validateDestinationProtocol(field, path+".destination_protocol", out)
	}
	if field, present := source["deadline"]; present {
		validateTimestamp(field, path+".deadline", out)
	}
}
